(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

Notation "'t_Element'" := (nseq int8 32).
Definition Element : both t_Element -> both t_Element :=
  id.

Definition t_Error : choice_type :=
  ('unit).
Notation "'Error_InvalidAddition_case'" := tt (at level 100).
Equations Error_InvalidAddition : both t_Error :=
  Error_InvalidAddition  :=
    solve_lift (ret_both (tt : 'unit : t_Error)) : both t_Error.
Fail Next Obligation.

Notation "'t_P256FieldElement'" := (nat_mod 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff).
Definition P256FieldElement : both t_P256FieldElement -> both t_P256FieldElement :=
  id.

Notation "'t_Affine'" := (t_P256FieldElement × t_P256FieldElement).

Notation "'t_AffineResult'" := (t_Result (t_P256FieldElement × t_P256FieldElement) t_Error).

Notation "'t_JacobianResult'" := (t_Result (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement) t_Error).

Notation "'t_P256Jacobian'" := (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement).

Notation "'t_P256Scalar'" := (nat_mod 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551).
Definition P256Scalar : both t_P256Scalar -> both t_P256Scalar :=
  id.

(*Not implemented yet? todo(item)*)

Equations v_BITS : both uint_size :=
  v_BITS  :=
    solve_lift (ret_both (256 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations affine_to_jacobian (p : both (t_P256FieldElement × t_P256FieldElement)) : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement) :=
  affine_to_jacobian p  :=
    letb '(x,y) := p in
    solve_lift (prod_b (x,y,impl__P256FieldElement__from_literal (ret_both (1 : int128)))) : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement).
Fail Next Obligation.

Equations is_point_at_infinity (p : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement)) : both 'bool :=
  is_point_at_infinity p  :=
    letb '(v__x,v__y,z) := p in
    solve_lift (f_equal z (impl__P256FieldElement__from_literal (ret_both (0 : int128)))) : both 'bool.
Fail Next Obligation.

Equations jacobian_to_affine (p : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement)) : both (t_P256FieldElement × t_P256FieldElement) :=
  jacobian_to_affine p  :=
    letb '(x,y,z) := p in
    letb z2 := f_exp z (ret_both (2 : int32)) in
    letb z2i := impl__P256FieldElement__inv z2 in
    letb z3 := z .* z2 in
    letb z3i := impl__P256FieldElement__inv z3 in
    letb x := x .* z2i in
    letb y := y .* z3i in
    solve_lift (prod_b (x,y)) : both (t_P256FieldElement × t_P256FieldElement).
Fail Next Obligation.

Equations point_double (p : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement)) : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement) :=
  point_double p  :=
    letb '(x1,y1,z1) := p in
    letb delta := f_exp z1 (ret_both (2 : int32)) in
    letb gamma := f_exp y1 (ret_both (2 : int32)) in
    letb beta := x1 .* gamma in
    letb alpha_1_ := x1 .- delta in
    letb alpha_2_ := x1 .+ delta in
    letb alpha := (impl__P256FieldElement__from_literal (ret_both (3 : int128))) .* (alpha_1_ .* alpha_2_) in
    letb x3 := (f_exp alpha (ret_both (2 : int32))) .- ((impl__P256FieldElement__from_literal (ret_both (8 : int128))) .* beta) in
    letb z3___ := f_exp (y1 .+ z1) (ret_both (2 : int32)) in
    letb z3 := z3___ .- (gamma .+ delta) in
    letb y3_1_ := ((impl__P256FieldElement__from_literal (ret_both (4 : int128))) .* beta) .- x3 in
    letb y3_2_ := (impl__P256FieldElement__from_literal (ret_both (8 : int128))) .* (gamma .* gamma) in
    letb y3 := (alpha .* y3_1_) .- y3_2_ in
    solve_lift (prod_b (x3,y3,z3)) : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement).
Fail Next Obligation.

Equations s1_equal_s2 (s1 : both t_P256FieldElement) (s2 : both t_P256FieldElement) : both (t_Result (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement) t_Error) :=
  s1_equal_s2 s1 s2  :=
    solve_lift (ifb f_equal s1 s2
    then v_Err Error_InvalidAddition
    else v_Ok (prod_b (impl__P256FieldElement__from_literal (ret_both (0 : int128)),impl__P256FieldElement__from_literal (ret_both (1 : int128)),impl__P256FieldElement__from_literal (ret_both (0 : int128))))) : both (t_Result (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement) t_Error).
Fail Next Obligation.

Equations point_add_jacob (p : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement)) (q : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement)) : both (t_Result (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement) t_Error) :=
  point_add_jacob p q  :=
    letb result := v_Ok q in
    letb result := ifb not (is_point_at_infinity p)
    then ifb is_point_at_infinity q
    then letb result := v_Ok p in
    result
    else letb '(x1,y1,z1) := p in
    letb '(x2,y2,z2) := q in
    letb z1z1 := f_exp z1 (ret_both (2 : int32)) in
    letb z2z2 := f_exp z2 (ret_both (2 : int32)) in
    letb u1 := x1 .* z2z2 in
    letb u2 := x2 .* z1z1 in
    letb s1 := (y1 .* z2) .* z2z2 in
    letb s2 := (y2 .* z1) .* z1z1 in
    ifb f_equal u1 u2
    then letb result := s1_equal_s2 s1 s2 in
    result
    else letb h := u2 .- u1 in
    letb i := f_exp ((impl__P256FieldElement__from_literal (ret_both (2 : int128))) .* h) (ret_both (2 : int32)) in
    letb j := h .* i in
    letb r := (impl__P256FieldElement__from_literal (ret_both (2 : int128))) .* (s2 .- s1) in
    letb v := u1 .* i in
    letb x3_1_ := (impl__P256FieldElement__from_literal (ret_both (2 : int128))) .* v in
    letb x3_2_ := (f_exp r (ret_both (2 : int32))) .- j in
    letb x3 := x3_2_ .- x3_1_ in
    letb y3_1_ := ((impl__P256FieldElement__from_literal (ret_both (2 : int128))) .* s1) .* j in
    letb y3_2_ := r .* (v .- x3) in
    letb y3 := y3_2_ .- y3_1_ in
    letb z3___ := f_exp (z1 .+ z2) (ret_both (2 : int32)) in
    letb z3 := (z3___ .- (z1z1 .+ z2z2)) .* h in
    letb result := v_Ok (prod_b (x3,y3,z3)) in
    result
    else result in
    solve_lift result : both (t_Result (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement) t_Error).
Fail Next Obligation.

Equations ltr_mul (k : both t_P256Scalar) (p : both (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement)) : both (t_Result (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement) t_Error) :=
  ltr_mul k p  :=
    letb q := prod_b (impl__P256FieldElement__from_literal (ret_both (0 : int128)),impl__P256FieldElement__from_literal (ret_both (1 : int128)),impl__P256FieldElement__from_literal (ret_both (0 : int128))) in
    letb q := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := v_BITS))) q (fun q => fun i =>
      letb q := point_double q in
      ifb f_equal (f_get_bit k ((v_BITS .- (ret_both (1 : uint_size))) .- i)) (f_ONE (ret_both (tt : 'unit)))
      then letm[choice_typeMonad.result_bind_code t_Error] hoist1 := impl__map_err (point_add_jacob q p) f_from in
      Result_Ok (letb q := hoist1 in
      q)
      else Result_Ok q) in
    solve_lift (v_Ok q) : both (t_Result (t_P256FieldElement × t_P256FieldElement × t_P256FieldElement) t_Error).
Fail Next Obligation.

Equations p256_point_mul (k : both t_P256Scalar) (p : both (t_P256FieldElement × t_P256FieldElement)) : both (t_Result (t_P256FieldElement × t_P256FieldElement) t_Error) :=
  p256_point_mul k p  :=
    solve_lift (run (letm[choice_typeMonad.result_bind_code t_Error] jac := impl__map_err (ltr_mul k (affine_to_jacobian p)) f_from in
    Result_Ok (v_Ok (jacobian_to_affine jac)))) : both (t_Result (t_P256FieldElement × t_P256FieldElement) t_Error).
Fail Next Obligation.

Equations point_add_distinct (p : both (t_P256FieldElement × t_P256FieldElement)) (q : both (t_P256FieldElement × t_P256FieldElement)) : both (t_Result (t_P256FieldElement × t_P256FieldElement) t_Error) :=
  point_add_distinct p q  :=
    solve_lift (run (letm[choice_typeMonad.result_bind_code t_Error] r := impl__map_err (point_add_jacob (affine_to_jacobian p) (affine_to_jacobian q)) f_from in
    Result_Ok (v_Ok (jacobian_to_affine r)))) : both (t_Result (t_P256FieldElement × t_P256FieldElement) t_Error).
Fail Next Obligation.

Equations point_add (p : both (t_P256FieldElement × t_P256FieldElement)) (q : both (t_P256FieldElement × t_P256FieldElement)) : both (t_Result (t_P256FieldElement × t_P256FieldElement) t_Error) :=
  point_add p q  :=
    solve_lift (ifb p <> q
    then point_add_distinct p q
    else v_Ok (jacobian_to_affine (point_double (affine_to_jacobian p)))) : both (t_Result (t_P256FieldElement × t_P256FieldElement) t_Error).
Fail Next Obligation.

Equations p256_calculate_w (x : both t_P256FieldElement) : both t_P256FieldElement :=
  p256_calculate_w x  :=
    letb b := impl__P256FieldElement__from_byte_seq_be (impl_52__from_vec (impl__into_vec (unsize (box_new (array_from_list [U8 (ret_both (90 : int8));
      U8 (ret_both (198 : int8));
      U8 (ret_both (53 : int8));
      U8 (ret_both (216 : int8));
      U8 (ret_both (170 : int8));
      U8 (ret_both (58 : int8));
      U8 (ret_both (147 : int8));
      U8 (ret_both (231 : int8));
      U8 (ret_both (179 : int8));
      U8 (ret_both (235 : int8));
      U8 (ret_both (189 : int8));
      U8 (ret_both (85 : int8));
      U8 (ret_both (118 : int8));
      U8 (ret_both (152 : int8));
      U8 (ret_both (134 : int8));
      U8 (ret_both (188 : int8));
      U8 (ret_both (101 : int8));
      U8 (ret_both (29 : int8));
      U8 (ret_both (6 : int8));
      U8 (ret_both (176 : int8));
      U8 (ret_both (204 : int8));
      U8 (ret_both (83 : int8));
      U8 (ret_both (176 : int8));
      U8 (ret_both (246 : int8));
      U8 (ret_both (59 : int8));
      U8 (ret_both (206 : int8));
      U8 (ret_both (60 : int8));
      U8 (ret_both (62 : int8));
      U8 (ret_both (39 : int8));
      U8 (ret_both (210 : int8));
      U8 (ret_both (96 : int8));
      U8 (ret_both (75 : int8))]))))) in
    letb exp := impl__P256FieldElement__from_byte_seq_be (impl_52__from_vec (impl__into_vec (unsize (box_new (array_from_list [U8 (ret_both (63 : int8));
      U8 (ret_both (255 : int8));
      U8 (ret_both (255 : int8));
      U8 (ret_both (255 : int8));
      U8 (ret_both (192 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (64 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (64 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8));
      U8 (ret_both (0 : int8))]))))) in
    letb z := (((x .* x) .* x) .- ((impl__P256FieldElement__from_literal (ret_both (3 : int128))) .* x)) .+ b in
    solve_lift (impl__P256FieldElement__pow_felem z exp) : both t_P256FieldElement.
Fail Next Obligation.

Equations p256_point_mul_base (k : both t_P256Scalar) : both (t_Result (t_P256FieldElement × t_P256FieldElement) t_Error) :=
  p256_point_mul_base k  :=
    letb base_point := prod_b (impl__P256FieldElement__from_byte_seq_be (Element (array_from_list [U8 (ret_both (107 : int8));
        U8 (ret_both (23 : int8));
        U8 (ret_both (209 : int8));
        U8 (ret_both (242 : int8));
        U8 (ret_both (225 : int8));
        U8 (ret_both (44 : int8));
        U8 (ret_both (66 : int8));
        U8 (ret_both (71 : int8));
        U8 (ret_both (248 : int8));
        U8 (ret_both (188 : int8));
        U8 (ret_both (230 : int8));
        U8 (ret_both (229 : int8));
        U8 (ret_both (99 : int8));
        U8 (ret_both (164 : int8));
        U8 (ret_both (64 : int8));
        U8 (ret_both (242 : int8));
        U8 (ret_both (119 : int8));
        U8 (ret_both (3 : int8));
        U8 (ret_both (125 : int8));
        U8 (ret_both (129 : int8));
        U8 (ret_both (45 : int8));
        U8 (ret_both (235 : int8));
        U8 (ret_both (51 : int8));
        U8 (ret_both (160 : int8));
        U8 (ret_both (244 : int8));
        U8 (ret_both (161 : int8));
        U8 (ret_both (57 : int8));
        U8 (ret_both (69 : int8));
        U8 (ret_both (216 : int8));
        U8 (ret_both (152 : int8));
        U8 (ret_both (194 : int8));
        U8 (ret_both (150 : int8))])),impl__P256FieldElement__from_byte_seq_be (Element (array_from_list [U8 (ret_both (79 : int8));
        U8 (ret_both (227 : int8));
        U8 (ret_both (66 : int8));
        U8 (ret_both (226 : int8));
        U8 (ret_both (254 : int8));
        U8 (ret_both (26 : int8));
        U8 (ret_both (127 : int8));
        U8 (ret_both (155 : int8));
        U8 (ret_both (142 : int8));
        U8 (ret_both (231 : int8));
        U8 (ret_both (235 : int8));
        U8 (ret_both (74 : int8));
        U8 (ret_both (124 : int8));
        U8 (ret_both (15 : int8));
        U8 (ret_both (158 : int8));
        U8 (ret_both (22 : int8));
        U8 (ret_both (43 : int8));
        U8 (ret_both (206 : int8));
        U8 (ret_both (51 : int8));
        U8 (ret_both (87 : int8));
        U8 (ret_both (107 : int8));
        U8 (ret_both (49 : int8));
        U8 (ret_both (94 : int8));
        U8 (ret_both (206 : int8));
        U8 (ret_both (203 : int8));
        U8 (ret_both (182 : int8));
        U8 (ret_both (64 : int8));
        U8 (ret_both (104 : int8));
        U8 (ret_both (55 : int8));
        U8 (ret_both (191 : int8));
        U8 (ret_both (81 : int8));
        U8 (ret_both (245 : int8))]))) in
    solve_lift (p256_point_mul k base_point) : both (t_Result (t_P256FieldElement × t_P256FieldElement) t_Error).
Fail Next Obligation.

Equations p256_validate_private_key (k : both (t_Seq t_U8)) : both 'bool :=
  p256_validate_private_key k  :=
    letb valid := ret_both (true : 'bool) in
    letb k_element := impl__P256Scalar__from_byte_seq_be k in
    letb k_element_bytes := impl__P256Scalar__to_byte_seq_be k_element in
    letb all_zero := ret_both (true : 'bool) in
    letb '(all_zero,valid) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len k))) (prod_b (all_zero,valid)) (fun '(all_zero,valid) => fun i =>
      letb all_zero := ifb not (f_equal (k.a[i]) (U8 (ret_both (0 : int8))))
      then letb all_zero := ret_both (false : 'bool) in
      all_zero
      else all_zero in
      ifb not (f_equal (k_element_bytes.a[i]) (k.a[i]))
      then letb valid := ret_both (false : 'bool) in
      prod_b (all_zero,valid)
      else prod_b (all_zero,valid)) in
    solve_lift (andb valid (not all_zero)) : both 'bool.
Fail Next Obligation.

Equations p256_validate_public_key (p : both (t_P256FieldElement × t_P256FieldElement)) : both 'bool :=
  p256_validate_public_key p  :=
    letb b := impl__P256FieldElement__from_byte_seq_be (impl_52__from_vec (impl__into_vec (unsize (box_new (array_from_list [U8 (ret_both (90 : int8));
      U8 (ret_both (198 : int8));
      U8 (ret_both (53 : int8));
      U8 (ret_both (216 : int8));
      U8 (ret_both (170 : int8));
      U8 (ret_both (58 : int8));
      U8 (ret_both (147 : int8));
      U8 (ret_both (231 : int8));
      U8 (ret_both (179 : int8));
      U8 (ret_both (235 : int8));
      U8 (ret_both (189 : int8));
      U8 (ret_both (85 : int8));
      U8 (ret_both (118 : int8));
      U8 (ret_both (152 : int8));
      U8 (ret_both (134 : int8));
      U8 (ret_both (188 : int8));
      U8 (ret_both (101 : int8));
      U8 (ret_both (29 : int8));
      U8 (ret_both (6 : int8));
      U8 (ret_both (176 : int8));
      U8 (ret_both (204 : int8));
      U8 (ret_both (83 : int8));
      U8 (ret_both (176 : int8));
      U8 (ret_both (246 : int8));
      U8 (ret_both (59 : int8));
      U8 (ret_both (206 : int8));
      U8 (ret_both (60 : int8));
      U8 (ret_both (62 : int8));
      U8 (ret_both (39 : int8));
      U8 (ret_both (210 : int8));
      U8 (ret_both (96 : int8));
      U8 (ret_both (75 : int8))]))))) in
    letb point_at_infinity := is_point_at_infinity (affine_to_jacobian p) in
    letb '(x,y) := p in
    letb on_curve := (y .* y) =.? ((((x .* x) .* x) .- ((impl__P256FieldElement__from_literal (ret_both (3 : int128))) .* x)) .+ b) in
    solve_lift (andb (not point_at_infinity) on_curve) : both 'bool.
Fail Next Obligation.
