(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

Notation "'t_Point'" := (t_X25519FieldElement × t_X25519FieldElement).

(*Not implemented yet? todo(item)*)

Equations point_add_and_double (q : both (t_X25519FieldElement × t_X25519FieldElement)) (np : both (t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement)) : both (t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement) :=
  point_add_and_double q np  :=
    letb '(nq,nqp1) := np in
    letb '(x_1_,v__z_1_) := q in
    letb '(x_2_,z_2_) := nq in
    letb '(x_3_,z_3_) := nqp1 in
    letb a := x_2_ .+ z_2_ in
    letb aa := impl__X25519FieldElement__pow a (ret_both (2 : int128)) in
    letb b := x_2_ .- z_2_ in
    letb bb := b .* b in
    letb e := aa .- bb in
    letb c := x_3_ .+ z_3_ in
    letb d := x_3_ .- z_3_ in
    letb da := d .* a in
    letb cb := c .* b in
    letb x_3_ := impl__X25519FieldElement__pow (da .+ cb) (ret_both (2 : int128)) in
    letb z_3_ := x_1_ .* (impl__X25519FieldElement__pow (da .- cb) (ret_both (2 : int128))) in
    letb x_2_ := aa .* bb in
    letb e121665 := impl__X25519FieldElement__from_literal (ret_both (121665 : int128)) in
    letb z_2_ := e .* (aa .+ (e121665 .* e)) in
    solve_lift (prod_b (prod_b (x_2_,z_2_),prod_b (x_3_,z_3_))) : both (t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement).
Fail Next Obligation.

Equations swap (x : both (t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement)) : both (t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement) :=
  swap x  :=
    letb '(x0,x1) := x in
    solve_lift (prod_b (x1,x0)) : both (t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement).
Fail Next Obligation.

Notation "'t_X25519SerializedPoint'" := (nseq int8 32).
Definition X25519SerializedPoint : both t_X25519SerializedPoint -> both t_X25519SerializedPoint :=
  id.

Notation "'t_X25519SerializedScalar'" := (nseq int8 32).
Definition X25519SerializedScalar : both t_X25519SerializedScalar -> both t_X25519SerializedScalar :=
  id.

Notation "'t_X25519FieldElement'" := (nat_mod 0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffed).
Definition X25519FieldElement : both t_X25519FieldElement -> both t_X25519FieldElement :=
  id.

Notation "'t_Scalar'" := (nat_mod 0x8000000000000000000000000000000000000000000000000000000000000000).
Definition Scalar : both t_Scalar -> both t_Scalar :=
  id.

Equations montgomery_ladder (k : both t_Scalar) (init : both (t_X25519FieldElement × t_X25519FieldElement)) : both (t_X25519FieldElement × t_X25519FieldElement) :=
  montgomery_ladder k init  :=
    letb inf := prod_b (impl__X25519FieldElement__from_literal (ret_both (1 : int128)),impl__X25519FieldElement__from_literal (ret_both (0 : int128))) in
    letb (acc : t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement × t_X25519FieldElement) := prod_b (inf,init) in
    letb acc := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := ret_both (256 : uint_size)))) acc (fun acc => fun i =>
      ifb impl__Scalar__bit k ((ret_both (255 : uint_size)) .- i)
      then letb acc := swap acc in
      letb acc := point_add_and_double init acc in
      letb acc := swap acc in
      acc
      else letb acc := point_add_and_double init acc in
      acc) in
    letb '(out,_) := acc in
    solve_lift out : both (t_X25519FieldElement × t_X25519FieldElement).
Fail Next Obligation.

Equations encode_point (p : both (t_X25519FieldElement × t_X25519FieldElement)) : both t_X25519SerializedPoint :=
  encode_point p  :=
    letb '(x,y) := p in
    letb b := x .* (impl__X25519FieldElement__inv y) in
    solve_lift (f_update_start (impl__X25519SerializedPoint__new (ret_both (tt : 'unit))) (impl__X25519FieldElement__to_byte_seq_le b)) : both t_X25519SerializedPoint.
Fail Next Obligation.

Equations decode_point (u : both t_X25519SerializedPoint) : both (t_X25519FieldElement × t_X25519FieldElement) :=
  decode_point u  :=
    letb u___ := u in
    letb u___ := update_at u___ (ret_both (31 : int32)) ((u___.a[(ret_both (31 : int32))]) .& (U8 (ret_both (127 : int8)))) in
    solve_lift (prod_b (impl__X25519FieldElement__from_byte_seq_le u___,impl__X25519FieldElement__from_literal (ret_both (1 : int128)))) : both (t_X25519FieldElement × t_X25519FieldElement).
Fail Next Obligation.

Equations mask_scalar (s : both t_X25519SerializedScalar) : both t_X25519SerializedScalar :=
  mask_scalar s  :=
    letb k := s in
    letb k := update_at k (ret_both (0 : int32)) ((k.a[(ret_both (0 : int32))]) .& (U8 (ret_both (248 : int8)))) in
    letb k := update_at k (ret_both (31 : int32)) ((k.a[(ret_both (31 : int32))]) .& (U8 (ret_both (127 : int8)))) in
    letb k := update_at k (ret_both (31 : int32)) ((k.a[(ret_both (31 : int32))]) .| (U8 (ret_both (64 : int8)))) in
    solve_lift k : both t_X25519SerializedScalar.
Fail Next Obligation.

Equations decode_scalar (s : both t_X25519SerializedScalar) : both t_Scalar :=
  decode_scalar s  :=
    letb k := mask_scalar s in
    solve_lift (impl__Scalar__from_byte_seq_le k) : both t_Scalar.
Fail Next Obligation.

Equations x25519_scalarmult (s : both t_X25519SerializedScalar) (p : both t_X25519SerializedPoint) : both t_X25519SerializedPoint :=
  x25519_scalarmult s p  :=
    letb s___ := decode_scalar s in
    letb p___ := decode_point p in
    letb r := montgomery_ladder s___ p___ in
    solve_lift (encode_point r) : both t_X25519SerializedPoint.
Fail Next Obligation.

Equations x25519_secret_to_public (s : both t_X25519SerializedScalar) : both t_X25519SerializedPoint :=
  x25519_secret_to_public s  :=
    letb base := impl__X25519SerializedPoint__new (ret_both (tt : 'unit)) in
    letb base := update_at base (ret_both (0 : int32)) (U8 (ret_both (9 : int8))) in
    solve_lift (x25519_scalarmult s base) : both t_X25519SerializedPoint.
Fail Next Obligation.
