(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Crypt Require Import jasmin_word.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(* Require Import Group. *)
(* Export Group. *)

(* Require Import Group_Ff. *)
(* Export Group_Ff. *)

(* Require Import Field. *)
(* Export Field. *)

(* Require Import Group. *)
(* Export Group. *)

(* Require Import Gt. *)
(* Export Gt. *)

(* Require Import Add. *)
(* Export Add. *)

(* Notation "'t_G'" := t_Gt. *)

(* Notation "'t_Z'" := f_Scalar. *)

(* (*Not implemented yet? todo(item)*) *)

(* (*Not implemented yet? todo(item)*) *)

(* Equations hash {L1 : {fset Location}} {I1 : Interface} (v__inp : both L1 I1 (t_Vec t_Gt t_Global)) : both L1 I1 t_Scalar := *)
(*   hash v__inp  := *)
(*     solve_lift (impl__Scalar__one (ret_both (tt : 'unit))) : both L1 I1 t_Scalar. *)
(* Fail Next Obligation. *)

Definition t_my_test : choice_type :=
  (int32 × 'bool).
Record t_my_test_rec : Type :=
  { f_temp : int32 ;
    f_other : 'bool ; }.
Definition to_rec : t_my_test -> t_my_test_rec := fun x => {| f_temp := fst x ; f_other := snd x |}.
Definition from_rec (x : t_my_test_rec) : t_my_test := (f_temp x, f_other x).

Record t_my_test_rec_both L I : Type :=
  { f_temp_both : both L I int32 ;
    f_other_both : both L I 'bool ; }.
Arguments f_temp_both {_} {_}.
Arguments f_other_both {_} {_}.

Equations lift_rec {L I} (x : t_my_test_rec) : @t_my_test_rec_both L I :=
  lift_rec x :=
    {|
      f_temp_both := solve_lift ret_both (f_temp x) ;
      f_other_both := solve_lift ret_both (f_other x) ; |}.
Fail Next Obligation.
Equations to_rec_both {L I} (x : both L I t_my_test) : t_my_test_rec_both L I :=
  to_rec_both x :=
    {|
      f_temp_both := bind_both x (fun x => solve_lift ret_both (fst x));
      f_other_both := bind_both x (fun x => solve_lift ret_both (snd x : 'bool));
    |}.
Fail Next Obligation.
Coercion to_rec_both : both >-> t_my_test_rec_both.

Equations from_rec_both {L I} (x : t_my_test_rec_both L I) :  both L I t_my_test :=
  from_rec_both x :=
    solve_lift prod_b(f_temp_both x, f_other_both x).
Fail Next Obligation.
Coercion from_rec_both : t_my_test_rec_both >-> both.

Notation "'matchb' x 'with' '|' a '=>' b 'end'" :=
  (bind_both x (fun y => match y with
                      | a => b end)) (at level 100, a pattern).
Check fun x : both fset0 fset0 t_my_test => matchb x with | (c, _) => ret_both c end.

Equations f_temp {L : {fset Location}} {I : Interface} (s : both L I t_my_test) : both L I int32 :=
  f_temp s  :=
    bind_both s (fun x =>
      solve_lift (ret_both (fst x : int32))) : both L I int32.
Fail Next Obligation.
Equations f_other {L : {fset Location}} {I : Interface} (s : both L I t_my_test) : both L I 'bool :=
  f_other s  :=
    bind_both s (fun x =>
      solve_lift (ret_both (snd x : 'bool))) : both L I 'bool.
Fail Next Obligation.
Inductive t_my_test_ind : forall {L I} (s : both L I t_my_test), Type :=
| Build_t_my_test : forall {L1 L2 I1 I2} {f_temp : both L1 I1 int32} {f_other : both L2 I2 'bool}, t_my_test_ind (prod_b(f_temp, f_other) : both (L1 :|: L2) (I1 :|: I2) t_my_test).
Fail Next Obligation.
Notation "'Build_t_my_test' '[' x ']' '(' 'f_temp' ':=' y ')'" := (Build_t_my_test (f_temp := y) (f_other := f_other x)).

Theorem equality_by_weak_equivalence :
  forall {A : choice_type} (is_pure : A) (is_state : raw_code A) (k : raw_code A -> Prop),
    deterministic is_state ->
  ⊢ ⦃ true_precond ⦄ is_state ≈ ret is_pure ⦃ pre_to_post_ret true_precond is_pure ⦄ ->
  is_state = (ret is_pure).
Proof.
  intros.
  apply (sem_to_det _ _ _ _ X (deterministic_ret is_pure)) in H.
  specialize (H empty_heap empty_heap (ltac:(reflexivity))).
  induction X.
  - now destruct H as [[] ?].
  - admit.
  - rewrite IHX.
Admitted.
  (* intros. *)
  (* apply rf_preserves_eq. *)
  (* Set Printing All. *)
  
  (* inversion H. *)
  (* unfold ssreflect.lock in H0. *)
  (* unfold rel_jdg in H. *)
  (* inversion H. *)

Set Bullet Behavior "Strict Subproofs".
Set Default Goal Selector "!".

Lemma Location_eq_dec : forall x y : Location, {x = y} + {x <> y}.
Proof.
  clear ; intros.
  destruct x as [x0 x1], y as [y0 y1].
  destruct (choice_type_eqP x0 y0).
  - subst.
    destruct (Nat.eq_dec x1 y1).
    + now left.
    + now right.
  - now right.
Qed.

Definition cast_from_one_to_other {L I} {s : _ } (x : @t_my_test_ind L I s) : both L I t_my_test := s.

Program Definition cast_from_one_to_other {L I} (s : both L I t_my_test) : @t_my_test_ind (L :|: L) (I :|: I) (solve_lift s).
Proof.
  pose (split_both s).
  destruct s0 eqn:so.
  assert (forall {L I} {A : choice_type} (s : both L I A),  unsplit_both (split_both s) = s).
  {
    clear ; intros.
    apply both_eq.
    induction A ; simpl ; try reflexivity.
    - destruct s as [[] [] ?] ; simpl in is_valid_code, is_valid_both, p_eq.
      rewrite prod_to_prod_equation_1 ; simpl.
      unfold prod_both0, eq_rect ; destruct ChoiceEquality.prod_both0_obligation_1, ChoiceEquality.prod_both0_obligation_2.
      rewrite prod_both_equation_1.
      simpl; rewrite IHA1, IHA2.
      unfold bind_raw_both ; simpl.
      rewrite <- surjective_pairing.
      f_equal.
      specialize (valid_both_is_deterministic L (A1 × A2) is_pure is_state is_valid_both).
      apply (sem_to_det _ _ _ _ X (deterministic_ret is_pure)) in p_eq.
      specialize (p_eq empty_heap empty_heap Logic.I).
      inversion is_valid_both ; subst.
      + now destruct is_pure.
      + simpl in *.
        (* unfold det_jdg in p_eq. *)
        (* unfold det_run in p_eq. *)
        inversion X ; subst.
        inversion X0 ; subst.
        apply Eqdep_dec.inj_pair2_eq_dec in H3.
        2: apply Location_eq_dec.
        apply Eqdep_dec.inj_pair2_eq_dec in H4.
        2: apply Location_eq_dec.
        f_equal.
        f_equal.
        Require Import FunctionalExtensionality.
        apply functional_extensionality.
        intros x.
        specialize (X1 x).
        inversion X1.
        * subst.
          rewrite <- H0.
          simpl.
          
        
        inversion X1.
        * 

        unfold Location in x.
          apply Nat.eq_dec.
          apply Int.Z_as_Int.eq_dec.
          easy.
        
        inversion X1 ; subst.

        * simpl.
        
      assert (deterministic is_state).
      {
        subst.
        apply deterministic_put.
        apply deterministic_get.
        intros.
        apply deterministic_ret.
      }

        
        destruct both_prog_valid.
        
        destruct is_state.
        apply (sem_to_det _ _ _ _ X (deterministic_ret is_pure)) in p_eq.
        simpl in p_eq.
        
        equality_by_weak_equivalence.
  }  
  
  refine (let '(a, b) := split_both s in _).
  epose (Build_t_my_test (f_temp := a) (f_other := b)).
Proof.
  replace (solve_lift s) with (prod_b (f_temp s, f_other s)).
  apply (Build_t_my_test (f_temp := f_temp s) (f_other := f_other s)).
  apply both_eq.
  simpl.
  destruct s as [[] ? ?].
  rewrite prod_both_equation_1, f_temp_equation_1, f_other_equation_1.
  simpl ; unfold bind_raw_both ; simpl in p_eq |- *.
  f_equal.
  - now destruct is_pure.
  - pattern is_state ; rewrite (equality_by_weak_equivalence is_pure is_state) ; [ | apply p_eq ].
    simpl.
    
    
    replace is_state with (x ← is_state ;; ret ((fst x, snd x) : chProd int32 'bool)) at -1 by now setoid_rewrite <- surjective_pairing ; rewrite bind_ret.
    setoid_rewrite bind_assoc.
    setoid_rewrite bind_assoc.
    setoid_rewrite bind_rewrite.
    rewrite <- (bind_ret _ is_state) at -1.
    rewrite bind_assoc.
    apply f_equal.
    Require Import FunctionalExtensionality.
    apply functional_extensionality.
    intros.
    apply f_equal.
    
    intros x.
  rewrite <- bind_ret.
    apply rf_preserves_eq.
      
    replace (x ← is_state ;; _ (fst x)) with ('(a, b) ← is_state ;; ret a).
    inversion both_prog_valid.
    pose bind_cong.
    rewrite bind_assoc.
    rewrite bind_assoc.
    setoid_rewrite bind_assoc.
    destruct is_state.
    + destruct x.
    + reflexivity.
    + simpl.
      .
      
    rewrite <- bind_ret.
    destruct is_state.
    now destruct x.
    simpl.
    now destruct x0.
  cbn.
  reflexivity.
  cbn in t.
  unfold bind_both in t.
  cbn in t.
  unfold bind_both in t.
  apply t.
  unfold prod_both in t.
  epose (bind_both s (fun '(x, y) => Build_t_my_test x)).
  apply Build_t_my_test.
Check fun x : both fset0 fset0 t_my_test =>
        matchb x with
| Build_t_my_test => _
end.


Print Table Printing Records.
Add Printing Record f_temp.

Class t_Add A B := {
    f_Output : choice_type ;
    f_add_loc : {fset Location} ;
    f_add : forall {L1 L2 I1 I2}, both L1 I1 A -> both L2 I2 B -> both (L1 :|: L2 :|: f_add_loc) (I1 :|: I2) f_Output
  }.

#[global] Program Instance t_my_test_t_Add : t_Add t_my_test t_my_test :=
  let f_Output := t_my_test : choice_type in
  let f_add := fun  {L1 : {fset Location}} {L2 : {fset Location}} {I1 : Interface} {I2 : Interface} (self : both L1 I1 t_my_test) (rhs : both L2 I2 t_my_test) => solve_lift (Build_t_my_test (f_temp := (f_temp self) .+ (f_temp rhs))) : both (L1 :|: L2 :|: fset []) (I1 :|: I2) t_my_test in
  {| f_Output := (@f_Output);
  f_add_loc := (fset [] : {fset Location});
  f_add := (@f_add)|}.
Fail Next Obligation.
Hint Unfold t_my_test_t_Add.
