(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

(*Not implemented yet? todo(item)*)

Notation "'t_Constants'" := (nseq int32 4).
Definition Constants : both t_Constants -> both t_Constants :=
  id.

Notation "'t_State'" := (nseq int32 16).
Definition State : both t_State -> both t_State :=
  id.

Notation "'t_Block'" := (nseq int8 64).
Definition Block : both t_Block -> both t_Block :=
  id.

Notation "'t_ChaChaIV'" := (nseq int8 12).
Definition ChaChaIV : both t_ChaChaIV -> both t_ChaChaIV :=
  id.

Notation "'t_ChaChaKey'" := (nseq int8 32).
Definition ChaChaKey : both t_ChaChaKey -> both t_ChaChaKey :=
  id.

Equations chacha20_line (a : both uint_size) (b : both uint_size) (d : both uint_size) (s : both uint_size) (m : both t_State) : both t_State :=
  chacha20_line a b d s m  :=
    letb state := m in
    letb state := update_at_usize state a ((state.a[a]) .+ (state.a[b])) in
    letb state := update_at_usize state d ((state.a[d]) .^ (state.a[a])) in
    letb state := update_at_usize state d (impl__U32__rotate_left (state.a[d]) s) in
    solve_lift state : both t_State.
Fail Next Obligation.

Equations chacha20_quarter_round (a : both uint_size) (b : both uint_size) (c : both uint_size) (d : both uint_size) (state : both t_State) : both t_State :=
  chacha20_quarter_round a b c d state  :=
    letb state := chacha20_line a b d (ret_both (16 : uint_size)) state in
    letb state := chacha20_line c d b (ret_both (12 : uint_size)) state in
    letb state := chacha20_line a b d (ret_both (8 : uint_size)) state in
    solve_lift (chacha20_line c d b (ret_both (7 : uint_size)) state) : both t_State.
Fail Next Obligation.

Equations chacha20_double_round (state : both t_State) : both t_State :=
  chacha20_double_round state  :=
    letb state := chacha20_quarter_round (ret_both (0 : uint_size)) (ret_both (4 : uint_size)) (ret_both (8 : uint_size)) (ret_both (12 : uint_size)) state in
    letb state := chacha20_quarter_round (ret_both (1 : uint_size)) (ret_both (5 : uint_size)) (ret_both (9 : uint_size)) (ret_both (13 : uint_size)) state in
    letb state := chacha20_quarter_round (ret_both (2 : uint_size)) (ret_both (6 : uint_size)) (ret_both (10 : uint_size)) (ret_both (14 : uint_size)) state in
    letb state := chacha20_quarter_round (ret_both (3 : uint_size)) (ret_both (7 : uint_size)) (ret_both (11 : uint_size)) (ret_both (15 : uint_size)) state in
    letb state := chacha20_quarter_round (ret_both (0 : uint_size)) (ret_both (5 : uint_size)) (ret_both (10 : uint_size)) (ret_both (15 : uint_size)) state in
    letb state := chacha20_quarter_round (ret_both (1 : uint_size)) (ret_both (6 : uint_size)) (ret_both (11 : uint_size)) (ret_both (12 : uint_size)) state in
    letb state := chacha20_quarter_round (ret_both (2 : uint_size)) (ret_both (7 : uint_size)) (ret_both (8 : uint_size)) (ret_both (13 : uint_size)) state in
    solve_lift (chacha20_quarter_round (ret_both (3 : uint_size)) (ret_both (4 : uint_size)) (ret_both (9 : uint_size)) (ret_both (14 : uint_size)) state) : both t_State.
Fail Next Obligation.

Equations chacha20_rounds (state : both t_State) : both t_State :=
  chacha20_rounds state  :=
    letb st := state in
    letb st := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (10 : int32)))) st (fun st => fun v__i =>
      chacha20_double_round st) in
    solve_lift st : both t_State.
Fail Next Obligation.

Equations chacha20_core (ctr : both t_U32) (st0 : both t_State) : both t_State :=
  chacha20_core ctr st0  :=
    letb state := st0 in
    letb state := update_at state (ret_both (12 : int32)) ((state.a[(ret_both (12 : int32))]) .+ ctr) in
    letb k := chacha20_rounds state in
    solve_lift (k .+ state) : both t_State.
Fail Next Obligation.

Equations chacha20_constants_init (_ : both 'unit) : both t_Constants :=
  chacha20_constants_init _  :=
    letb constants := impl__Constants__new (ret_both (tt : 'unit)) in
    letb constants := update_at constants (ret_both (0 : int32)) (U32 (ret_both (1634760805 : int32))) in
    letb constants := update_at constants (ret_both (1 : int32)) (U32 (ret_both (857760878 : int32))) in
    letb constants := update_at constants (ret_both (2 : int32)) (U32 (ret_both (2036477234 : int32))) in
    letb constants := update_at constants (ret_both (3 : int32)) (U32 (ret_both (1797285236 : int32))) in
    solve_lift constants : both t_Constants.
Fail Next Obligation.

Equations chacha20_init (key : both t_ChaChaKey) (iv : both t_ChaChaIV) (ctr : both t_U32) : both t_State :=
  chacha20_init key iv ctr  :=
    letb st := impl__State__new (ret_both (tt : 'unit)) in
    letb st := f_update st (ret_both (0 : uint_size)) (chacha20_constants_init (ret_both (tt : 'unit))) in
    letb st := f_update st (ret_both (4 : uint_size)) (impl__ChaChaKey__to_le_U32s key) in
    letb st := update_at st (ret_both (12 : int32)) ctr in
    letb st := f_update st (ret_both (13 : uint_size)) (impl__ChaChaIV__to_le_U32s iv) in
    solve_lift st : both t_State.
Fail Next Obligation.

Equations chacha20_encrypt_block (st0 : both t_State) (ctr : both t_U32) (plain : both t_Block) : both t_Block :=
  chacha20_encrypt_block st0 ctr plain  :=
    letb st := chacha20_core ctr st0 in
    letb pl := impl__State__from_seq (impl__Block__to_le_U32s plain) in
    letb st := pl .^ st in
    solve_lift (impl__Block__from_seq (impl__State__to_le_bytes st)) : both t_Block.
Fail Next Obligation.

Equations chacha20_encrypt_last (st0 : both t_State) (ctr : both t_U32) (plain : both (t_Seq t_U8)) : both (t_Seq t_U8) :=
  chacha20_encrypt_last st0 ctr plain  :=
    letb b := impl__Block__new (ret_both (tt : 'unit)) in
    letb b := f_update b (ret_both (0 : uint_size)) plain in
    letb b := chacha20_encrypt_block st0 ctr b in
    solve_lift (impl__Block__slice b (ret_both (0 : uint_size)) (impl_41__len plain)) : both (t_Seq t_U8).
Fail Next Obligation.

Equations chacha20_key_block (state : both t_State) : both t_Block :=
  chacha20_key_block state  :=
    letb state := chacha20_core (U32 (ret_both (0 : int32))) state in
    solve_lift (impl__Block__from_seq (impl__State__to_le_bytes state)) : both t_Block.
Fail Next Obligation.

Equations chacha20_key_block0 (key : both t_ChaChaKey) (iv : both t_ChaChaIV) : both t_Block :=
  chacha20_key_block0 key iv  :=
    letb state := chacha20_init key iv (U32 (ret_both (0 : int32))) in
    solve_lift (chacha20_key_block state) : both t_Block.
Fail Next Obligation.

Equations chacha20_update (st0 : both t_State) (m : both (t_Seq t_U8)) : both (t_Seq t_U8) :=
  chacha20_update st0 m  :=
    letb blocks_out := impl_41__new (impl_41__len m) in
    letb n_blocks := impl_41__num_exact_chunks m (ret_both (64 : uint_size)) in
    letb blocks_out := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_blocks))) blocks_out (fun blocks_out => fun i =>
      letb msg_block := impl_41__get_exact_chunk m (ret_both (64 : uint_size)) i in
      letb b := chacha20_encrypt_block st0 (U32 (cast_int (WS2 := _) i)) (impl__Block__from_seq msg_block) in
      letb blocks_out := impl_41__set_exact_chunk blocks_out (ret_both (64 : uint_size)) i b in
      blocks_out) in
    letb last_block := impl_41__get_remainder_chunk m (ret_both (64 : uint_size)) in
    letb blocks_out := ifb (impl_41__len last_block) <> (ret_both (0 : uint_size))
    then letb b := chacha20_encrypt_last st0 (U32 (cast_int (WS2 := _) n_blocks)) last_block in
    letb blocks_out := impl_41__set_chunk blocks_out (ret_both (64 : uint_size)) n_blocks b in
    blocks_out
    else blocks_out in
    solve_lift blocks_out : both (t_Seq t_U8).
Fail Next Obligation.

Equations chacha20 (key : both t_ChaChaKey) (iv : both t_ChaChaIV) (ctr : both int32) (m : both (t_Seq t_U8)) : both (t_Seq t_U8) :=
  chacha20 key iv ctr m  :=
    letb state := chacha20_init key iv (U32 ctr) in
    solve_lift (chacha20_update state m) : both (t_Seq t_U8).
Fail Next Obligation.
