(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

(*Not implemented yet? todo(item)*)

Equations v_BLOCKSIZE : both uint_size :=
  v_BLOCKSIZE  :=
    solve_lift (ret_both (16 : uint_size)) : both uint_size.
Fail Next Obligation.

Notation "'t_Gf128Block'" := (nseq int8 BLOCKSIZE).
Definition Gf128Block : both t_Gf128Block -> both t_Gf128Block :=
  id.

Notation "'t_Gf128Key'" := (nseq int8 BLOCKSIZE).
Definition Gf128Key : both t_Gf128Key -> both t_Gf128Key :=
  id.

Notation "'t_Gf128Tag'" := (nseq int8 BLOCKSIZE).
Definition Gf128Tag : both t_Gf128Tag -> both t_Gf128Tag :=
  id.

Notation "'t_Element'" := t_U128.

Equations decode (e : both t_U128) : both t_Gf128Block :=
  decode e  :=
    solve_lift (impl__Gf128Block__from_seq (v_U128_to_be_bytes e)) : both t_Gf128Block.
Fail Next Obligation.

Equations encode (block : both t_Gf128Block) : both t_U128 :=
  encode block  :=
    solve_lift (v_U128_from_be_bytes (impl__U128Word__from_seq block)) : both t_U128.
Fail Next Obligation.

Equations fadd (x : both t_U128) (y : both t_U128) : both t_U128 :=
  fadd x y  :=
    solve_lift (x .^ y) : both t_U128.
Fail Next Obligation.

Equations v_IRRED : both t_U128 :=
  v_IRRED  :=
    U128 (solve_lift (ret_both (299076299051606071403356588563077529600 : int128))) : both t_U128.
Fail Next Obligation.

Equations fmul (x : both t_U128) (y : both t_U128) : both t_U128 :=
  fmul x y  :=
    letb (res : t_U128) := U128 (ret_both (0 : int128)) in
    letb sh := x in
    letb '(res,sh) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := ret_both (128 : uint_size)))) (prod_b (res,sh)) (fun '(res,sh) => fun i =>
      letb res := ifb (impl__U128__declassify (y .& ((U128 (ret_both (1 : int128))) shift_left ((ret_both (127 : uint_size)) .- i)))) <> (impl__U128__declassify (U128 (ret_both (0 : int128))))
      then letb res := res .^ sh in
      res
      else res in
      ifb (impl__U128__declassify (sh .& (U128 (ret_both (1 : int128))))) <> (impl__U128__declassify (U128 (ret_both (0 : int128))))
      then letb sh := (sh shift_right (ret_both (1 : uint_size))) .^ v_IRRED in
      prod_b (res,sh)
      else letb sh := sh shift_right (ret_both (1 : uint_size)) in
      prod_b (res,sh)) in
    solve_lift res : both t_U128.
Fail Next Obligation.

Equations update (r : both t_U128) (block : both t_Gf128Block) (acc : both t_U128) : both t_U128 :=
  update r block acc  :=
    solve_lift (fmul (fadd (encode block) acc) r) : both t_U128.
Fail Next Obligation.

Equations poly (msg : both (t_Seq t_U8)) (r : both t_U128) : both t_U128 :=
  poly msg r  :=
    letb l := impl_41__len msg in
    letb (n_blocks : uint_size) := l ./ v_BLOCKSIZE in
    letb rem := l .% v_BLOCKSIZE in
    letb acc := U128 (ret_both (0 : int128)) in
    letb acc := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_blocks))) acc (fun acc => fun i =>
      letb k := i .* v_BLOCKSIZE in
      letb block := impl__Gf128Block__new (ret_both (tt : 'unit)) in
      letb block := f_update_start block (impl_41__slice_range msg (Build_t_Range (f_start := k) (f_end := k .+ v_BLOCKSIZE))) in
      letb acc := update r block acc in
      acc) in
    letb acc := ifb rem <> (ret_both (0 : uint_size))
    then letb k := n_blocks .* v_BLOCKSIZE in
    letb last_block := impl__Gf128Block__new (ret_both (tt : 'unit)) in
    letb last_block := f_update_slice last_block (ret_both (0 : uint_size)) msg k rem in
    letb acc := update r last_block acc in
    acc
    else acc in
    solve_lift acc : both t_U128.
Fail Next Obligation.

Equations gmac (text : both (t_Seq t_U8)) (k : both t_Gf128Key) : both t_Gf128Tag :=
  gmac text k  :=
    letb s := impl__Gf128Block__new (ret_both (tt : 'unit)) in
    letb r := encode (impl__Gf128Block__from_seq k) in
    letb a := poly text r in
    solve_lift (impl__Gf128Tag__from_seq (decode (fadd a (encode s)))) : both t_Gf128Tag.
Fail Next Obligation.
