(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

Notation "'t_BlockIndex'" := uint_size.

Notation "'t_FieldElement'" := (nat_mod 0x03fffffffffffffffffffffffffffffffb).
Definition FieldElement : both t_FieldElement -> both t_FieldElement :=
  id.

Notation "'t_Poly1305Tag'" := (nseq int8 16).
Definition Poly1305Tag : both t_Poly1305Tag -> both t_Poly1305Tag :=
  id.

Notation "'t_PolyBlock'" := (nseq int8 16).
Definition PolyBlock : both t_PolyBlock -> both t_PolyBlock :=
  id.

Notation "'t_PolyKey'" := (nseq int8 32).
Definition PolyKey : both t_PolyKey -> both t_PolyKey :=
  id.

Notation "'t_PolyState'" := (t_FieldElement × t_FieldElement × t_PolyKey).

(*Not implemented yet? todo(item)*)

Equations v_BLOCKSIZE : both uint_size :=
  v_BLOCKSIZE  :=
    solve_lift (ret_both (16 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations poly1305_encode_block (b : both t_PolyBlock) : both t_FieldElement :=
  poly1305_encode_block b  :=
    letb n := v_U128_from_le_bytes (impl__U128Word__from_seq b) in
    letb f := impl__FieldElement__from_secret_literal n in
    solve_lift (f .+ (impl__FieldElement__pow2 (ret_both (128 : uint_size)))) : both t_FieldElement.
Fail Next Obligation.

Equations poly1305_update_block (b : both t_PolyBlock) (st : both (t_FieldElement × t_FieldElement × t_PolyKey)) : both (t_FieldElement × t_FieldElement × t_PolyKey) :=
  poly1305_update_block b st  :=
    letb '(acc,r,k) := st in
    solve_lift (prod_b (((poly1305_encode_block b) .+ acc) .* r,r,k)) : both (t_FieldElement × t_FieldElement × t_PolyKey).
Fail Next Obligation.

Equations poly1305_encode_r (b : both t_PolyBlock) : both t_FieldElement :=
  poly1305_encode_r b  :=
    letb n := v_U128_from_le_bytes (impl__U128Word__from_seq b) in
    letb n := n .& (U128 (ret_both (21267647620597763993911028882763415551 : int128))) in
    solve_lift (impl__FieldElement__from_secret_literal n) : both t_FieldElement.
Fail Next Obligation.

Equations poly1305_init (k : both t_PolyKey) : both (t_FieldElement × t_FieldElement × t_PolyKey) :=
  poly1305_init k  :=
    letb r := poly1305_encode_r (impl__PolyBlock__from_slice k (ret_both (0 : uint_size)) (ret_both (16 : uint_size))) in
    solve_lift (prod_b (f_ZERO (ret_both (tt : 'unit)),r,k)) : both (t_FieldElement × t_FieldElement × t_PolyKey).
Fail Next Obligation.

Notation "'t_SubBlock'" := (t_Seq t_U8).

Equations poly1305_encode_last (pad_len : both uint_size) (b : both (t_Seq t_U8)) : both t_FieldElement :=
  poly1305_encode_last pad_len b  :=
    letb n := v_U128_from_le_bytes (impl__U128Word__from_slice b (ret_both (0 : uint_size)) (impl_41__len b)) in
    letb f := impl__FieldElement__from_secret_literal n in
    solve_lift (f .+ (impl__FieldElement__pow2 ((ret_both (8 : uint_size)) .* pad_len))) : both t_FieldElement.
Fail Next Obligation.

Equations poly1305_finish (st : both (t_FieldElement × t_FieldElement × t_PolyKey)) : both t_Poly1305Tag :=
  poly1305_finish st  :=
    letb '(acc,_,k) := st in
    letb n := v_U128_from_le_bytes (impl__U128Word__from_slice k (ret_both (16 : uint_size)) (ret_both (16 : uint_size))) in
    letb aby := impl__FieldElement__to_byte_seq_le acc in
    letb a := v_U128_from_le_bytes (impl__U128Word__from_slice aby (ret_both (0 : uint_size)) (ret_both (16 : uint_size))) in
    solve_lift (impl__Poly1305Tag__from_seq (v_U128_to_le_bytes (a .+ n))) : both t_Poly1305Tag.
Fail Next Obligation.

Equations poly1305_update_blocks (m : both (t_Seq t_U8)) (st : both (t_FieldElement × t_FieldElement × t_PolyKey)) : both (t_FieldElement × t_FieldElement × t_PolyKey) :=
  poly1305_update_blocks m st  :=
    letb st := st in
    letb n_blocks := (impl_41__len m) ./ v_BLOCKSIZE in
    letb st := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_blocks))) st (fun st => fun i =>
      letb block := impl__PolyBlock__from_seq (impl_41__get_exact_chunk m v_BLOCKSIZE i) in
      letb st := poly1305_update_block block st in
      st) in
    solve_lift st : both (t_FieldElement × t_FieldElement × t_PolyKey).
Fail Next Obligation.

Equations poly1305_update_last (pad_len : both uint_size) (b : both (t_Seq t_U8)) (st : both (t_FieldElement × t_FieldElement × t_PolyKey)) : both (t_FieldElement × t_FieldElement × t_PolyKey) :=
  poly1305_update_last pad_len b st  :=
    letb st := st in
    letb st := ifb (impl_41__len b) <> (ret_both (0 : uint_size))
    then letb '(acc,r,k) := st in
    letb st := prod_b (((poly1305_encode_last pad_len b) .+ acc) .* r,r,k) in
    st
    else st in
    solve_lift st : both (t_FieldElement × t_FieldElement × t_PolyKey).
Fail Next Obligation.

Equations poly1305_update (m : both (t_Seq t_U8)) (st : both (t_FieldElement × t_FieldElement × t_PolyKey)) : both (t_FieldElement × t_FieldElement × t_PolyKey) :=
  poly1305_update m st  :=
    letb st := poly1305_update_blocks m st in
    letb last := impl_41__get_remainder_chunk m v_BLOCKSIZE in
    solve_lift (poly1305_update_last (impl_41__len last) last st) : both (t_FieldElement × t_FieldElement × t_PolyKey).
Fail Next Obligation.

Equations poly1305 (m : both (t_Seq t_U8)) (key : both t_PolyKey) : both t_Poly1305Tag :=
  poly1305 m key  :=
    letb st := poly1305_init key in
    letb st := poly1305_update m st in
    solve_lift (poly1305_finish st) : both t_Poly1305Tag.
Fail Next Obligation.
