(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

Require Import Hacspec_pasta.
Export Hacspec_pasta.

(*Not implemented yet? todo(item)*)

Equations sigma (i : both uint_size) (sigma_list : both (t_Seq uint_size)) (q : both (t_Seq (t_Seq uint_size))) : both (t_Seq uint_size) :=
  sigma i sigma_list q  :=
    letb idx := sigma_list.a[i] in
    solve_lift (f_clone (q.a[idx])) : both (t_Seq uint_size).
Fail Next Obligation.

Notation "'t_CRS'" := (t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_FpPallas × t_FpPallas × 'bool).

Notation "'t_Polyx'" := (t_Seq t_FpVesta).

Equations gen_zero_polyx (_ : both 'unit) : both (t_Seq t_FpVesta) :=
  gen_zero_polyx _  :=
    solve_lift (f_create (ret_both (1 : uint_size))) : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations step_15_ (x_3_ : both t_FpVesta) : both t_FpVesta :=
  step_15_ x_3_  :=
    solve_lift x_3_ : both t_FpVesta.
Fail Next Obligation.

Equations step_17_ (x_4_ : both t_FpVesta) : both t_FpVesta :=
  step_17_ x_4_  :=
    solve_lift x_4_ : both t_FpVesta.
Fail Next Obligation.

Equations step_21_ (xi : both t_FpVesta) (z : both t_FpVesta) : both (t_FpVesta × t_FpVesta) :=
  step_21_ xi z  :=
    solve_lift (prod_b (xi,z)) : both (t_FpVesta × t_FpVesta).
Fail Next Obligation.

Equations step_22_ (p : both (t_FpPallas × t_FpPallas × 'bool)) (g0 : both (t_FpPallas × t_FpPallas × 'bool)) (s : both (t_FpPallas × t_FpPallas × 'bool)) (v : both t_FpVesta) (xi : both t_FpVesta) : both (t_FpPallas × t_FpPallas × 'bool) :=
  step_22_ p g0 s v xi  :=
    letb (prod1 : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas v g0 in
    letb (prod1_neg : t_FpPallas × t_FpPallas × 'bool) := g1neg_pallas prod1 in
    letb (prod2 : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas xi s in
    letb (lhs_sum : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas p prod1_neg in
    letb (p_prime : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas lhs_sum prod2 in
    solve_lift p_prime : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations add_scalar_polyx (p : both (t_Seq t_FpVesta)) (s : both t_FpVesta) : both (t_Seq t_FpVesta) :=
  add_scalar_polyx p s  :=
    letb res := f_clone p in
    letb res := ifb (impl_41__len res) =.? (ret_both (0 : uint_size))
    then letb res := f_create (ret_both (1 : uint_size)) in
    res
    else res in
    letb res := update_at_usize res (f_zero (ret_both (tt : 'unit))) ((res.a[(f_zero (ret_both (tt : 'unit)))]) .+ s) in
    solve_lift res : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations gen_one_polyx (_ : both 'unit) : both (t_Seq t_FpVesta) :=
  gen_one_polyx _  :=
    letb poly := f_create (ret_both (1 : uint_size)) in
    letb poly := update_at_usize poly (f_zero (ret_both (tt : 'unit))) (f_ONE (ret_both (tt : 'unit))) in
    solve_lift poly : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations sub_scalar_polyx (p : both (t_Seq t_FpVesta)) (s : both t_FpVesta) : both (t_Seq t_FpVesta) :=
  sub_scalar_polyx p s  :=
    letb res := f_clone p in
    letb res := ifb (impl_41__len res) =.? (ret_both (0 : uint_size))
    then letb res := f_create (ret_both (1 : uint_size)) in
    res
    else res in
    letb res := update_at_usize res (f_zero (ret_both (tt : 'unit))) ((res.a[(f_zero (ret_both (tt : 'unit)))]) .- s) in
    solve_lift res : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations check_not_zero_polyx (p : both (t_Seq t_FpVesta)) : both 'bool :=
  check_not_zero_polyx p  :=
    letb sum := f_ZERO (ret_both (tt : 'unit)) in
    letb all_zero := ret_both (false : 'bool) in
    letb all_zero := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len p))) all_zero (fun all_zero => fun i =>
      ifb (p.a[i]) >.? (f_ZERO (ret_both (tt : 'unit)))
      then letb all_zero := ret_both (true : 'bool) in
      all_zero
      else all_zero) in
    solve_lift all_zero : both 'bool.
Fail Next Obligation.

Equations eval_polyx (p : both (t_Seq t_FpVesta)) (x : both t_FpVesta) : both t_FpVesta :=
  eval_polyx p x  :=
    letb res := f_ZERO (ret_both (tt : 'unit)) in
    letb res := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len p))) res (fun res => fun i =>
      res .+ ((p.a[i]) .* (f_exp x (cast_int (WS2 := _) i)))) in
    solve_lift res : both t_FpVesta.
Fail Next Obligation.

Equations inner_product (u : both (t_Seq t_FpVesta)) (v : both (t_Seq t_FpVesta)) : both t_FpVesta :=
  inner_product u v  :=
    letb res := f_ZERO (ret_both (tt : 'unit)) in
    letb res := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len u))) res (fun res => fun i =>
      res .+ ((u.a[i]) .* (v.a[i]))) in
    solve_lift res : both t_FpVesta.
Fail Next Obligation.

Equations msm (a : both (t_Seq t_FpVesta)) (g : both (t_Seq (t_FpPallas × t_FpPallas × 'bool))) : both (t_FpPallas × t_FpPallas × 'bool) :=
  msm a g  :=
    letb (res : t_FpPallas × t_FpPallas × 'bool) := prod_b (f_ZERO (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)),ret_both (true : 'bool)) in
    letb res := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len a))) res (fun res => fun i =>
      g1add_pallas res (g1mul_pallas (a.a[i]) (g.a[i]))) in
    solve_lift res : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations calculate_L_or_R (p_part : both (t_Seq t_FpVesta)) (b_part : both (t_Seq t_FpVesta)) (g_part : both (t_Seq (t_FpPallas × t_FpPallas × 'bool))) (z : both t_FpVesta) (v_U : both (t_FpPallas × t_FpPallas × 'bool)) (v_W : both (t_FpPallas × t_FpPallas × 'bool)) (blinding : both t_FpVesta) : both (t_FpPallas × t_FpPallas × 'bool) :=
  calculate_L_or_R p_part b_part g_part z v_U v_W blinding  :=
    letb (p_g_msm : t_FpPallas × t_FpPallas × 'bool) := msm (f_clone p_part) g_part in
    letb (p_b_ip : t_FpVesta) := inner_product p_part b_part in
    letb (z_ip : t_FpVesta) := z .* p_b_ip in
    letb (z_ip_U : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas z_ip v_U in
    letb (multed_W : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas blinding v_W in
    letb (part_j : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas p_g_msm z_ip_U in
    letb part_j := g1add_pallas part_j multed_W in
    solve_lift part_j : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations commit_polyx (crs : both (t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_FpPallas × t_FpPallas × 'bool)) (a : both (t_Seq t_FpVesta)) (blinding : both t_FpVesta) : both (t_FpPallas × t_FpPallas × 'bool) :=
  commit_polyx crs a blinding  :=
    letb '(v_G,v_W) := crs in
    letb '(f1,f2,b) := v_W in
    letb (lhs : t_FpPallas × t_FpPallas × 'bool) := msm a (f_clone v_G) in
    letb (rhs : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas blinding (prod_b (f_clone f1,f_clone f2,f_clone b)) in
    letb (res : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas lhs rhs in
    solve_lift res : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations mul_scalar_polyx (p : both (t_Seq t_FpVesta)) (s : both t_FpVesta) : both (t_Seq t_FpVesta) :=
  mul_scalar_polyx p s  :=
    letb res := f_clone p in
    letb res := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len res))) res (fun res => fun i =>
      update_at_usize res i ((p.a[i]) .* s)) in
    solve_lift res : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations rotate_polyx (p : both (t_Seq t_FpVesta)) (rotation : both t_FpVesta) : both (t_Seq t_FpVesta) :=
  rotate_polyx p rotation  :=
    letb res := p in
    letb res := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len res))) res (fun res => fun i =>
      letb coef := res.a[i] in
      letb rot := impl__FpVesta__pow rotation (cast_int (WS2 := _) i) in
      letb res := update_at_usize res i (coef .* rot) in
      res) in
    solve_lift res : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations step_11_ (n_a : both uint_size) (x1 : both t_FpVesta) (x2 : both t_FpVesta) (v_H_prime : both (t_FpPallas × t_FpPallas × 'bool)) (v_R : both (t_FpPallas × t_FpPallas × 'bool)) (a : both (t_Seq (t_FpPallas × t_FpPallas × 'bool))) (q : both (t_Seq (t_Seq uint_size))) (sigma_list : both (t_Seq uint_size)) : both (t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_FpVesta × t_FpVesta) :=
  step_11_ n_a x1 x2 v_H_prime v_R a q sigma_list  :=
    letb (n_q : uint_size) := impl_41__len q in
    letb (qs : t_Seq (t_FpPallas × t_FpPallas × 'bool)) := f_create n_q in
    letb qs := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len qs))) qs (fun qs => fun i =>
      update_at_usize qs i (g1_default_pallas (ret_both (tt : 'unit)))) in
    letb qs := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_a))) qs (fun qs => fun i =>
      letb (a_i : t_FpPallas × t_FpPallas × 'bool) := a.a[i] in
      letb sigma_i := sigma i (f_clone sigma_list) (f_clone q) in
      f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len sigma_i))) qs (fun qs => fun k =>
        letb (j : uint_size) := sigma_i.a[k] in
        letb (q_sigma_i : t_FpPallas × t_FpPallas × 'bool) := qs.a[j] in
        letb (product : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas x1 q_sigma_i in
        letb qs := update_at_usize qs j (g1add_pallas product a_i) in
        qs)) in
    letb (x1_squared : t_FpVesta) := x1 .* x1 in
    letb (q0 : t_FpPallas × t_FpPallas × 'bool) := qs.a[(f_zero (ret_both (tt : 'unit)))] in
    letb (product1 : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas x1_squared q0 in
    letb (product2 : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas x1 v_H_prime in
    letb (sum1 : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas product1 product2 in
    letb (final_sum : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas sum1 v_R in
    letb qs := update_at_usize qs (f_zero (ret_both (tt : 'unit))) final_sum in
    solve_lift (prod_b (qs,x1,x2)) : both (t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_FpVesta × t_FpVesta).
Fail Next Obligation.

Equations step_16_ (n_q : both uint_size) (x3 : both t_FpVesta) (q_polys : both (t_Seq (t_Seq t_FpVesta))) : both (t_Seq t_FpVesta) :=
  step_16_ n_q x3 q_polys  :=
    letb (u : t_Seq t_FpVesta) := f_create n_q in
    letb u := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_q))) u (fun u => fun i =>
      letb (q_i : t_Seq t_FpVesta) := f_clone (q_polys.a[i]) in
      letb (u_i : t_FpVesta) := eval_polyx q_i x3 in
      letb u := update_at_usize u i u_i in
      u) in
    solve_lift u : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations step_18_ (x : both t_FpVesta) (x1 : both t_FpVesta) (x2 : both t_FpVesta) (x3 : both t_FpVesta) (x4 : both t_FpVesta) (omega : both t_FpVesta) (v_Q_prime : both (t_FpPallas × t_FpPallas × 'bool)) (v_Q : both (t_Seq (t_FpPallas × t_FpPallas × 'bool))) (u : both (t_Seq t_FpVesta)) (r : both (t_Seq (t_Seq t_FpVesta))) (q : both (t_Seq (t_Seq uint_size))) : both (t_FpPallas × t_FpPallas × 'bool × t_FpVesta) :=
  step_18_ x x1 x2 x3 x4 omega v_Q_prime v_Q u r q  :=
    letb n_q := impl_41__len q in
    letb v := f_ZERO (ret_both (tt : 'unit)) in
    letb (v_P_sum : t_FpPallas × t_FpPallas × 'bool) := g1_default_pallas (ret_both (tt : 'unit)) in
    letb v_P_sum := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_q))) v_P_sum (fun v_P_sum => fun i =>
      letb (v_Q_i : t_FpPallas × t_FpPallas × 'bool) := v_Q.a[i] in
      letb (term : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas (impl__FpVesta__pow x4 (cast_int (WS2 := _) ((n_q .- i) .- (ret_both (1 : uint_size))))) v_Q_i in
      g1add_pallas v_P_sum term) in
    letb (first_term : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas (impl__FpVesta__pow x4 (cast_int (WS2 := _) n_q)) v_Q_prime in
    letb (v_P : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas first_term v_P_sum in
    letb (vv_first_sum : t_FpVesta) := f_ZERO (ret_both (tt : 'unit)) in
    letb vv_first_sum := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_q))) vv_first_sum (fun vv_first_sum => fun i =>
      letb (q_i : t_Seq uint_size) := f_clone (q.a[i]) in
      letb (n_e : uint_size) := impl_41__len q_i in
      letb (u_i : t_FpVesta) := u.a[i] in
      letb (r_i : t_Seq t_FpVesta) := f_clone (r.a[i]) in
      letb (r_i_x3 : t_FpVesta) := eval_polyx r_i x3 in
      letb (numerator : t_FpVesta) := u_i .- r_i_x3 in
      letb (product : t_FpVesta) := f_ONE (ret_both (tt : 'unit)) in
      letb product := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_e))) product (fun product => fun j =>
        letb (q_i_j : uint_size) := q_i.a[j] in
        letb rhs := (impl__FpVesta__pow omega (cast_int (WS2 := _) q_i_j)) .* x in
        letb term := x3 .- rhs in
        letb product := product .* term in
        product) in
      letb (sum_term : t_FpVesta) := (impl__FpVesta__pow x2 (cast_int (WS2 := _) ((n_q .- i) .- (ret_both (1 : uint_size))))) .* (numerator ./ product) in
      letb vv_first_sum := vv_first_sum .+ sum_term in
      vv_first_sum) in
    letb vv_first_sum := vv_first_sum .* (impl__FpVesta__pow x4 (cast_int (WS2 := _) n_q)) in
    letb (vv_second_sum : t_FpVesta) := f_ZERO (ret_both (tt : 'unit)) in
    letb vv_second_sum := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_q))) vv_second_sum (fun vv_second_sum => fun i =>
      letb (u_i : t_FpVesta) := u.a[i] in
      letb (term : t_FpVesta) := (impl__FpVesta__pow x4 (cast_int (WS2 := _) ((n_q .- (ret_both (1 : uint_size))) .- i))) .* u_i in
      letb vv_second_sum := vv_second_sum .+ term in
      vv_second_sum) in
    letb v := vv_first_sum .+ vv_second_sum in
    solve_lift (prod_b (v_P,v)) : both (t_FpPallas × t_FpPallas × 'bool × t_FpVesta).
Fail Next Obligation.

Equations step_20_ (s : both (t_Seq t_FpVesta)) (crs : both (t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_FpPallas × t_FpPallas × 'bool)) (r : both t_FpVesta) : both (t_FpPallas × t_FpPallas × 'bool × t_FpVesta) :=
  step_20_ s crs r  :=
    letb (v_S : t_FpPallas × t_FpPallas × 'bool) := commit_polyx crs s r in
    solve_lift (prod_b (v_S,r)) : both (t_FpPallas × t_FpPallas × 'bool × t_FpVesta).
Fail Next Obligation.

Equations step_25_ (p_prime : both (t_Seq t_FpVesta)) (v_L_blinding : both (t_Seq t_FpVesta)) (v_R_blinding : both (t_Seq t_FpVesta)) (p_prime_blind : both t_FpVesta) (u : both (t_Seq t_FpVesta)) : both (t_FpVesta × t_FpVesta) :=
  step_25_ p_prime v_L_blinding v_R_blinding p_prime_blind u  :=
    letb c := p_prime.a[(f_zero (ret_both (tt : 'unit)))] in
    letb (f : t_FpVesta) := p_prime_blind in
    letb f := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len v_L_blinding))) f (fun f => fun j =>
      letb (u_j : t_FpVesta) := u.a[j] in
      letb (u_j_inv : t_FpVesta) := impl__FpVesta__inv u_j in
      letb (v_L_j_blinding : t_FpVesta) := v_L_blinding.a[j] in
      letb (v_R_j_blinding : t_FpVesta) := v_R_blinding.a[j] in
      letb f := f .+ (v_L_j_blinding .* u_j_inv) in
      letb f := f .+ (v_R_j_blinding .* u_j) in
      f) in
    solve_lift (prod_b (c,f)) : both (t_FpVesta × t_FpVesta).
Fail Next Obligation.

Equations step_26_ (u : both (t_Seq t_FpVesta)) (v_L : both (t_Seq (t_FpPallas × t_FpPallas × 'bool))) (v_P_prime : both (t_FpPallas × t_FpPallas × 'bool)) (v_R : both (t_Seq (t_FpPallas × t_FpPallas × 'bool))) (c : both t_FpVesta) (v_G_prime_0_ : both (t_FpPallas × t_FpPallas × 'bool)) (b_0_ : both t_FpVesta) (z : both t_FpVesta) (v_U : both (t_FpPallas × t_FpPallas × 'bool)) (f : both t_FpVesta) (v_W : both (t_FpPallas × t_FpPallas × 'bool)) : both 'bool :=
  step_26_ u v_L v_P_prime v_R c v_G_prime_0_ b_0_ z v_U f v_W  :=
    letb (first_sum : t_FpPallas × t_FpPallas × 'bool) := g1_default_pallas (ret_both (tt : 'unit)) in
    letb first_sum := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len u))) first_sum (fun first_sum => fun j =>
      letb (u_j_inv : t_FpVesta) := impl__FpVesta__inv (u.a[j]) in
      letb (v_L_j : t_FpPallas × t_FpPallas × 'bool) := v_L.a[j] in
      letb (prod_j : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas u_j_inv v_L_j in
      letb first_sum := g1add_pallas first_sum prod_j in
      first_sum) in
    letb (second_sum : t_FpPallas × t_FpPallas × 'bool) := g1_default_pallas (ret_both (tt : 'unit)) in
    letb second_sum := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len u))) second_sum (fun second_sum => fun j =>
      letb (u_j : t_FpVesta) := u.a[j] in
      letb (v_R_j : t_FpPallas × t_FpPallas × 'bool) := v_R.a[j] in
      letb (prod_j : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas u_j v_R_j in
      letb second_sum := g1add_pallas second_sum prod_j in
      second_sum) in
    letb (lhs : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas first_sum (g1add_pallas v_P_prime second_sum) in
    letb (rhs_term_1_ : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas c v_G_prime_0_ in
    letb (cb_0z : t_FpVesta) := (c .* b_0_) .* z in
    letb (rhs_term_2_ : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas cb_0z v_U in
    letb (rhs_term_3_ : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas f v_W in
    letb (rhs : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas rhs_term_1_ (g1add_pallas rhs_term_2_ rhs_term_3_) in
    letb (check : 'bool) := lhs =.? rhs in
    solve_lift check : both 'bool.
Fail Next Obligation.

Equations step_6_ (poly_parts : both (t_Seq (t_Seq t_FpVesta))) (crs : both (t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_FpPallas × t_FpPallas × 'bool)) (blindings : both (t_Seq t_FpVesta)) : both (t_Seq (t_FpPallas × t_FpPallas × 'bool)) :=
  step_6_ poly_parts crs blindings  :=
    letb (commitment_seq : t_Seq (t_FpPallas × t_FpPallas × 'bool)) := f_create (impl_41__len poly_parts) in
    letb commitment_seq := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len poly_parts))) commitment_seq (fun commitment_seq => fun i =>
      letb (commitment : t_FpPallas × t_FpPallas × 'bool) := commit_polyx crs (f_clone (poly_parts.a[i])) (blindings.a[i]) in
      letb commitment_seq := update_at_usize commitment_seq i commitment in
      commitment_seq) in
    solve_lift commitment_seq : both (t_Seq (t_FpPallas × t_FpPallas × 'bool)).
Fail Next Obligation.

Equations step_7_ (commitment_seq : both (t_Seq (t_FpPallas × t_FpPallas × 'bool))) (x : both t_FpVesta) (n : both uint_size) : both (t_FpPallas × t_FpPallas × 'bool) :=
  step_7_ commitment_seq x n  :=
    letb (result : t_FpPallas × t_FpPallas × 'bool) := g1_default_pallas (ret_both (tt : 'unit)) in
    letb result := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len commitment_seq))) result (fun result => fun i =>
      letb (power : uint_size) := n .* i in
      letb x_raised := impl__FpVesta__pow x (cast_int (WS2 := _) power) in
      letb (intemidiate : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas x_raised (commitment_seq.a[i]) in
      letb result := g1add_pallas result intemidiate in
      result) in
    solve_lift result : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations step_9_ (r : both (t_Seq t_FpVesta)) (a_prime_seq : both (t_Seq (t_Seq t_FpVesta))) (omega : both t_FpVesta) (p : both (t_Seq (t_Seq uint_size))) (x : both t_FpVesta) : both (t_FpVesta × t_Seq (t_Seq t_FpVesta)) :=
  step_9_ r a_prime_seq omega p x  :=
    letb (n_a : uint_size) := impl_41__len a_prime_seq in
    letb (a_seq : t_Seq (t_Seq t_FpVesta)) := f_create n_a in
    letb a_seq := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_a))) a_seq (fun a_seq => fun i =>
      letb (p_i : t_Seq uint_size) := f_clone (p.a[i]) in
      letb (n_e : uint_size) := impl_41__len p_i in
      letb (a_prime_i : t_Seq t_FpVesta) := f_clone (a_prime_seq.a[i]) in
      letb (a_i_seq : t_Seq t_FpVesta) := f_create n_e in
      letb a_i_seq := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_e))) a_i_seq (fun a_i_seq => fun j =>
        letb (p_i_j : uint_size) := p_i.a[j] in
        letb (argument : t_FpVesta) := (impl__FpVesta__pow omega (cast_int (WS2 := _) p_i_j)) .* x in
        letb (a_i_j : t_FpVesta) := eval_polyx (f_clone a_prime_i) argument in
        letb a_i_seq := update_at_usize a_i_seq j a_i_j in
        a_i_seq) in
      letb a_seq := update_at_usize a_seq i a_i_seq in
      a_seq) in
    letb r_x := eval_polyx r x in
    solve_lift (prod_b (r_x,a_seq)) : both (t_FpVesta × t_Seq (t_Seq t_FpVesta)).
Fail Next Obligation.

Equations trim_polyx (p : both (t_Seq t_FpVesta)) : both (t_Seq t_FpVesta) :=
  trim_polyx p  :=
    letb last_val_idx := ret_both (1 : uint_size) in
    letb last_val_idx := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len p))) last_val_idx (fun last_val_idx => fun i =>
      ifb (p.a[i]) <> (f_ZERO (ret_both (tt : 'unit)))
      then letb last_val_idx := i .+ (ret_both (1 : uint_size)) in
      last_val_idx
      else last_val_idx) in
    letb res := f_create last_val_idx in
    letb res := ifb (impl_41__len p) <> (ret_both (0 : uint_size))
    then f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len res))) res (fun res => fun i =>
      update_at_usize res i (p.a[i]))
    else res in
    letb res := ifb (impl_41__len p) =.? (ret_both (0 : uint_size))
    then letb res := p in
    res
    else res in
    solve_lift res : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations add_polyx (p1 : both (t_Seq t_FpVesta)) (p2 : both (t_Seq t_FpVesta)) : both (t_Seq t_FpVesta) :=
  add_polyx p1 p2  :=
    letb res := f_create (ret_both (0 : uint_size)) in
    letb short_len := ret_both (0 : uint_size) in
    letb '(res,short_len) := ifb (impl_41__len p1) >.? (impl_41__len p2)
    then letb res := f_clone p1 in
    letb short_len := impl_41__len p2 in
    prod_b (res,short_len)
    else letb res := f_clone p2 in
    letb short_len := impl_41__len p1 in
    prod_b (res,short_len) in
    letb res := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := short_len))) res (fun res => fun i =>
      update_at_usize res i ((p1.a[i]) .+ (p2.a[i]))) in
    solve_lift (trim_polyx res) : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations check_equal_polyx (p1 : both (t_Seq t_FpVesta)) (p2 : both (t_Seq t_FpVesta)) : both 'bool :=
  check_equal_polyx p1 p2  :=
    letb is_equal := ret_both (false : 'bool) in
    letb is_equal := ifb (impl_41__len (trim_polyx (f_clone p1))) =.? (impl_41__len (trim_polyx (f_clone p2)))
    then letb is_equal := ret_both (true : 'bool) in
    f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len (trim_polyx (f_clone p1))))) is_equal (fun is_equal => fun i =>
      letb p1_scaler_i := f_clone (p1.a[i]) in
      letb p2_scaler_i := f_clone (p2.a[i]) in
      ifb p1_scaler_i <> p2_scaler_i
      then letb is_equal := ret_both (false : 'bool) in
      is_equal
      else is_equal)
    else is_equal in
    solve_lift is_equal : both 'bool.
Fail Next Obligation.

Equations degree_polyx (p : both (t_Seq t_FpVesta)) : both uint_size :=
  degree_polyx p  :=
    letb len := impl_41__len (trim_polyx p) in
    solve_lift (ifb len =.? (ret_both (0 : uint_size))
    then ret_both (0 : uint_size)
    else len .- (ret_both (1 : uint_size))) : both uint_size.
Fail Next Obligation.

Equations divide_leading_terms (n : both (t_Seq t_FpVesta)) (d : both (t_Seq t_FpVesta)) : both (t_Seq t_FpVesta) :=
  divide_leading_terms n d  :=
    letb (n : t_Seq t_FpVesta) := trim_polyx n in
    letb (d : t_Seq t_FpVesta) := trim_polyx d in
    letb (x_pow : uint_size) := (impl_41__len n) .- (impl_41__len d) in
    letb (n_coeff : t_FpVesta) := n.a[((impl_41__len n) .- (ret_both (1 : uint_size)))] in
    letb (d_coeff : t_FpVesta) := d.a[((impl_41__len d) .- (ret_both (1 : uint_size)))] in
    letb (coeff : t_FpVesta) := n_coeff ./ d_coeff in
    letb (res : t_Seq t_FpVesta) := f_create (x_pow .+ (ret_both (1 : uint_size))) in
    letb res := update_at_usize res x_pow coeff in
    solve_lift res : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations mul_polyx (a : both (t_Seq t_FpVesta)) (b : both (t_Seq t_FpVesta)) : both (t_Seq t_FpVesta) :=
  mul_polyx a b  :=
    letb result := f_create ((impl_41__len a) .+ (impl_41__len b)) in
    letb result := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len a))) result (fun result => fun i =>
      ifb not (f_equal (a.a[i]) (f_default (ret_both (tt : 'unit))))
      then f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len b))) result (fun result => fun j =>
        ifb not (f_equal (b.a[j]) (f_default (ret_both (tt : 'unit))))
        then letb result := update_at_usize result (i .+ j) ((result.a[(i .+ j)]) .+ ((a.a[i]) .* (b.a[j]))) in
        result
        else result)
      else result) in
    solve_lift (trim_polyx result) : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations multi_poly_with_x_pow (p : both (t_Seq t_FpVesta)) (power : both uint_size) : both (t_Seq t_FpVesta) :=
  multi_poly_with_x_pow p power  :=
    letb (p : t_Seq t_FpVesta) := trim_polyx p in
    letb (res : t_Seq t_FpVesta) := f_create ((impl_41__len p) .+ power) in
    letb res := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len p))) res (fun res => fun i =>
      update_at_usize res (i .+ power) (p.a[i])) in
    solve_lift res : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations multi_poly_with_x (p : both (t_Seq t_FpVesta)) : both (t_Seq t_FpVesta) :=
  multi_poly_with_x p  :=
    solve_lift (multi_poly_with_x_pow p (ret_both (1 : uint_size))) : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations compute_vanishing_polynomial (omega : both t_FpVesta) (n : both uint_size) : both (t_Seq t_FpVesta) :=
  compute_vanishing_polynomial omega n  :=
    letb (vanishing_poly : t_Seq t_FpVesta) := f_create (ret_both (1 : uint_size)) in
    letb vanishing_poly := update_at_usize vanishing_poly (f_zero (ret_both (tt : 'unit))) (f_ONE (ret_both (tt : 'unit))) in
    letb vanishing_poly := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n))) vanishing_poly (fun vanishing_poly => fun i =>
      letb eval_point := impl__FpVesta__pow omega (cast_int (WS2 := _) i) in
      letb poly_mul_x := multi_poly_with_x (f_clone vanishing_poly) in
      letb (poly_mul_scalar : t_Seq t_FpVesta) := mul_scalar_polyx (f_clone vanishing_poly) (impl__FpVesta__neg eval_point) in
      letb vanishing_poly := add_polyx poly_mul_x poly_mul_scalar in
      vanishing_poly) in
    solve_lift vanishing_poly : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations step_12_ (n_a : both uint_size) (x1 : both t_FpVesta) (h_prime : both (t_Seq t_FpVesta)) (r : both (t_Seq t_FpVesta)) (a_prime : both (t_Seq (t_Seq t_FpVesta))) (q : both (t_Seq (t_Seq uint_size))) (sigma_list : both (t_Seq uint_size)) (a_blinds : both (t_Seq t_FpVesta)) (r_blind : both t_FpVesta) (h_prime_blind : both t_FpVesta) : both (t_Seq (t_Seq t_FpVesta) × t_Seq t_FpVesta) :=
  step_12_ n_a x1 h_prime r a_prime q sigma_list a_blinds r_blind h_prime_blind  :=
    letb (n_q : uint_size) := impl_41__len q in
    letb (qs : t_Seq (t_Seq t_FpVesta)) := f_create n_q in
    letb q_blinds := f_create n_q in
    letb qs := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len qs))) qs (fun qs => fun i =>
      update_at_usize qs i (f_create (ret_both (1 : uint_size)))) in
    letb '(q_blinds,qs) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_a))) (prod_b (q_blinds,qs)) (fun '(q_blinds,qs) => fun i =>
      letb (a_i : t_Seq t_FpVesta) := f_clone (a_prime.a[i]) in
      letb (a_blind_i : t_FpVesta) := a_blinds.a[i] in
      letb (sigma_i : t_Seq uint_size) := sigma i (f_clone sigma_list) (f_clone q) in
      f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len sigma_i))) (prod_b (q_blinds,qs)) (fun '(q_blinds,qs) => fun j =>
        letb (j : uint_size) := sigma_i.a[j] in
        letb (q_sigma_i : t_Seq t_FpVesta) := f_clone (qs.a[j]) in
        letb (product : t_Seq t_FpVesta) := mul_scalar_polyx (f_clone q_sigma_i) x1 in
        letb qs := update_at_usize qs j (add_polyx product (f_clone a_i)) in
        letb q_blinds := update_at_usize q_blinds j ((x1 .* (q_blinds.a[j])) .+ a_blind_i) in
        prod_b (q_blinds,qs))) in
    letb (x1_squared : t_FpVesta) := x1 .* x1 in
    letb (q0 : t_Seq t_FpVesta) := f_clone (qs.a[(f_zero (ret_both (tt : 'unit)))]) in
    letb (product1 : t_Seq t_FpVesta) := mul_scalar_polyx q0 x1_squared in
    letb (product2 : t_Seq t_FpVesta) := mul_scalar_polyx h_prime x1 in
    letb (sum1 : t_Seq t_FpVesta) := add_polyx product1 product2 in
    letb (final_sum : t_Seq t_FpVesta) := add_polyx sum1 r in
    letb qs := update_at_usize qs (f_zero (ret_both (tt : 'unit))) final_sum in
    letb q_blinds := update_at_usize q_blinds (f_zero (ret_both (tt : 'unit))) (x1_squared .* (q_blinds.a[(f_zero (ret_both (tt : 'unit)))])) in
    letb q_blinds := update_at_usize q_blinds (f_zero (ret_both (tt : 'unit))) ((q_blinds.a[(f_zero (ret_both (tt : 'unit)))]) .+ r_blind) in
    letb q_blinds := update_at_usize q_blinds (f_zero (ret_both (tt : 'unit))) ((q_blinds.a[(f_zero (ret_both (tt : 'unit)))]) .+ (h_prime_blind .* x1)) in
    solve_lift (prod_b (qs,q_blinds)) : both (t_Seq (t_Seq t_FpVesta) × t_Seq t_FpVesta).
Fail Next Obligation.

Equations step_13_ (n : both uint_size) (omega : both t_FpVesta) (x : both t_FpVesta) (x1 : both t_FpVesta) (r : both t_FpVesta) (s : both (t_Seq (t_Seq t_FpVesta))) (q : both (t_Seq (t_Seq uint_size))) (sigma_list : both (t_Seq uint_size)) (g_prime_eval_combined_from_a : both t_FpVesta) (g_prime : both (t_Seq t_FpVesta)) : both (t_Seq (t_Seq t_FpVesta) × t_Seq (t_Seq t_FpVesta)) :=
  step_13_ n omega x x1 r s q sigma_list g_prime_eval_combined_from_a g_prime  :=
    letb (n_a : uint_size) := impl_41__len s in
    letb (n_q : uint_size) := impl_41__len q in
    letb (rs : t_Seq (t_Seq t_FpVesta)) := f_create n_q in
    letb rs := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len rs))) rs (fun rs => fun i =>
      update_at_usize rs i (f_create (ret_both (1 : uint_size)))) in
    letb rs := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_a))) rs (fun rs => fun i =>
      letb (s_i : t_Seq t_FpVesta) := f_clone (s.a[i]) in
      letb (sigma_i : t_Seq uint_size) := sigma i (f_clone sigma_list) (f_clone q) in
      f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len sigma_i))) rs (fun rs => fun j =>
        letb j := sigma_i.a[j] in
        letb r_sigma_i := f_clone (rs.a[j]) in
        letb product := mul_scalar_polyx (f_clone r_sigma_i) x1 in
        letb rs := update_at_usize rs j (add_polyx product (f_clone s_i)) in
        rs)) in
    letb rs_verifier := f_clone rs in
    letb rs_prover := rs in
    letb (g_prime_x : t_FpVesta) := eval_polyx g_prime x in
    letb (vanishing_poly : t_Seq t_FpVesta) := compute_vanishing_polynomial omega n in
    letb (vanishing_poly_x : t_FpVesta) := eval_polyx vanishing_poly x in
    letb h := g_prime_x ./ vanishing_poly_x in
    letb (x1_squared : t_FpVesta) := x1 .* x1 in
    letb (r0 : t_Seq t_FpVesta) := f_clone (rs_prover.a[(f_zero (ret_both (tt : 'unit)))]) in
    letb product1 := mul_scalar_polyx r0 x1_squared in
    letb product2 := h .* x1 in
    letb sum1 := add_scalar_polyx product1 product2 in
    letb final_sum := add_scalar_polyx sum1 r in
    letb rs_prover := update_at_usize rs_prover (f_zero (ret_both (tt : 'unit))) final_sum in
    letb (vanishing_poly : t_Seq t_FpVesta) := compute_vanishing_polynomial omega n in
    letb (vanishing_poly_x : t_FpVesta) := eval_polyx vanishing_poly x in
    letb h := g_prime_eval_combined_from_a ./ vanishing_poly_x in
    letb (x1_squared : t_FpVesta) := x1 .* x1 in
    letb (r0 : t_Seq t_FpVesta) := f_clone (rs_verifier.a[(f_zero (ret_both (tt : 'unit)))]) in
    letb product1 := mul_scalar_polyx r0 x1_squared in
    letb product2 := h .* x1 in
    letb sum1 := add_scalar_polyx product1 product2 in
    letb final_sum := add_scalar_polyx sum1 r in
    letb rs_verifier := update_at_usize rs_verifier (f_zero (ret_both (tt : 'unit))) final_sum in
    solve_lift (prod_b (rs_prover,rs_verifier)) : both (t_Seq (t_Seq t_FpVesta) × t_Seq (t_Seq t_FpVesta)).
Fail Next Obligation.

Equations step_19_ (x4 : both t_FpVesta) (q_prime : both (t_Seq t_FpVesta)) (q_polys : both (t_Seq (t_Seq t_FpVesta))) (q_blinds : both (t_Seq t_FpVesta)) (q_prime_blind : both t_FpVesta) : both (t_Seq t_FpVesta × t_FpVesta) :=
  step_19_ x4 q_prime q_polys q_blinds q_prime_blind  :=
    letb p := f_create (ret_both (1 : uint_size)) in
    letb (n_q : uint_size) := impl_41__len q_polys in
    letb p_blind := f_ZERO (ret_both (tt : 'unit)) in
    letb '(p,p_blind) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_q))) (prod_b (p,p_blind)) (fun '(p,p_blind) => fun i =>
      letb (power : uint_size) := (n_q .- (ret_both (1 : uint_size))) .- i in
      letb x4_powered := impl__FpVesta__pow x4 (cast_int (WS2 := _) power) in
      letb q_i := f_clone (q_polys.a[i]) in
      letb multed_poly := mul_scalar_polyx q_i x4_powered in
      letb p := add_polyx p multed_poly in
      letb p_blind := p_blind .+ (x4_powered .* (q_blinds.a[i])) in
      prod_b (p,p_blind)) in
    letb (x4n_q : t_FpVesta) := impl__FpVesta__pow x4 (cast_int (WS2 := _) n_q) in
    letb (first_term : t_Seq t_FpVesta) := mul_scalar_polyx q_prime x4n_q in
    letb p := add_polyx p first_term in
    letb p_blind := p_blind .+ (x4n_q .* q_prime_blind) in
    solve_lift (prod_b (p,p_blind)) : both (t_Seq t_FpVesta × t_FpVesta).
Fail Next Obligation.

Equations step_23_ (p : both (t_Seq t_FpVesta)) (s : both (t_Seq t_FpVesta)) (x3 : both t_FpVesta) (xi : both t_FpVesta) (p_blind : both t_FpVesta) (s_blind : both t_FpVesta) : both (t_Seq t_FpVesta × t_FpVesta) :=
  step_23_ p s x3 xi p_blind s_blind  :=
    letb p_eval_x3 := eval_polyx (f_clone p) x3 in
    letb xi_mul_s := mul_scalar_polyx s xi in
    letb p_prime := p in
    letb p_prime := sub_scalar_polyx p_prime p_eval_x3 in
    letb p_prime := add_polyx p_prime xi_mul_s in
    letb p_prime_blind := (s_blind .* xi) .+ p_blind in
    solve_lift (prod_b (p_prime,p_prime_blind)) : both (t_Seq t_FpVesta × t_FpVesta).
Fail Next Obligation.

Equations step_24_ (p_prime_poly : both (t_Seq t_FpVesta)) (v_G : both (t_Seq (t_FpPallas × t_FpPallas × 'bool))) (x3 : both t_FpVesta) (z : both t_FpVesta) (v_U : both (t_FpPallas × t_FpPallas × 'bool)) (v_W : both (t_FpPallas × t_FpPallas × 'bool)) (n : both uint_size) (k : both uint_size) (u : both (t_Seq t_FpVesta)) (v_L_blinding : both (t_Seq t_FpVesta)) (v_R_blinding : both (t_Seq t_FpVesta)) : both (t_Seq t_FpVesta × t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_Seq t_FpVesta × t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_Seq t_FpVesta × t_Seq t_FpVesta) :=
  step_24_ p_prime_poly v_G x3 z v_U v_W n k u v_L_blinding v_R_blinding  :=
    letb (p_prime : t_Seq t_FpVesta) := p_prime_poly in
    letb (g_prime : t_Seq (t_FpPallas × t_FpPallas × 'bool)) := v_G in
    letb (b : t_Seq t_FpVesta) := f_create n in
    letb (v_L : t_Seq (t_FpPallas × t_FpPallas × 'bool)) := f_create k in
    letb (v_R : t_Seq (t_FpPallas × t_FpPallas × 'bool)) := f_create k in
    letb b := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len b))) b (fun b => fun i =>
      letb (x3_powered : t_FpVesta) := impl__FpVesta__pow x3 (cast_int (WS2 := _) i) in
      letb b := update_at_usize b i x3_powered in
      b) in
    letb '(v_L,v_R,b,g_prime,p_prime) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := k))) (prod_b (v_L,v_R,b,g_prime,p_prime)) (fun '(v_L,v_R,b,g_prime,p_prime) => fun j =>
      letb (p_prime_half : uint_size) := (impl_41__len p_prime) ./ (ret_both (2 : uint_size)) in
      letb (g_prime_half : uint_size) := (impl_41__len g_prime) ./ (ret_both (2 : uint_size)) in
      letb (b_half : uint_size) := (impl_41__len b) ./ (ret_both (2 : uint_size)) in
      letb (p_prime_lo : t_Seq t_FpVesta) := impl_41__slice p_prime (ret_both (0 : uint_size)) p_prime_half in
      letb (p_prime_hi : t_Seq t_FpVesta) := impl_41__slice p_prime p_prime_half p_prime_half in
      letb (g_prime_lo : t_Seq (t_FpPallas × t_FpPallas × 'bool)) := impl_41__slice g_prime (ret_both (0 : uint_size)) g_prime_half in
      letb (g_prime_hi : t_Seq (t_FpPallas × t_FpPallas × 'bool)) := impl_41__slice g_prime g_prime_half g_prime_half in
      letb (b_lo : t_Seq t_FpVesta) := impl_41__slice b (ret_both (0 : uint_size)) b_half in
      letb (b_hi : t_Seq t_FpVesta) := impl_41__slice b b_half b_half in
      letb (v_L_j : t_FpPallas × t_FpPallas × 'bool) := calculate_L_or_R (f_clone p_prime_hi) (f_clone b_lo) (f_clone g_prime_lo) z v_U v_W (v_L_blinding.a[j]) in
      letb v_L := update_at_usize v_L j v_L_j in
      letb (v_R_j : t_FpPallas × t_FpPallas × 'bool) := calculate_L_or_R (f_clone p_prime_lo) (f_clone b_hi) (f_clone g_prime_hi) z v_U v_W (v_R_blinding.a[j]) in
      letb v_R := update_at_usize v_R j v_R_j in
      letb (u_j : t_FpVesta) := u.a[j] in
      letb (new_g_prime : t_Seq (t_FpPallas × t_FpPallas × 'bool)) := f_create g_prime_half in
      letb new_g_prime := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len new_g_prime))) new_g_prime (fun new_g_prime => fun i =>
        letb (g_prime_hi_indexed : t_FpPallas × t_FpPallas × 'bool) := g_prime_hi.a[i] in
        letb (g_prime_lo_indexed : t_FpPallas × t_FpPallas × 'bool) := g_prime_lo.a[i] in
        letb (rhs_product : t_FpPallas × t_FpPallas × 'bool) := g1mul_pallas u_j g_prime_hi_indexed in
        letb (sum : t_FpPallas × t_FpPallas × 'bool) := g1add_pallas g_prime_lo_indexed rhs_product in
        letb new_g_prime := update_at_usize new_g_prime i sum in
        new_g_prime) in
      letb g_prime := new_g_prime in
      letb (rhs : t_Seq t_FpVesta) := mul_scalar_polyx (f_clone b_hi) u_j in
      letb (new_b : t_Seq t_FpVesta) := add_polyx (f_clone b_lo) rhs in
      letb b := new_b in
      letb (u_j_inv : t_FpVesta) := impl__FpVesta__inv u_j in
      letb (rhs : t_Seq t_FpVesta) := mul_scalar_polyx (f_clone p_prime_hi) u_j_inv in
      letb (new_p_prime : t_Seq t_FpVesta) := add_polyx (f_clone p_prime_lo) rhs in
      letb p_prime := new_p_prime in
      prod_b (v_L,v_R,b,g_prime,p_prime)) in
    solve_lift (prod_b (p_prime,g_prime,b,v_L,v_R,v_L_blinding,v_R_blinding)) : both (t_Seq t_FpVesta × t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_Seq t_FpVesta × t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_Seq t_FpVesta × t_Seq t_FpVesta).
Fail Next Obligation.

Equations step_5_ (h : both (t_Seq t_FpVesta)) (n : both uint_size) (n_g : both uint_size) : both (t_Seq (t_Seq t_FpVesta)) :=
  step_5_ h n n_g  :=
    letb h := trim_polyx h in
    letb n_g := n_g in
    letb n := n in
    letb index_in_h := ret_both (0 : uint_size) in
    letb poly_parts := f_create (n_g .- (ret_both (1 : uint_size))) in
    letb '(index_in_h,poly_parts) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_g .- (ret_both (1 : uint_size))))) (prod_b (index_in_h,poly_parts)) (fun '(index_in_h,poly_parts) => fun i =>
      letb current_poly_part := f_create n in
      letb '(current_poly_part,index_in_h) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n))) (prod_b (current_poly_part,index_in_h)) (fun '(current_poly_part,index_in_h) => fun j =>
        ifb index_in_h <.? (impl_41__len h)
        then letb current_poly_part := update_at_usize current_poly_part j (h.a[index_in_h]) in
        letb index_in_h := index_in_h .+ (ret_both (1 : uint_size)) in
        prod_b (current_poly_part,index_in_h)
        else prod_b (current_poly_part,index_in_h)) in
      letb poly_parts := update_at_usize poly_parts i current_poly_part in
      prod_b (index_in_h,poly_parts)) in
    solve_lift poly_parts : both (t_Seq (t_Seq t_FpVesta)).
Fail Next Obligation.

Equations step_8_ (h_parts : both (t_Seq (t_Seq t_FpVesta))) (x : both t_FpVesta) (n : both uint_size) (h_blinds : both (t_Seq t_FpVesta)) : both (t_Seq t_FpVesta × t_FpVesta) :=
  step_8_ h_parts x n h_blinds  :=
    letb (res : t_Seq t_FpVesta) := f_create (ret_both (1 : uint_size)) in
    letb h_prime_blind := f_ZERO (ret_both (tt : 'unit)) in
    letb '(h_prime_blind,res) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len h_parts))) (prod_b (h_prime_blind,res)) (fun '(h_prime_blind,res) => fun i =>
      letb (power : uint_size) := n .* i in
      letb (x_raised : t_FpVesta) := impl__FpVesta__pow x (cast_int (WS2 := _) power) in
      letb (h_i : t_Seq t_FpVesta) := f_clone (h_parts.a[i]) in
      letb (aux_prod : t_Seq t_FpVesta) := mul_scalar_polyx h_i x_raised in
      letb res := add_polyx res aux_prod in
      letb h_prime_blind := h_prime_blind .+ ((h_blinds.a[i]) .* x_raised) in
      prod_b (h_prime_blind,res)) in
    solve_lift (prod_b (res,h_prime_blind)) : both (t_Seq t_FpVesta × t_FpVesta).
Fail Next Obligation.

Equations sub_polyx (p1 : both (t_Seq t_FpVesta)) (p2 : both (t_Seq t_FpVesta)) : both (t_Seq t_FpVesta) :=
  sub_polyx p1 p2  :=
    letb largest := impl_41__len p1 in
    letb largest := ifb (impl_41__len p2) >.? (impl_41__len p1)
    then letb largest := impl_41__len p2 in
    largest
    else largest in
    letb res := f_create largest in
    letb res := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len p1))) res (fun res => fun i =>
      update_at_usize res i (p1.a[i])) in
    letb res := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len p2))) res (fun res => fun i =>
      update_at_usize res i ((res.a[i]) .- (p2.a[i]))) in
    solve_lift (trim_polyx res) : both (t_Seq t_FpVesta).
Fail Next Obligation.

Equations divide_polyx (n : both (t_Seq t_FpVesta)) (d : both (t_Seq t_FpVesta)) : both (t_Seq t_FpVesta × t_Seq t_FpVesta) :=
  divide_polyx n d  :=
    letb (q : t_Seq t_FpVesta) := f_create (impl_41__len n) in
    letb (r : t_Seq t_FpVesta) := f_clone n in
    letb loop_upper_bound := impl_41__len d in
    letb loop_upper_bound := ifb (impl_41__len q) >.? (impl_41__len d)
    then letb loop_upper_bound := impl_41__len q in
    loop_upper_bound
    else loop_upper_bound in
    letb '(q,r) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := loop_upper_bound))) (prod_b (q,r)) (fun '(q,r) => fun _ =>
      ifb andb (check_not_zero_polyx (f_clone r)) ((degree_polyx (f_clone r)) >=.? (degree_polyx (f_clone d)))
      then letb (t : t_Seq t_FpVesta) := divide_leading_terms (f_clone r) (f_clone d) in
      letb q := add_polyx q (f_clone t) in
      letb (aux_prod : t_Seq t_FpVesta) := mul_polyx (f_clone d) (f_clone t) in
      letb r := sub_polyx r aux_prod in
      prod_b (q,r)
      else prod_b (q,r)) in
    solve_lift (prod_b (trim_polyx q,trim_polyx r)) : both (t_Seq t_FpVesta × t_Seq t_FpVesta).
Fail Next Obligation.

(*item error backend*)

(*item error backend*)

Equations step_10_ (omega : both t_FpVesta) (p : both (t_Seq (t_Seq uint_size))) (x : both t_FpVesta) (a : both (t_Seq (t_Seq t_FpVesta))) : both (t_Seq (t_Seq t_FpVesta)) :=
  step_10_ omega p x a  :=
    letb n_a := impl_41__len a in
    letb s := f_create n_a in
    letb s := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_a))) s (fun s => fun i =>
      letb a_i := f_clone (a.a[i]) in
      letb p_i := f_clone (p.a[i]) in
      letb n_e := impl_41__len p_i in
      letb (points : t_Seq (t_FpVesta × t_FpVesta)) := f_create n_e in
      letb points := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_e))) points (fun points => fun j =>
        letb (p_i_j : uint_size) := p_i.a[j] in
        letb x_j := (impl__FpVesta__pow omega (cast_int (WS2 := _) p_i_j)) .* x in
        letb y_j := a_i.a[j] in
        letb points := update_at_usize points j (prod_b (x_j,y_j)) in
        points) in
      letb (s_i : t_Seq t_FpVesta) := lagrange_polyx points in
      letb s := update_at_usize s i s_i in
      s) in
    solve_lift s : both (t_Seq (t_Seq t_FpVesta)).
Fail Next Obligation.

Equations step_14_ (crs : both (t_Seq (t_FpPallas × t_FpPallas × 'bool) × t_FpPallas × t_FpPallas × 'bool)) (x2 : both t_FpVesta) (q_polys : both (t_Seq (t_Seq t_FpVesta))) (r_polys : both (t_Seq (t_Seq t_FpVesta))) (q : both (t_Seq (t_Seq uint_size))) (blinding : both t_FpVesta) (omega : both t_FpVesta) (x : both t_FpVesta) : both (t_FpPallas × t_FpPallas × 'bool × t_Seq t_FpVesta × t_FpVesta) :=
  step_14_ crs x2 q_polys r_polys q blinding omega x  :=
    letb (q_prime : t_Seq t_FpVesta) := f_create (ret_both (1 : uint_size)) in
    letb (n_q : uint_size) := impl_41__len q in
    letb q_prime := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_q))) q_prime (fun q_prime => fun i =>
      letb (x2_powered : t_FpVesta) := impl__FpVesta__pow x2 (cast_int (WS2 := _) ((n_q .- (ret_both (1 : uint_size))) .- i)) in
      letb (q_poly_i : t_Seq t_FpVesta) := f_clone (q_polys.a[i]) in
      letb (r_i : t_Seq t_FpVesta) := f_clone (r_polys.a[i]) in
      letb (q_i_sub_r_i : t_Seq t_FpVesta) := sub_polyx q_poly_i r_i in
      letb (q_i : t_Seq uint_size) := f_clone (q.a[i]) in
      letb (divisor : t_Seq t_FpVesta) := f_create (ret_both (1 : uint_size)) in
      letb divisor := update_at_usize divisor (f_zero (ret_both (tt : 'unit))) (f_ONE (ret_both (tt : 'unit))) in
      letb divisor := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__len q_i))) divisor (fun divisor => fun j =>
        letb (q_i_j : uint_size) := q_i.a[j] in
        letb (scalar : t_FpVesta) := (impl__FpVesta__pow omega (cast_int (WS2 := _) q_i_j)) .* x in
        letb (divisor_mul_x : t_Seq t_FpVesta) := multi_poly_with_x (f_clone divisor) in
        letb (divisor_mul_scalar : t_Seq t_FpVesta) := mul_scalar_polyx (f_clone divisor) (impl__FpVesta__neg scalar) in
        letb divisor := add_polyx divisor_mul_x divisor_mul_scalar in
        divisor) in
      letb '(divided_poly,remainder) := divide_polyx (f_clone q_i_sub_r_i) divisor in
      letb (multed_poly : t_Seq t_FpVesta) := mul_scalar_polyx divided_poly x2_powered in
      letb q_prime := add_polyx q_prime multed_poly in
      q_prime) in
    letb (commitment : t_FpPallas × t_FpPallas × 'bool) := commit_polyx crs (f_clone q_prime) blinding in
    solve_lift (prod_b (commitment,q_prime,blinding)) : both (t_FpPallas × t_FpPallas × 'bool × t_Seq t_FpVesta × t_FpVesta).
Fail Next Obligation.

Equations step_4_ (g_prime : both (t_Seq t_FpVesta)) (omega : both t_FpVesta) (n : both uint_size) : both (t_Seq t_FpVesta) :=
  step_4_ g_prime omega n  :=
    letb vanishing := compute_vanishing_polynomial omega n in
    letb '(h,remainder) := divide_polyx g_prime vanishing in
    solve_lift h : both (t_Seq t_FpVesta).
Fail Next Obligation.
