(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Equations test (_ : both 'unit) : both int8 :=
  test _  :=
    letb acc := ret_both (0 : int8) in
    letb acc := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (1 : int8)) (f_end := ret_both (10 : int8)))) acc (fun acc => fun i =>
      acc .+ i) in
    solve_lift (acc .+ (ret_both (1 : int8))) : both int8.
Fail Next Obligation.
