(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

(*Not implemented yet? todo(item)*)

Equations v_BLOCKSIZE : both uint_size :=
  v_BLOCKSIZE  :=
    solve_lift (ret_both (16 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations v_INVALID_KEY_EXPANSION_INDEX : both int8 :=
  v_INVALID_KEY_EXPANSION_INDEX  :=
    solve_lift (ret_both (1 : int8)) : both int8.
Fail Next Obligation.

Equations v_ITERATIONS : both uint_size :=
  v_ITERATIONS  :=
    solve_lift (ret_both (40 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations v_IVSIZE : both uint_size :=
  v_IVSIZE  :=
    solve_lift (ret_both (12 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations v_KEY_LENGTH : both uint_size :=
  v_KEY_LENGTH  :=
    solve_lift (ret_both (4 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations v_KEY_SCHEDULE_LENGTH : both uint_size :=
  v_KEY_SCHEDULE_LENGTH  :=
    solve_lift (ret_both (176 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations v_ROUNDS : both uint_size :=
  v_ROUNDS  :=
    solve_lift (ret_both (10 : uint_size)) : both uint_size.
Fail Next Obligation.

Notation "'t_AesNonce'" := (nseq int8 IVSIZE).
Definition AesNonce : both t_AesNonce -> both t_AesNonce :=
  id.

Notation "'t_Block'" := (nseq int8 BLOCKSIZE).
Definition Block : both t_Block -> both t_Block :=
  id.

Notation "'t_BlockResult'" := (t_Result t_Block int8).

Notation "'t_Bytes144'" := (nseq int8 144).
Definition Bytes144 : both t_Bytes144 -> both t_Bytes144 :=
  id.

Notation "'t_Bytes176'" := (nseq int8 KEY_SCHEDULE_LENGTH).
Definition Bytes176 : both t_Bytes176 -> both t_Bytes176 :=
  id.

Notation "'t_Key128'" := (nseq int8 BLOCKSIZE).
Definition Key128 : both t_Key128 -> both t_Key128 :=
  id.

Notation "'t_RCon'" := (nseq int8 15).
Definition RCon : both t_RCon -> both t_RCon :=
  id.

Notation "'t_RoundKey'" := (nseq int8 BLOCKSIZE).
Definition RoundKey : both t_RoundKey -> both t_RoundKey :=
  id.

Notation "'t_SBox'" := (nseq int8 256).
Definition SBox : both t_SBox -> both t_SBox :=
  id.

Notation "'t_Word'" := (nseq int8 KEY_LENGTH).
Definition Word : both t_Word -> both t_Word :=
  id.

Notation "'t_WordResult'" := (t_Result t_Word int8).

Notation "'t_ByteSeqResult'" := (t_Result (t_Seq t_U8) int8).

Equations add_round_key (state : both t_Block) (key : both t_RoundKey) : both t_Block :=
  add_round_key state key  :=
    letb out := state in
    letb out := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := v_BLOCKSIZE))) out (fun out => fun i =>
      update_at_usize out i ((out.a[i]) .^ (key.a[i]))) in
    solve_lift out : both t_Block.
Fail Next Obligation.

Equations rotate_word (w : both t_Word) : both t_Word :=
  rotate_word w  :=
    Word (array_from_list [solve_lift (w.a[(ret_both (1 : int32))]);
      solve_lift (w.a[(ret_both (2 : int32))]);
      solve_lift (w.a[(ret_both (3 : int32))]);
      solve_lift (w.a[(ret_both (0 : int32))])]) : both t_Word.
Fail Next Obligation.

Equations shift_row (i : both uint_size) (shift : both uint_size) (state : both t_Block) : both t_Block :=
  shift_row i shift state  :=
    letb out := state in
    letb out := update_at_usize out i (state.a[(i .+ ((ret_both (4 : uint_size)) .* (shift .% (ret_both (4 : uint_size)))))]) in
    letb out := update_at_usize out (i .+ (ret_both (4 : uint_size))) (state.a[(i .+ ((ret_both (4 : uint_size)) .* ((shift .+ (ret_both (1 : uint_size))) .% (ret_both (4 : uint_size)))))]) in
    letb out := update_at_usize out (i .+ (ret_both (8 : uint_size))) (state.a[(i .+ ((ret_both (4 : uint_size)) .* ((shift .+ (ret_both (2 : uint_size))) .% (ret_both (4 : uint_size)))))]) in
    letb out := update_at_usize out (i .+ (ret_both (12 : uint_size))) (state.a[(i .+ ((ret_both (4 : uint_size)) .* ((shift .+ (ret_both (3 : uint_size))) .% (ret_both (4 : uint_size)))))]) in
    solve_lift out : both t_Block.
Fail Next Obligation.

Equations shift_rows (state : both t_Block) : both t_Block :=
  shift_rows state  :=
    letb state := shift_row (ret_both (1 : uint_size)) (ret_both (1 : uint_size)) state in
    letb state := shift_row (ret_both (2 : uint_size)) (ret_both (2 : uint_size)) state in
    solve_lift (shift_row (ret_both (3 : uint_size)) (ret_both (3 : uint_size)) state) : both t_Block.
Fail Next Obligation.

Equations xor_block (block : both t_Block) (key_block : both t_Block) : both t_Block :=
  xor_block block key_block  :=
    letb out := block in
    letb out := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := v_BLOCKSIZE))) out (fun out => fun i =>
      update_at_usize out i ((out.a[i]) .^ (key_block.a[i]))) in
    solve_lift out : both t_Block.
Fail Next Obligation.

Equations v_RCON : both t_RCon :=
  v_RCON  :=
    RCon (array_from_list [U8 (solve_lift (ret_both (141 : int8)));
      U8 (solve_lift (ret_both (1 : int8)));
      U8 (solve_lift (ret_both (2 : int8)));
      U8 (solve_lift (ret_both (4 : int8)));
      U8 (solve_lift (ret_both (8 : int8)));
      U8 (solve_lift (ret_both (16 : int8)));
      U8 (solve_lift (ret_both (32 : int8)));
      U8 (solve_lift (ret_both (64 : int8)));
      U8 (solve_lift (ret_both (128 : int8)));
      U8 (solve_lift (ret_both (27 : int8)));
      U8 (solve_lift (ret_both (54 : int8)));
      U8 (solve_lift (ret_both (108 : int8)));
      U8 (solve_lift (ret_both (216 : int8)));
      U8 (solve_lift (ret_both (171 : int8)));
      U8 (solve_lift (ret_both (77 : int8)))]) : both t_RCon.
Fail Next Obligation.

Equations v_SBOX : both t_SBox :=
  v_SBOX  :=
    SBox (array_from_list [U8 (solve_lift (ret_both (99 : int8)));
      U8 (solve_lift (ret_both (124 : int8)));
      U8 (solve_lift (ret_both (119 : int8)));
      U8 (solve_lift (ret_both (123 : int8)));
      U8 (solve_lift (ret_both (242 : int8)));
      U8 (solve_lift (ret_both (107 : int8)));
      U8 (solve_lift (ret_both (111 : int8)));
      U8 (solve_lift (ret_both (197 : int8)));
      U8 (solve_lift (ret_both (48 : int8)));
      U8 (solve_lift (ret_both (1 : int8)));
      U8 (solve_lift (ret_both (103 : int8)));
      U8 (solve_lift (ret_both (43 : int8)));
      U8 (solve_lift (ret_both (254 : int8)));
      U8 (solve_lift (ret_both (215 : int8)));
      U8 (solve_lift (ret_both (171 : int8)));
      U8 (solve_lift (ret_both (118 : int8)));
      U8 (solve_lift (ret_both (202 : int8)));
      U8 (solve_lift (ret_both (130 : int8)));
      U8 (solve_lift (ret_both (201 : int8)));
      U8 (solve_lift (ret_both (125 : int8)));
      U8 (solve_lift (ret_both (250 : int8)));
      U8 (solve_lift (ret_both (89 : int8)));
      U8 (solve_lift (ret_both (71 : int8)));
      U8 (solve_lift (ret_both (240 : int8)));
      U8 (solve_lift (ret_both (173 : int8)));
      U8 (solve_lift (ret_both (212 : int8)));
      U8 (solve_lift (ret_both (162 : int8)));
      U8 (solve_lift (ret_both (175 : int8)));
      U8 (solve_lift (ret_both (156 : int8)));
      U8 (solve_lift (ret_both (164 : int8)));
      U8 (solve_lift (ret_both (114 : int8)));
      U8 (solve_lift (ret_both (192 : int8)));
      U8 (solve_lift (ret_both (183 : int8)));
      U8 (solve_lift (ret_both (253 : int8)));
      U8 (solve_lift (ret_both (147 : int8)));
      U8 (solve_lift (ret_both (38 : int8)));
      U8 (solve_lift (ret_both (54 : int8)));
      U8 (solve_lift (ret_both (63 : int8)));
      U8 (solve_lift (ret_both (247 : int8)));
      U8 (solve_lift (ret_both (204 : int8)));
      U8 (solve_lift (ret_both (52 : int8)));
      U8 (solve_lift (ret_both (165 : int8)));
      U8 (solve_lift (ret_both (229 : int8)));
      U8 (solve_lift (ret_both (241 : int8)));
      U8 (solve_lift (ret_both (113 : int8)));
      U8 (solve_lift (ret_both (216 : int8)));
      U8 (solve_lift (ret_both (49 : int8)));
      U8 (solve_lift (ret_both (21 : int8)));
      U8 (solve_lift (ret_both (4 : int8)));
      U8 (solve_lift (ret_both (199 : int8)));
      U8 (solve_lift (ret_both (35 : int8)));
      U8 (solve_lift (ret_both (195 : int8)));
      U8 (solve_lift (ret_both (24 : int8)));
      U8 (solve_lift (ret_both (150 : int8)));
      U8 (solve_lift (ret_both (5 : int8)));
      U8 (solve_lift (ret_both (154 : int8)));
      U8 (solve_lift (ret_both (7 : int8)));
      U8 (solve_lift (ret_both (18 : int8)));
      U8 (solve_lift (ret_both (128 : int8)));
      U8 (solve_lift (ret_both (226 : int8)));
      U8 (solve_lift (ret_both (235 : int8)));
      U8 (solve_lift (ret_both (39 : int8)));
      U8 (solve_lift (ret_both (178 : int8)));
      U8 (solve_lift (ret_both (117 : int8)));
      U8 (solve_lift (ret_both (9 : int8)));
      U8 (solve_lift (ret_both (131 : int8)));
      U8 (solve_lift (ret_both (44 : int8)));
      U8 (solve_lift (ret_both (26 : int8)));
      U8 (solve_lift (ret_both (27 : int8)));
      U8 (solve_lift (ret_both (110 : int8)));
      U8 (solve_lift (ret_both (90 : int8)));
      U8 (solve_lift (ret_both (160 : int8)));
      U8 (solve_lift (ret_both (82 : int8)));
      U8 (solve_lift (ret_both (59 : int8)));
      U8 (solve_lift (ret_both (214 : int8)));
      U8 (solve_lift (ret_both (179 : int8)));
      U8 (solve_lift (ret_both (41 : int8)));
      U8 (solve_lift (ret_both (227 : int8)));
      U8 (solve_lift (ret_both (47 : int8)));
      U8 (solve_lift (ret_both (132 : int8)));
      U8 (solve_lift (ret_both (83 : int8)));
      U8 (solve_lift (ret_both (209 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (237 : int8)));
      U8 (solve_lift (ret_both (32 : int8)));
      U8 (solve_lift (ret_both (252 : int8)));
      U8 (solve_lift (ret_both (177 : int8)));
      U8 (solve_lift (ret_both (91 : int8)));
      U8 (solve_lift (ret_both (106 : int8)));
      U8 (solve_lift (ret_both (203 : int8)));
      U8 (solve_lift (ret_both (190 : int8)));
      U8 (solve_lift (ret_both (57 : int8)));
      U8 (solve_lift (ret_both (74 : int8)));
      U8 (solve_lift (ret_both (76 : int8)));
      U8 (solve_lift (ret_both (88 : int8)));
      U8 (solve_lift (ret_both (207 : int8)));
      U8 (solve_lift (ret_both (208 : int8)));
      U8 (solve_lift (ret_both (239 : int8)));
      U8 (solve_lift (ret_both (170 : int8)));
      U8 (solve_lift (ret_both (251 : int8)));
      U8 (solve_lift (ret_both (67 : int8)));
      U8 (solve_lift (ret_both (77 : int8)));
      U8 (solve_lift (ret_both (51 : int8)));
      U8 (solve_lift (ret_both (133 : int8)));
      U8 (solve_lift (ret_both (69 : int8)));
      U8 (solve_lift (ret_both (249 : int8)));
      U8 (solve_lift (ret_both (2 : int8)));
      U8 (solve_lift (ret_both (127 : int8)));
      U8 (solve_lift (ret_both (80 : int8)));
      U8 (solve_lift (ret_both (60 : int8)));
      U8 (solve_lift (ret_both (159 : int8)));
      U8 (solve_lift (ret_both (168 : int8)));
      U8 (solve_lift (ret_both (81 : int8)));
      U8 (solve_lift (ret_both (163 : int8)));
      U8 (solve_lift (ret_both (64 : int8)));
      U8 (solve_lift (ret_both (143 : int8)));
      U8 (solve_lift (ret_both (146 : int8)));
      U8 (solve_lift (ret_both (157 : int8)));
      U8 (solve_lift (ret_both (56 : int8)));
      U8 (solve_lift (ret_both (245 : int8)));
      U8 (solve_lift (ret_both (188 : int8)));
      U8 (solve_lift (ret_both (182 : int8)));
      U8 (solve_lift (ret_both (218 : int8)));
      U8 (solve_lift (ret_both (33 : int8)));
      U8 (solve_lift (ret_both (16 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (243 : int8)));
      U8 (solve_lift (ret_both (210 : int8)));
      U8 (solve_lift (ret_both (205 : int8)));
      U8 (solve_lift (ret_both (12 : int8)));
      U8 (solve_lift (ret_both (19 : int8)));
      U8 (solve_lift (ret_both (236 : int8)));
      U8 (solve_lift (ret_both (95 : int8)));
      U8 (solve_lift (ret_both (151 : int8)));
      U8 (solve_lift (ret_both (68 : int8)));
      U8 (solve_lift (ret_both (23 : int8)));
      U8 (solve_lift (ret_both (196 : int8)));
      U8 (solve_lift (ret_both (167 : int8)));
      U8 (solve_lift (ret_both (126 : int8)));
      U8 (solve_lift (ret_both (61 : int8)));
      U8 (solve_lift (ret_both (100 : int8)));
      U8 (solve_lift (ret_both (93 : int8)));
      U8 (solve_lift (ret_both (25 : int8)));
      U8 (solve_lift (ret_both (115 : int8)));
      U8 (solve_lift (ret_both (96 : int8)));
      U8 (solve_lift (ret_both (129 : int8)));
      U8 (solve_lift (ret_both (79 : int8)));
      U8 (solve_lift (ret_both (220 : int8)));
      U8 (solve_lift (ret_both (34 : int8)));
      U8 (solve_lift (ret_both (42 : int8)));
      U8 (solve_lift (ret_both (144 : int8)));
      U8 (solve_lift (ret_both (136 : int8)));
      U8 (solve_lift (ret_both (70 : int8)));
      U8 (solve_lift (ret_both (238 : int8)));
      U8 (solve_lift (ret_both (184 : int8)));
      U8 (solve_lift (ret_both (20 : int8)));
      U8 (solve_lift (ret_both (222 : int8)));
      U8 (solve_lift (ret_both (94 : int8)));
      U8 (solve_lift (ret_both (11 : int8)));
      U8 (solve_lift (ret_both (219 : int8)));
      U8 (solve_lift (ret_both (224 : int8)));
      U8 (solve_lift (ret_both (50 : int8)));
      U8 (solve_lift (ret_both (58 : int8)));
      U8 (solve_lift (ret_both (10 : int8)));
      U8 (solve_lift (ret_both (73 : int8)));
      U8 (solve_lift (ret_both (6 : int8)));
      U8 (solve_lift (ret_both (36 : int8)));
      U8 (solve_lift (ret_both (92 : int8)));
      U8 (solve_lift (ret_both (194 : int8)));
      U8 (solve_lift (ret_both (211 : int8)));
      U8 (solve_lift (ret_both (172 : int8)));
      U8 (solve_lift (ret_both (98 : int8)));
      U8 (solve_lift (ret_both (145 : int8)));
      U8 (solve_lift (ret_both (149 : int8)));
      U8 (solve_lift (ret_both (228 : int8)));
      U8 (solve_lift (ret_both (121 : int8)));
      U8 (solve_lift (ret_both (231 : int8)));
      U8 (solve_lift (ret_both (200 : int8)));
      U8 (solve_lift (ret_both (55 : int8)));
      U8 (solve_lift (ret_both (109 : int8)));
      U8 (solve_lift (ret_both (141 : int8)));
      U8 (solve_lift (ret_both (213 : int8)));
      U8 (solve_lift (ret_both (78 : int8)));
      U8 (solve_lift (ret_both (169 : int8)));
      U8 (solve_lift (ret_both (108 : int8)));
      U8 (solve_lift (ret_both (86 : int8)));
      U8 (solve_lift (ret_both (244 : int8)));
      U8 (solve_lift (ret_both (234 : int8)));
      U8 (solve_lift (ret_both (101 : int8)));
      U8 (solve_lift (ret_both (122 : int8)));
      U8 (solve_lift (ret_both (174 : int8)));
      U8 (solve_lift (ret_both (8 : int8)));
      U8 (solve_lift (ret_both (186 : int8)));
      U8 (solve_lift (ret_both (120 : int8)));
      U8 (solve_lift (ret_both (37 : int8)));
      U8 (solve_lift (ret_both (46 : int8)));
      U8 (solve_lift (ret_both (28 : int8)));
      U8 (solve_lift (ret_both (166 : int8)));
      U8 (solve_lift (ret_both (180 : int8)));
      U8 (solve_lift (ret_both (198 : int8)));
      U8 (solve_lift (ret_both (232 : int8)));
      U8 (solve_lift (ret_both (221 : int8)));
      U8 (solve_lift (ret_both (116 : int8)));
      U8 (solve_lift (ret_both (31 : int8)));
      U8 (solve_lift (ret_both (75 : int8)));
      U8 (solve_lift (ret_both (189 : int8)));
      U8 (solve_lift (ret_both (139 : int8)));
      U8 (solve_lift (ret_both (138 : int8)));
      U8 (solve_lift (ret_both (112 : int8)));
      U8 (solve_lift (ret_both (62 : int8)));
      U8 (solve_lift (ret_both (181 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (72 : int8)));
      U8 (solve_lift (ret_both (3 : int8)));
      U8 (solve_lift (ret_both (246 : int8)));
      U8 (solve_lift (ret_both (14 : int8)));
      U8 (solve_lift (ret_both (97 : int8)));
      U8 (solve_lift (ret_both (53 : int8)));
      U8 (solve_lift (ret_both (87 : int8)));
      U8 (solve_lift (ret_both (185 : int8)));
      U8 (solve_lift (ret_both (134 : int8)));
      U8 (solve_lift (ret_both (193 : int8)));
      U8 (solve_lift (ret_both (29 : int8)));
      U8 (solve_lift (ret_both (158 : int8)));
      U8 (solve_lift (ret_both (225 : int8)));
      U8 (solve_lift (ret_both (248 : int8)));
      U8 (solve_lift (ret_both (152 : int8)));
      U8 (solve_lift (ret_both (17 : int8)));
      U8 (solve_lift (ret_both (105 : int8)));
      U8 (solve_lift (ret_both (217 : int8)));
      U8 (solve_lift (ret_both (142 : int8)));
      U8 (solve_lift (ret_both (148 : int8)));
      U8 (solve_lift (ret_both (155 : int8)));
      U8 (solve_lift (ret_both (30 : int8)));
      U8 (solve_lift (ret_both (135 : int8)));
      U8 (solve_lift (ret_both (233 : int8)));
      U8 (solve_lift (ret_both (206 : int8)));
      U8 (solve_lift (ret_both (85 : int8)));
      U8 (solve_lift (ret_both (40 : int8)));
      U8 (solve_lift (ret_both (223 : int8)));
      U8 (solve_lift (ret_both (140 : int8)));
      U8 (solve_lift (ret_both (161 : int8)));
      U8 (solve_lift (ret_both (137 : int8)));
      U8 (solve_lift (ret_both (13 : int8)));
      U8 (solve_lift (ret_both (191 : int8)));
      U8 (solve_lift (ret_both (230 : int8)));
      U8 (solve_lift (ret_both (66 : int8)));
      U8 (solve_lift (ret_both (104 : int8)));
      U8 (solve_lift (ret_both (65 : int8)));
      U8 (solve_lift (ret_both (153 : int8)));
      U8 (solve_lift (ret_both (45 : int8)));
      U8 (solve_lift (ret_both (15 : int8)));
      U8 (solve_lift (ret_both (176 : int8)));
      U8 (solve_lift (ret_both (84 : int8)));
      U8 (solve_lift (ret_both (187 : int8)));
      U8 (solve_lift (ret_both (22 : int8)))]) : both t_SBox.
Fail Next Obligation.

Equations sub_bytes (state : both t_Block) : both t_Block :=
  sub_bytes state  :=
    letb st := state in
    letb st := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := v_BLOCKSIZE))) st (fun st => fun i =>
      update_at_usize st i (v_SBOX.a[(impl__U8__declassify (state.a[i]))])) in
    solve_lift st : both t_Block.
Fail Next Obligation.

Equations aes_enc_last (state : both t_Block) (round_key : both t_RoundKey) : both t_Block :=
  aes_enc_last state round_key  :=
    letb state := sub_bytes state in
    letb state := shift_rows state in
    solve_lift (add_round_key state round_key) : both t_Block.
Fail Next Obligation.

Equations xtime (x : both t_U8) : both t_U8 :=
  xtime x  :=
    letb x1 := x shift_left (ret_both (1 : uint_size)) in
    letb x7 := x shift_right (ret_both (7 : uint_size)) in
    letb x71 := x7 .& (U8 (ret_both (1 : int8))) in
    letb x711b := x71 .* (U8 (ret_both (27 : int8))) in
    solve_lift (x1 .^ x711b) : both t_U8.
Fail Next Obligation.

Equations mix_column (c : both uint_size) (state : both t_Block) : both t_Block :=
  mix_column c state  :=
    letb i0 := (ret_both (4 : uint_size)) .* c in
    letb s0 := state.a[i0] in
    letb s1 := state.a[(i0 .+ (ret_both (1 : uint_size)))] in
    letb s2 := state.a[(i0 .+ (ret_both (2 : uint_size)))] in
    letb s3 := state.a[(i0 .+ (ret_both (3 : uint_size)))] in
    letb st := state in
    letb tmp := ((s0 .^ s1) .^ s2) .^ s3 in
    letb st := update_at_usize st i0 ((s0 .^ tmp) .^ (xtime (s0 .^ s1))) in
    letb st := update_at_usize st (i0 .+ (ret_both (1 : uint_size))) ((s1 .^ tmp) .^ (xtime (s1 .^ s2))) in
    letb st := update_at_usize st (i0 .+ (ret_both (2 : uint_size))) ((s2 .^ tmp) .^ (xtime (s2 .^ s3))) in
    letb st := update_at_usize st (i0 .+ (ret_both (3 : uint_size))) ((s3 .^ tmp) .^ (xtime (s3 .^ s0))) in
    solve_lift st : both t_Block.
Fail Next Obligation.

Equations mix_columns (state : both t_Block) : both t_Block :=
  mix_columns state  :=
    letb state := mix_column (ret_both (0 : uint_size)) state in
    letb state := mix_column (ret_both (1 : uint_size)) state in
    letb state := mix_column (ret_both (2 : uint_size)) state in
    solve_lift (mix_column (ret_both (3 : uint_size)) state) : both t_Block.
Fail Next Obligation.

Equations aes_enc (state : both t_Block) (round_key : both t_RoundKey) : both t_Block :=
  aes_enc state round_key  :=
    letb state := sub_bytes state in
    letb state := shift_rows state in
    letb state := mix_columns state in
    solve_lift (add_round_key state round_key) : both t_Block.
Fail Next Obligation.

Equations rounds_aes (state : both t_Block) (key : both (t_Seq t_U8)) : both t_Block :=
  rounds_aes state key  :=
    letb out := state in
    letb out := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__num_chunks key v_BLOCKSIZE))) out (fun out => fun i =>
      letb '(_,key_block) := impl_41__get_chunk key v_BLOCKSIZE i in
      letb out := aes_enc out (impl__RoundKey__from_seq key_block) in
      out) in
    solve_lift out : both t_Block.
Fail Next Obligation.

Equations block_cipher_aes (input : both t_Block) (key : both (t_Seq t_U8)) (nr : both uint_size) : both t_Block :=
  block_cipher_aes input key nr  :=
    letb k0 := impl__RoundKey__from_slice_range key (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := ret_both (16 : uint_size))) in
    letb k := impl_41__from_slice_range key (Build_t_Range (f_start := ret_both (16 : uint_size)) (f_end := nr .* (ret_both (16 : uint_size)))) in
    letb kn := impl__RoundKey__from_slice key (nr .* (ret_both (16 : uint_size))) (ret_both (16 : uint_size)) in
    letb state := add_round_key input k0 in
    letb state := rounds_aes state k in
    solve_lift (aes_enc_last state kn) : both t_Block.
Fail Next Obligation.

Equations slice_word (w : both t_Word) : both t_Word :=
  slice_word w  :=
    Word (array_from_list [solve_lift (v_SBOX.a[(declassify_usize_from_U8 (w.a[(ret_both (0 : int32))]))]);
      solve_lift (v_SBOX.a[(declassify_usize_from_U8 (w.a[(ret_both (1 : int32))]))]);
      solve_lift (v_SBOX.a[(declassify_usize_from_U8 (w.a[(ret_both (2 : int32))]))]);
      solve_lift (v_SBOX.a[(declassify_usize_from_U8 (w.a[(ret_both (3 : int32))]))])]) : both t_Word.
Fail Next Obligation.

Equations aes_keygen_assist (w : both t_Word) (rcon : both t_U8) : both t_Word :=
  aes_keygen_assist w rcon  :=
    letb k := rotate_word w in
    letb k := slice_word k in
    letb k := update_at k (ret_both (0 : int32)) ((k.a[(ret_both (0 : int32))]) .^ rcon) in
    solve_lift k : both t_Word.
Fail Next Obligation.

Equations key_expansion_word (w0 : both t_Word) (w1 : both t_Word) (i : both uint_size) (nk : both uint_size) (nr : both uint_size) : both (t_Result t_Word int8) :=
  key_expansion_word w0 w1 i nk nr  :=
    letb k := w1 in
    letb result := v_Err v_INVALID_KEY_EXPANSION_INDEX in
    letb '(k,result) := ifb i <.? ((ret_both (4 : uint_size)) .* (nr .+ (ret_both (1 : uint_size))))
    then letb k := ifb (i .% nk) =.? (ret_both (0 : uint_size))
    then letb k := aes_keygen_assist k (v_RCON.a[(i ./ nk)]) in
    k
    else ifb andb (nk >.? (ret_both (6 : uint_size))) ((i .% nk) =.? (ret_both (4 : uint_size)))
    then letb k := slice_word k in
    k
    else k in
    letb k := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (4 : int32)))) k (fun k => fun i =>
      update_at k i ((k.a[i]) .^ (w0.a[i]))) in
    letb result := v_Ok k in
    prod_b (k,result)
    else prod_b (k,result) in
    solve_lift result : both (t_Result t_Word int8).
Fail Next Obligation.

Equations key_expansion_aes (key : both (t_Seq t_U8)) (nk : both uint_size) (nr : both uint_size) (key_schedule_length : both uint_size) (key_length : both uint_size) (iterations : both uint_size) : both (t_Result (t_Seq t_U8) int8) :=
  key_expansion_aes key nk nr key_schedule_length key_length iterations  :=
    letb key_ex := impl_41__new key_schedule_length in
    letb key_ex := f_update_start key_ex key in
    letb word_size := key_length in
    letb key_ex := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := iterations))) key_ex (fun key_ex => fun j =>
      letb i := j .+ word_size in
      letm[choice_typeMonad.result_bind_code int8] word := impl__map_err (key_expansion_word (impl__Word__from_slice key_ex ((ret_both (4 : uint_size)) .* (i .- word_size)) (ret_both (4 : uint_size))) (impl__Word__from_slice key_ex (((ret_both (4 : uint_size)) .* i) .- (ret_both (4 : uint_size))) (ret_both (4 : uint_size))) i nk nr) f_from in
      Result_Ok (letb key_ex := f_update key_ex ((ret_both (4 : uint_size)) .* i) word in
      key_ex)) in
    solve_lift (v_Ok key_ex) : both (t_Result (t_Seq t_U8) int8).
Fail Next Obligation.

Equations aes_encrypt_block (k : both (t_Seq t_U8)) (input : both t_Block) (nk : both uint_size) (nr : both uint_size) (key_schedule_length : both uint_size) (key_length : both uint_size) (iterations : both uint_size) : both (t_Result t_Block int8) :=
  aes_encrypt_block k input nk nr key_schedule_length key_length iterations  :=
    solve_lift (run (letm[choice_typeMonad.result_bind_code int8] key_ex := impl__map_err (key_expansion_aes k nk nr key_schedule_length key_length iterations) f_from in
    Result_Ok (v_Ok (block_cipher_aes input key_ex nr)))) : both (t_Result t_Block int8).
Fail Next Obligation.

Equations aes128_encrypt_block (k : both t_Key128) (input : both t_Block) : both t_Block :=
  aes128_encrypt_block k input  :=
    solve_lift (impl__unwrap (aes_encrypt_block (impl_52__from_seq k) input v_KEY_LENGTH v_ROUNDS v_KEY_SCHEDULE_LENGTH v_KEY_LENGTH v_ITERATIONS)) : both t_Block.
Fail Next Obligation.

Equations aes_ctr_key_block (k : both (t_Seq t_U8)) (n : both t_AesNonce) (c : both t_U32) (nk : both uint_size) (nr : both uint_size) (key_schedule_length : both uint_size) (key_length : both uint_size) (iterations : both uint_size) : both (t_Result t_Block int8) :=
  aes_ctr_key_block k n c nk nr key_schedule_length key_length iterations  :=
    letb input := impl__Block__new (ret_both (tt : 'unit)) in
    letb input := f_update input (ret_both (0 : uint_size)) n in
    letb input := f_update input (ret_both (12 : uint_size)) (v_U32_to_be_bytes c) in
    solve_lift (aes_encrypt_block k input nk nr key_schedule_length key_length iterations) : both (t_Result t_Block int8).
Fail Next Obligation.

Equations aes_counter_mode (key : both (t_Seq t_U8)) (nonce : both t_AesNonce) (counter : both t_U32) (msg : both (t_Seq t_U8)) (nk : both uint_size) (nr : both uint_size) (key_schedule_length : both uint_size) (key_length : both uint_size) (iterations : both uint_size) : both (t_Result (t_Seq t_U8) int8) :=
  aes_counter_mode key nonce counter msg nk nr key_schedule_length key_length iterations  :=
    solve_lift (run (letb ctr := counter in
    letb blocks_out := impl_41__new (impl_41__len msg) in
    letb n_blocks := impl_41__num_exact_chunks msg v_BLOCKSIZE in
    letb '(blocks_out,ctr) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := n_blocks))) (prod_b (blocks_out,ctr)) (fun '(blocks_out,ctr) => fun i =>
      letb msg_block := impl_41__get_exact_chunk msg v_BLOCKSIZE i in
      letm[choice_typeMonad.result_bind_code int8] key_block := impl__map_err (aes_ctr_key_block key nonce ctr nk nr key_schedule_length key_length iterations) f_from in
      Result_Ok (letb blocks_out := impl_41__set_chunk blocks_out v_BLOCKSIZE i (xor_block (impl__Block__from_seq msg_block) key_block) in
      letb ctr := ctr .+ (U32 (ret_both (1 : int32))) in
      prod_b (blocks_out,ctr))) in
    letb last_block := impl_41__get_remainder_chunk msg v_BLOCKSIZE in
    letb last_block_len := impl_41__len last_block in
    letm[choice_typeMonad.result_bind_code int8] blocks_out := ifb last_block_len <> (ret_both (0 : uint_size))
    then letb last_block := f_update_start (impl__Block__new (ret_both (tt : 'unit))) last_block in
    letm[choice_typeMonad.result_bind_code int8] key_block := impl__map_err (aes_ctr_key_block key nonce ctr nk nr key_schedule_length key_length iterations) f_from in
    Result_Ok (letb blocks_out := impl_41__set_chunk blocks_out v_BLOCKSIZE n_blocks (impl__Block__slice_range (xor_block last_block key_block) (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := last_block_len))) in
    blocks_out)
    else Result_Ok blocks_out in
    Result_Ok (v_Ok blocks_out))) : both (t_Result (t_Seq t_U8) int8).
Fail Next Obligation.

Equations aes128_decrypt (key : both t_Key128) (nonce : both t_AesNonce) (counter : both t_U32) (ctxt : both (t_Seq t_U8)) : both (t_Seq t_U8) :=
  aes128_decrypt key nonce counter ctxt  :=
    solve_lift (impl__unwrap (aes_counter_mode (impl_52__from_seq key) nonce counter ctxt v_KEY_LENGTH v_ROUNDS v_KEY_SCHEDULE_LENGTH v_KEY_LENGTH v_ITERATIONS)) : both (t_Seq t_U8).
Fail Next Obligation.

Equations aes128_encrypt (key : both t_Key128) (nonce : both t_AesNonce) (counter : both t_U32) (msg : both (t_Seq t_U8)) : both (t_Seq t_U8) :=
  aes128_encrypt key nonce counter msg  :=
    solve_lift (impl__unwrap (aes_counter_mode (impl_52__from_seq key) nonce counter msg v_KEY_LENGTH v_ROUNDS v_KEY_SCHEDULE_LENGTH v_KEY_LENGTH v_ITERATIONS)) : both (t_Seq t_U8).
Fail Next Obligation.
