(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

(*Not implemented yet? todo(item)*)

Notation "'t_State'" := (nseq int32 12).
Definition State : both t_State -> both t_State :=
  id.

Notation "'t_Block'" := (nseq int8 16).
Definition Block : both t_Block -> both t_Block :=
  id.

Notation "'t_Digest'" := (nseq int8 32).
Definition Digest : both t_Digest -> both t_Digest :=
  id.

Notation "'t_Key'" := (nseq int8 32).
Definition Key : both t_Key -> both t_Key :=
  id.

Notation "'t_Nonce'" := (nseq int8 16).
Definition Nonce : both t_Nonce -> both t_Nonce :=
  id.

Notation "'t_Tag'" := (nseq int8 16).
Definition Tag : both t_Tag -> both t_Tag :=
  id.

Equations key_to_u32s (key : both t_Key) : both (t_Seq t_U32) :=
  key_to_u32s key  :=
    letb uints := impl_41__new (ret_both (8 : uint_size)) in
    letb uints := update_at uints (ret_both (0 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range key (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := ret_both (4 : uint_size))))) in
    letb uints := update_at uints (ret_both (1 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range key (Build_t_Range (f_start := ret_both (4 : uint_size)) (f_end := ret_both (8 : uint_size))))) in
    letb uints := update_at uints (ret_both (2 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range key (Build_t_Range (f_start := ret_both (8 : uint_size)) (f_end := ret_both (12 : uint_size))))) in
    letb uints := update_at uints (ret_both (3 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range key (Build_t_Range (f_start := ret_both (12 : uint_size)) (f_end := ret_both (16 : uint_size))))) in
    letb uints := update_at uints (ret_both (4 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range key (Build_t_Range (f_start := ret_both (16 : uint_size)) (f_end := ret_both (20 : uint_size))))) in
    letb uints := update_at uints (ret_both (5 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range key (Build_t_Range (f_start := ret_both (20 : uint_size)) (f_end := ret_both (24 : uint_size))))) in
    letb uints := update_at uints (ret_both (6 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range key (Build_t_Range (f_start := ret_both (24 : uint_size)) (f_end := ret_both (28 : uint_size))))) in
    letb uints := update_at uints (ret_both (7 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range key (Build_t_Range (f_start := ret_both (28 : uint_size)) (f_end := ret_both (32 : uint_size))))) in
    solve_lift uints : both (t_Seq t_U32).
Fail Next Obligation.

Equations nonce_to_u32s (nonce : both t_Nonce) : both (t_Seq t_U32) :=
  nonce_to_u32s nonce  :=
    letb uints := impl_41__new (ret_both (4 : uint_size)) in
    letb uints := update_at uints (ret_both (0 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range nonce (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := ret_both (4 : uint_size))))) in
    letb uints := update_at uints (ret_both (1 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range nonce (Build_t_Range (f_start := ret_both (4 : uint_size)) (f_end := ret_both (8 : uint_size))))) in
    letb uints := update_at uints (ret_both (2 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range nonce (Build_t_Range (f_start := ret_both (8 : uint_size)) (f_end := ret_both (12 : uint_size))))) in
    letb uints := update_at uints (ret_both (3 : int32)) (v_U32_from_le_bytes (impl__U32Word__from_slice_range nonce (Build_t_Range (f_start := ret_both (12 : uint_size)) (f_end := ret_both (16 : uint_size))))) in
    solve_lift uints : both (t_Seq t_U32).
Fail Next Obligation.

Equations swap (s : both t_State) (i : both uint_size) (j : both uint_size) : both t_State :=
  swap s i j  :=
    letb tmp := s.a[i] in
    letb s := update_at_usize s i (s.a[j]) in
    letb s := update_at_usize s j tmp in
    solve_lift s : both t_State.
Fail Next Obligation.

Equations gimli_round (s : both t_State) (r : both int32) : both t_State :=
  gimli_round s r  :=
    letb s := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := ret_both (4 : uint_size)))) s (fun s => fun col =>
      letb x := impl__U32__rotate_left (s.a[col]) (ret_both (24 : uint_size)) in
      letb y := impl__U32__rotate_left (s.a[(col .+ (ret_both (4 : uint_size)))]) (ret_both (9 : uint_size)) in
      letb z := s.a[(col .+ (ret_both (8 : uint_size)))] in
      letb s := update_at_usize s (col .+ (ret_both (8 : uint_size))) ((x .^ (z shift_left (ret_both (1 : uint_size)))) .^ ((y .& z) shift_left (ret_both (2 : uint_size)))) in
      letb s := update_at_usize s (col .+ (ret_both (4 : uint_size))) ((y .^ x) .^ ((x .| z) shift_left (ret_both (1 : uint_size)))) in
      letb s := update_at_usize s col ((z .^ y) .^ ((x .& y) shift_left (ret_both (3 : uint_size)))) in
      s) in
    letb s := ifb (r .& (ret_both (3 : int32))) =.? (ret_both (0 : int32))
    then letb s := swap s (ret_both (0 : uint_size)) (ret_both (1 : uint_size)) in
    letb s := swap s (ret_both (2 : uint_size)) (ret_both (3 : uint_size)) in
    s
    else s in
    letb s := ifb (r .& (ret_both (3 : int32))) =.? (ret_both (2 : int32))
    then letb s := swap s (ret_both (0 : uint_size)) (ret_both (2 : uint_size)) in
    letb s := swap s (ret_both (1 : uint_size)) (ret_both (3 : uint_size)) in
    s
    else s in
    letb s := ifb (r .& (ret_both (3 : int32))) =.? (ret_both (0 : int32))
    then update_at s (ret_both (0 : int32)) ((s.a[(ret_both (0 : int32))]) .^ ((U32 (ret_both (2654435584 : int32))) .| (U32 r)))
    else s in
    solve_lift s : both t_State.
Fail Next Obligation.

Equations gimli (s : both t_State) : both t_State :=
  gimli s  :=
    letb s := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (24 : int32)))) s (fun s => fun rnd =>
      letb rnd := cast_int (WS2 := _) ((ret_both (24 : int32)) .- rnd) in
      letb s := gimli_round s rnd in
      s) in
    solve_lift s : both t_State.
Fail Next Obligation.

Equations absorb_block (input_block : both t_Block) (s : both t_State) : both t_State :=
  absorb_block input_block s  :=
    letb input_bytes := impl__Block__to_le_U32s input_block in
    letb s := update_at s (ret_both (0 : int32)) ((s.a[(ret_both (0 : int32))]) .^ (input_bytes.a[(ret_both (0 : int32))])) in
    letb s := update_at s (ret_both (1 : int32)) ((s.a[(ret_both (1 : int32))]) .^ (input_bytes.a[(ret_both (1 : int32))])) in
    letb s := update_at s (ret_both (2 : int32)) ((s.a[(ret_both (2 : int32))]) .^ (input_bytes.a[(ret_both (2 : int32))])) in
    letb s := update_at s (ret_both (3 : int32)) ((s.a[(ret_both (3 : int32))]) .^ (input_bytes.a[(ret_both (3 : int32))])) in
    solve_lift (gimli s) : both t_State.
Fail Next Obligation.

Equations squeeze_block (s : both t_State) : both t_Block :=
  squeeze_block s  :=
    letb block := impl__Block__new (ret_both (tt : 'unit)) in
    letb block := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (4 : int32)))) block (fun block => fun i =>
      letb (s_i : t_U32) := s.a[i] in
      letb s_i_bytes := f_to_le_bytes s_i in
      letb block := update_at block ((ret_both (4 : int32)) .* i) (s_i_bytes.a[(ret_both (0 : int32))]) in
      letb block := update_at block (((ret_both (4 : int32)) .* i) .+ (ret_both (1 : int32))) (s_i_bytes.a[(ret_both (1 : int32))]) in
      letb block := update_at block (((ret_both (4 : int32)) .* i) .+ (ret_both (2 : int32))) (s_i_bytes.a[(ret_both (2 : int32))]) in
      letb block := update_at block (((ret_both (4 : int32)) .* i) .+ (ret_both (3 : int32))) (s_i_bytes.a[(ret_both (3 : int32))]) in
      block) in
    solve_lift block : both t_Block.
Fail Next Obligation.

Equations gimli_hash_state (input : both (t_Seq t_U8)) (s : both t_State) : both t_State :=
  gimli_hash_state input s  :=
    letb rate := impl__Block__length (ret_both (tt : 'unit)) in
    letb chunks := impl_41__num_exact_chunks input rate in
    letb s := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := chunks))) s (fun s => fun i =>
      letb input_block := impl_41__get_exact_chunk input rate i in
      letb full_block := impl__Block__from_seq input_block in
      letb s := absorb_block full_block s in
      s) in
    letb input_block := impl_41__get_remainder_chunk input rate in
    letb input_block_padded := impl__Block__new (ret_both (tt : 'unit)) in
    letb input_block_padded := f_update_start input_block_padded input_block in
    letb input_block_padded := update_at_usize input_block_padded (impl_41__len input_block) (U8 (ret_both (1 : int8))) in
    letb s := update_at s (ret_both (11 : int32)) ((s.a[(ret_both (11 : int32))]) .^ (U32 (ret_both (16777216 : int32)))) in
    letb s := absorb_block input_block_padded s in
    solve_lift s : both t_State.
Fail Next Obligation.

Equations gimli_hash (input_bytes : both (t_Seq t_U8)) : both t_Digest :=
  gimli_hash input_bytes  :=
    letb s := impl__State__new (ret_both (tt : 'unit)) in
    letb s := gimli_hash_state input_bytes s in
    letb output := impl__Digest__new (ret_both (tt : 'unit)) in
    letb output := f_update_start output (squeeze_block s) in
    letb s := gimli s in
    solve_lift (f_update output (impl__Block__length (ret_both (tt : 'unit))) (squeeze_block s)) : both t_Digest.
Fail Next Obligation.

Equations process_ad (ad : both (t_Seq t_U8)) (s : both t_State) : both t_State :=
  process_ad ad s  :=
    solve_lift (gimli_hash_state ad s) : both t_State.
Fail Next Obligation.

Equations process_ct (ciphertext : both (t_Seq t_U8)) (s : both t_State) : both (t_State × t_Seq t_U8) :=
  process_ct ciphertext s  :=
    letb message := impl_41__new (impl_41__len ciphertext) in
    letb rate := impl__Block__length (ret_both (tt : 'unit)) in
    letb num_chunks := impl_41__num_exact_chunks ciphertext rate in
    letb '(message,s) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := num_chunks))) (prod_b (message,s)) (fun '(message,s) => fun i =>
      letb key_block := squeeze_block s in
      letb ct_block := impl_41__get_exact_chunk ciphertext rate i in
      letb ct_block := impl__Block__from_seq ct_block in
      letb msg_block := ct_block .^ key_block in
      letb message := impl_41__set_exact_chunk message rate i (ct_block .^ key_block) in
      letb s := absorb_block msg_block s in
      prod_b (message,s)) in
    letb key_block := squeeze_block s in
    letb ct_final := impl_41__get_remainder_chunk ciphertext rate in
    letb block_len := impl_41__len ct_final in
    letb ct_block_padded := impl__Block__new (ret_both (tt : 'unit)) in
    letb ct_block_padded := f_update_start ct_block_padded ct_final in
    letb msg_block := ct_block_padded .^ key_block in
    letb message := impl_41__set_chunk message rate num_chunks (impl__Block__slice_range msg_block (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := block_len))) in
    letb msg_block := impl__Block__from_slice_range msg_block (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := block_len)) in
    letb msg_block := update_at_usize msg_block block_len ((msg_block.a[block_len]) .^ (U8 (ret_both (1 : int8)))) in
    letb s := update_at s (ret_both (11 : int32)) ((s.a[(ret_both (11 : int32))]) .^ (U32 (ret_both (16777216 : int32)))) in
    letb s := absorb_block msg_block s in
    solve_lift (prod_b (s,message)) : both (t_State × t_Seq t_U8).
Fail Next Obligation.

Equations gimli_aead_decrypt (ciphertext : both (t_Seq t_U8)) (ad : both (t_Seq t_U8)) (tag : both t_Tag) (nonce : both t_Nonce) (key : both t_Key) : both (t_Seq t_U8) :=
  gimli_aead_decrypt ciphertext ad tag nonce key  :=
    letb s := impl__State__from_seq (impl_41__concat (nonce_to_u32s nonce) (key_to_u32s key)) in
    letb s := gimli s in
    letb s := process_ad ad s in
    letb '(s,message) := process_ct ciphertext s in
    letb my_tag := squeeze_block s in
    letb my_tag := impl__Tag__from_seq my_tag in
    letb out := impl_41__new (ret_both (0 : uint_size)) in
    letb out := ifb f_equal my_tag tag
    then letb out := message in
    out
    else out in
    solve_lift out : both (t_Seq t_U8).
Fail Next Obligation.

Equations process_msg (message : both (t_Seq t_U8)) (s : both t_State) : both (t_State × t_Seq t_U8) :=
  process_msg message s  :=
    letb ciphertext := impl_41__new (impl_41__len message) in
    letb rate := impl__Block__length (ret_both (tt : 'unit)) in
    letb num_chunks := impl_41__num_exact_chunks message rate in
    letb '(ciphertext,s) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := num_chunks))) (prod_b (ciphertext,s)) (fun '(ciphertext,s) => fun i =>
      letb key_block := squeeze_block s in
      letb msg_block := impl_41__get_exact_chunk message rate i in
      letb msg_block := impl__Block__from_seq msg_block in
      letb ciphertext := impl_41__set_exact_chunk ciphertext rate i (msg_block .^ key_block) in
      letb s := absorb_block msg_block s in
      prod_b (ciphertext,s)) in
    letb key_block := squeeze_block s in
    letb last_block := impl_41__get_remainder_chunk message rate in
    letb block_len := impl_41__len last_block in
    letb msg_block_padded := impl__Block__new (ret_both (tt : 'unit)) in
    letb msg_block_padded := f_update_start msg_block_padded last_block in
    letb ciphertext := impl_41__set_chunk ciphertext rate num_chunks (impl__Block__slice_range (msg_block_padded .^ key_block) (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := block_len))) in
    letb msg_block_padded := update_at_usize msg_block_padded block_len ((msg_block_padded.a[block_len]) .^ (U8 (ret_both (1 : int8)))) in
    letb s := update_at s (ret_both (11 : int32)) ((s.a[(ret_both (11 : int32))]) .^ (U32 (ret_both (16777216 : int32)))) in
    letb s := absorb_block msg_block_padded s in
    solve_lift (prod_b (s,ciphertext)) : both (t_State × t_Seq t_U8).
Fail Next Obligation.

Equations gimli_aead_encrypt (message : both (t_Seq t_U8)) (ad : both (t_Seq t_U8)) (nonce : both t_Nonce) (key : both t_Key) : both (t_Seq t_U8 × t_Tag) :=
  gimli_aead_encrypt message ad nonce key  :=
    letb s := impl__State__from_seq (impl_41__concat (nonce_to_u32s nonce) (key_to_u32s key)) in
    letb s := gimli s in
    letb s := process_ad ad s in
    letb '(s,ciphertext) := process_msg message s in
    letb tag := squeeze_block s in
    letb tag := impl__Tag__from_seq tag in
    solve_lift (prod_b (ciphertext,tag)) : both (t_Seq t_U8 × t_Tag).
Fail Next Obligation.
