(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

Notation "'t_Block'" := (nseq int8 BLOCK_SIZE).
Definition Block : both t_Block -> both t_Block :=
  id.

Notation "'t_Hash'" := (nseq int32 8).
Definition Hash : both t_Hash -> both t_Hash :=
  id.

Notation "'t_OpTableType'" := (nseq int32 12).
Definition OpTableType : both t_OpTableType -> both t_OpTableType :=
  id.

Notation "'t_RoundConstantsTable'" := (nseq int32 K_SIZE).
Definition RoundConstantsTable : both t_RoundConstantsTable -> both t_RoundConstantsTable :=
  id.

Notation "'t_Sha256Digest'" := (nseq int8 HASH_SIZE).
Definition Sha256Digest : both t_Sha256Digest -> both t_Sha256Digest :=
  id.

(*Not implemented yet? todo(item)*)

Equations v_BLOCK_SIZE : both uint_size :=
  v_BLOCK_SIZE  :=
    solve_lift (ret_both (64 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations v_HASH_SIZE : both uint_size :=
  v_HASH_SIZE  :=
    solve_lift ((ret_both (256 : uint_size)) ./ (ret_both (8 : uint_size))) : both uint_size.
Fail Next Obligation.

Equations v_K_SIZE : both uint_size :=
  v_K_SIZE  :=
    solve_lift (ret_both (64 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations v_LEN_SIZE : both uint_size :=
  v_LEN_SIZE  :=
    solve_lift (ret_both (8 : uint_size)) : both uint_size.
Fail Next Obligation.

Equations v_OP_TABLE : both t_OpTableType :=
  v_OP_TABLE  :=
    OpTableType (array_from_list [solve_lift (ret_both (2 : uint_size));
      solve_lift (ret_both (13 : uint_size));
      solve_lift (ret_both (22 : uint_size));
      solve_lift (ret_both (6 : uint_size));
      solve_lift (ret_both (11 : uint_size));
      solve_lift (ret_both (25 : uint_size));
      solve_lift (ret_both (7 : uint_size));
      solve_lift (ret_both (18 : uint_size));
      solve_lift (ret_both (3 : uint_size));
      solve_lift (ret_both (17 : uint_size));
      solve_lift (ret_both (19 : uint_size));
      solve_lift (ret_both (10 : uint_size))]) : both t_OpTableType.
Fail Next Obligation.

Equations ch (x : both t_U32) (y : both t_U32) (z : both t_U32) : both t_U32 :=
  ch x y z  :=
    solve_lift ((x .& y) .^ ((f_not x) .& z)) : both t_U32.
Fail Next Obligation.

Equations maj (x : both t_U32) (y : both t_U32) (z : both t_U32) : both t_U32 :=
  maj x y z  :=
    solve_lift ((x .& y) .^ ((x .& z) .^ (y .& z))) : both t_U32.
Fail Next Obligation.

Equations sigma (x : both t_U32) (i : both uint_size) (op : both uint_size) : both t_U32 :=
  sigma x i op  :=
    letb (tmp : t_U32) := impl__U32__rotate_right x (v_OP_TABLE.a[(((ret_both (3 : uint_size)) .* i) .+ (ret_both (2 : uint_size)))]) in
    letb tmp := ifb op =.? (ret_both (0 : uint_size))
    then x shift_right (v_OP_TABLE.a[(((ret_both (3 : uint_size)) .* i) .+ (ret_both (2 : uint_size)))])
    else tmp in
    solve_lift (((impl__U32__rotate_right x (v_OP_TABLE.a[((ret_both (3 : uint_size)) .* i)])) .^ (impl__U32__rotate_right x (v_OP_TABLE.a[(((ret_both (3 : uint_size)) .* i) .+ (ret_both (1 : uint_size)))]))) .^ tmp) : both t_U32.
Fail Next Obligation.

Equations schedule (block : both t_Block) : both t_RoundConstantsTable :=
  schedule block  :=
    letb b := impl__Block__to_be_U32s block in
    letb s := impl__RoundConstantsTable__new (ret_both (tt : 'unit)) in
    letb s := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := v_K_SIZE))) s (fun s => fun i =>
      ifb i <.? (ret_both (16 : uint_size))
      then letb s := update_at_usize s i (b.a[i]) in
      s
      else letb t16 := s.a[(i .- (ret_both (16 : uint_size)))] in
      letb t15 := s.a[(i .- (ret_both (15 : uint_size)))] in
      letb t7 := s.a[(i .- (ret_both (7 : uint_size)))] in
      letb t2 := s.a[(i .- (ret_both (2 : uint_size)))] in
      letb s1 := sigma t2 (ret_both (3 : uint_size)) (ret_both (0 : uint_size)) in
      letb s0 := sigma t15 (ret_both (2 : uint_size)) (ret_both (0 : uint_size)) in
      letb s := update_at_usize s i (((s1 .+ t7) .+ s0) .+ t16) in
      s) in
    solve_lift s : both t_RoundConstantsTable.
Fail Next Obligation.

Equations v_HASH_INIT : both t_Hash :=
  v_HASH_INIT  :=
    Hash (array_from_list [U32 (solve_lift (ret_both (1779033703 : int32)));
      U32 (solve_lift (ret_both (3144134277 : int32)));
      U32 (solve_lift (ret_both (1013904242 : int32)));
      U32 (solve_lift (ret_both (2773480762 : int32)));
      U32 (solve_lift (ret_both (1359893119 : int32)));
      U32 (solve_lift (ret_both (2600822924 : int32)));
      U32 (solve_lift (ret_both (528734635 : int32)));
      U32 (solve_lift (ret_both (1541459225 : int32)))]) : both t_Hash.
Fail Next Obligation.

Equations v_K_TABLE : both t_RoundConstantsTable :=
  v_K_TABLE  :=
    RoundConstantsTable (array_from_list [U32 (solve_lift (ret_both (1116352408 : int32)));
      U32 (solve_lift (ret_both (1899447441 : int32)));
      U32 (solve_lift (ret_both (3049323471 : int32)));
      U32 (solve_lift (ret_both (3921009573 : int32)));
      U32 (solve_lift (ret_both (961987163 : int32)));
      U32 (solve_lift (ret_both (1508970993 : int32)));
      U32 (solve_lift (ret_both (2453635748 : int32)));
      U32 (solve_lift (ret_both (2870763221 : int32)));
      U32 (solve_lift (ret_both (3624381080 : int32)));
      U32 (solve_lift (ret_both (310598401 : int32)));
      U32 (solve_lift (ret_both (607225278 : int32)));
      U32 (solve_lift (ret_both (1426881987 : int32)));
      U32 (solve_lift (ret_both (1925078388 : int32)));
      U32 (solve_lift (ret_both (2162078206 : int32)));
      U32 (solve_lift (ret_both (2614888103 : int32)));
      U32 (solve_lift (ret_both (3248222580 : int32)));
      U32 (solve_lift (ret_both (3835390401 : int32)));
      U32 (solve_lift (ret_both (4022224774 : int32)));
      U32 (solve_lift (ret_both (264347078 : int32)));
      U32 (solve_lift (ret_both (604807628 : int32)));
      U32 (solve_lift (ret_both (770255983 : int32)));
      U32 (solve_lift (ret_both (1249150122 : int32)));
      U32 (solve_lift (ret_both (1555081692 : int32)));
      U32 (solve_lift (ret_both (1996064986 : int32)));
      U32 (solve_lift (ret_both (2554220882 : int32)));
      U32 (solve_lift (ret_both (2821834349 : int32)));
      U32 (solve_lift (ret_both (2952996808 : int32)));
      U32 (solve_lift (ret_both (3210313671 : int32)));
      U32 (solve_lift (ret_both (3336571891 : int32)));
      U32 (solve_lift (ret_both (3584528711 : int32)));
      U32 (solve_lift (ret_both (113926993 : int32)));
      U32 (solve_lift (ret_both (338241895 : int32)));
      U32 (solve_lift (ret_both (666307205 : int32)));
      U32 (solve_lift (ret_both (773529912 : int32)));
      U32 (solve_lift (ret_both (1294757372 : int32)));
      U32 (solve_lift (ret_both (1396182291 : int32)));
      U32 (solve_lift (ret_both (1695183700 : int32)));
      U32 (solve_lift (ret_both (1986661051 : int32)));
      U32 (solve_lift (ret_both (2177026350 : int32)));
      U32 (solve_lift (ret_both (2456956037 : int32)));
      U32 (solve_lift (ret_both (2730485921 : int32)));
      U32 (solve_lift (ret_both (2820302411 : int32)));
      U32 (solve_lift (ret_both (3259730800 : int32)));
      U32 (solve_lift (ret_both (3345764771 : int32)));
      U32 (solve_lift (ret_both (3516065817 : int32)));
      U32 (solve_lift (ret_both (3600352804 : int32)));
      U32 (solve_lift (ret_both (4094571909 : int32)));
      U32 (solve_lift (ret_both (275423344 : int32)));
      U32 (solve_lift (ret_both (430227734 : int32)));
      U32 (solve_lift (ret_both (506948616 : int32)));
      U32 (solve_lift (ret_both (659060556 : int32)));
      U32 (solve_lift (ret_both (883997877 : int32)));
      U32 (solve_lift (ret_both (958139571 : int32)));
      U32 (solve_lift (ret_both (1322822218 : int32)));
      U32 (solve_lift (ret_both (1537002063 : int32)));
      U32 (solve_lift (ret_both (1747873779 : int32)));
      U32 (solve_lift (ret_both (1955562222 : int32)));
      U32 (solve_lift (ret_both (2024104815 : int32)));
      U32 (solve_lift (ret_both (2227730452 : int32)));
      U32 (solve_lift (ret_both (2361852424 : int32)));
      U32 (solve_lift (ret_both (2428436474 : int32)));
      U32 (solve_lift (ret_both (2756734187 : int32)));
      U32 (solve_lift (ret_both (3204031479 : int32)));
      U32 (solve_lift (ret_both (3329325298 : int32)))]) : both t_RoundConstantsTable.
Fail Next Obligation.

Equations shuffle (ws : both t_RoundConstantsTable) (hashi : both t_Hash) : both t_Hash :=
  shuffle ws hashi  :=
    letb h := hashi in
    letb h := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := v_K_SIZE))) h (fun h => fun i =>
      letb a0 := h.a[(ret_both (0 : int32))] in
      letb b0 := h.a[(ret_both (1 : int32))] in
      letb c0 := h.a[(ret_both (2 : int32))] in
      letb d0 := h.a[(ret_both (3 : int32))] in
      letb e0 := h.a[(ret_both (4 : int32))] in
      letb f0 := h.a[(ret_both (5 : int32))] in
      letb g0 := h.a[(ret_both (6 : int32))] in
      letb (h0 : t_U32) := h.a[(ret_both (7 : int32))] in
      letb t1 := (((h0 .+ (sigma e0 (ret_both (1 : uint_size)) (ret_both (1 : uint_size)))) .+ (ch e0 f0 g0)) .+ (v_K_TABLE.a[i])) .+ (ws.a[i]) in
      letb t2 := (sigma a0 (ret_both (0 : uint_size)) (ret_both (1 : uint_size))) .+ (maj a0 b0 c0) in
      letb h := update_at h (ret_both (0 : int32)) (t1 .+ t2) in
      letb h := update_at h (ret_both (1 : int32)) a0 in
      letb h := update_at h (ret_both (2 : int32)) b0 in
      letb h := update_at h (ret_both (3 : int32)) c0 in
      letb h := update_at h (ret_both (4 : int32)) (d0 .+ t1) in
      letb h := update_at h (ret_both (5 : int32)) e0 in
      letb h := update_at h (ret_both (6 : int32)) f0 in
      letb h := update_at h (ret_both (7 : int32)) g0 in
      h) in
    solve_lift h : both t_Hash.
Fail Next Obligation.

Equations compress (block : both t_Block) (h_in : both t_Hash) : both t_Hash :=
  compress block h_in  :=
    letb s := schedule block in
    letb h := shuffle s h_in in
    letb h := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (8 : int32)))) h (fun h => fun i =>
      update_at h i ((h.a[i]) .+ (h_in.a[i]))) in
    solve_lift h : both t_Hash.
Fail Next Obligation.

Equations hash (msg : both (t_Seq t_U8)) : both t_Sha256Digest :=
  hash msg  :=
    letb h := v_HASH_INIT in
    letb last_block := impl__Block__new (ret_both (tt : 'unit)) in
    letb last_block_len := ret_both (0 : uint_size) in
    letb '(h,last_block,last_block_len) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__num_chunks msg v_BLOCK_SIZE))) (prod_b (h,last_block,last_block_len)) (fun '(h,last_block,last_block_len) => fun i =>
      letb '(block_len,block) := impl_41__get_chunk msg v_BLOCK_SIZE i in
      ifb block_len <.? v_BLOCK_SIZE
      then letb last_block := f_update_start (impl__Block__new (ret_both (tt : 'unit))) block in
      letb last_block_len := block_len in
      prod_b (h,last_block,last_block_len)
      else letb compress_input := impl__Block__from_seq block in
      letb h := compress compress_input h in
      prod_b (h,last_block,last_block_len)) in
    letb last_block := update_at_usize last_block last_block_len (U8 (ret_both (128 : int8))) in
    letb len_bist := U64 (cast_int (WS2 := _) ((impl_41__len msg) .* (ret_both (8 : uint_size)))) in
    letb '(h,last_block) := ifb last_block_len <.? (v_BLOCK_SIZE .- v_LEN_SIZE)
    then letb last_block := f_update last_block (v_BLOCK_SIZE .- v_LEN_SIZE) (v_U64_to_be_bytes len_bist) in
    letb h := compress last_block h in
    prod_b (h,last_block)
    else letb pad_block := impl__Block__new (ret_both (tt : 'unit)) in
    letb pad_block := f_update pad_block (v_BLOCK_SIZE .- v_LEN_SIZE) (v_U64_to_be_bytes len_bist) in
    letb h := compress last_block h in
    letb h := compress pad_block h in
    prod_b (h,last_block) in
    solve_lift (impl__Sha256Digest__from_seq (impl__Hash__to_be_bytes h)) : both t_Sha256Digest.
Fail Next Obligation.

Equations sha256 (msg : both (t_Seq t_U8)) : both t_Sha256Digest :=
  sha256 msg  :=
    solve_lift (hash msg) : both t_Sha256Digest.
Fail Next Obligation.
