(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

Notation "'t_G1_pallas'" := (t_FpPallas × t_FpPallas × 'bool).

Notation "'t_G1_vesta'" := (t_FpVesta × t_FpVesta × 'bool).

Notation "'t_FpPallas'" := (nat_mod 0x40000000000000000000000000000000224698FC094CF91B992D30ED00000001).
Definition FpPallas : both t_FpPallas -> both t_FpPallas :=
  id.

Notation "'t_FpVesta'" := (nat_mod 0x40000000000000000000000000000000224698FC0994A8DD8C46EB2100000001).
Definition FpVesta : both t_FpVesta -> both t_FpVesta :=
  id.

(*Not implemented yet? todo(item)*)

Equations g1_default_pallas (_ : both 'unit) : both (t_FpPallas × t_FpPallas × 'bool) :=
  g1_default_pallas _  :=
    solve_lift (prod_b (f_ZERO (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)),ret_both (true : 'bool))) : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations g1_default_vesta (_ : both 'unit) : both (t_FpVesta × t_FpVesta × 'bool) :=
  g1_default_vesta _  :=
    solve_lift (prod_b (f_ZERO (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)),ret_both (true : 'bool))) : both (t_FpVesta × t_FpVesta × 'bool).
Fail Next Obligation.

Equations g1_is_identity_pallas (p : both (t_FpPallas × t_FpPallas × 'bool)) : both 'bool :=
  g1_is_identity_pallas p  :=
    letb '(_,_,inf) := p in
    solve_lift inf : both 'bool.
Fail Next Obligation.

Equations g1_is_identity_vesta (p : both (t_FpVesta × t_FpVesta × 'bool)) : both 'bool :=
  g1_is_identity_vesta p  :=
    letb '(_,_,inf) := p in
    solve_lift inf : both 'bool.
Fail Next Obligation.

Equations g1_on_curve_pallas (p : both (t_FpPallas × t_FpPallas × 'bool)) : both 'bool :=
  g1_on_curve_pallas p  :=
    letb '(x,y,inf) := p in
    letb y_squared := y .* y in
    letb x_cubed := (x .* x) .* x in
    letb fp5 := ((f_TWO (ret_both (tt : 'unit))) .+ (f_TWO (ret_both (tt : 'unit)))) .+ (f_ONE (ret_both (tt : 'unit))) in
    solve_lift (orb (y_squared =.? (x_cubed .+ fp5)) inf) : both 'bool.
Fail Next Obligation.

Equations g1_on_curve_vesta (p : both (t_FpVesta × t_FpVesta × 'bool)) : both 'bool :=
  g1_on_curve_vesta p  :=
    letb '(x,y,inf) := p in
    letb y_squared := y .* y in
    letb x_cubed := (x .* x) .* x in
    letb fp5 := ((f_TWO (ret_both (tt : 'unit))) .+ (f_TWO (ret_both (tt : 'unit)))) .+ (f_ONE (ret_both (tt : 'unit))) in
    solve_lift (orb (y_squared =.? (x_cubed .+ fp5)) inf) : both 'bool.
Fail Next Obligation.

Equations g1add_a_pallas (p : both (t_FpPallas × t_FpPallas × 'bool)) (q : both (t_FpPallas × t_FpPallas × 'bool)) : both (t_FpPallas × t_FpPallas × 'bool) :=
  g1add_a_pallas p q  :=
    letb '(x1,y1,_) := p in
    letb '(x2,y2,_) := q in
    letb x_diff := x2 .- x1 in
    letb y_diff := y2 .- y1 in
    letb xovery := y_diff .* (impl__FpPallas__inv x_diff) in
    letb x3 := ((f_exp xovery (ret_both (2 : int32))) .- x1) .- x2 in
    letb y3 := (xovery .* (x1 .- x3)) .- y1 in
    solve_lift (prod_b (x3,y3,ret_both (false : 'bool))) : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations g1add_a_vesta (p : both (t_FpVesta × t_FpVesta × 'bool)) (q : both (t_FpVesta × t_FpVesta × 'bool)) : both (t_FpVesta × t_FpVesta × 'bool) :=
  g1add_a_vesta p q  :=
    letb '(x1,y1,_) := p in
    letb '(x2,y2,_) := q in
    letb x_diff := x2 .- x1 in
    letb y_diff := y2 .- y1 in
    letb xovery := y_diff .* (impl__FpVesta__inv x_diff) in
    letb x3 := ((f_exp xovery (ret_both (2 : int32))) .- x1) .- x2 in
    letb y3 := (xovery .* (x1 .- x3)) .- y1 in
    solve_lift (prod_b (x3,y3,ret_both (false : 'bool))) : both (t_FpVesta × t_FpVesta × 'bool).
Fail Next Obligation.

Equations g1double_a_pallas (p : both (t_FpPallas × t_FpPallas × 'bool)) : both (t_FpPallas × t_FpPallas × 'bool) :=
  g1double_a_pallas p  :=
    letb '(x1,y1,_) := p in
    letb x12 := f_exp x1 (ret_both (2 : int32)) in
    letb xovery := ((impl__FpPallas__from_literal (ret_both (3 : int128))) .* x12) .* (impl__FpPallas__inv ((f_TWO (ret_both (tt : 'unit))) .* y1)) in
    letb x3 := (f_exp xovery (ret_both (2 : int32))) .- ((f_TWO (ret_both (tt : 'unit))) .* x1) in
    letb y3 := (xovery .* (x1 .- x3)) .- y1 in
    solve_lift (prod_b (x3,y3,ret_both (false : 'bool))) : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations g1double_a_vesta (p : both (t_FpVesta × t_FpVesta × 'bool)) : both (t_FpVesta × t_FpVesta × 'bool) :=
  g1double_a_vesta p  :=
    letb '(x1,y1,_) := p in
    letb x12 := f_exp x1 (ret_both (2 : int32)) in
    letb xovery := ((impl__FpVesta__from_literal (ret_both (3 : int128))) .* x12) .* (impl__FpVesta__inv ((f_TWO (ret_both (tt : 'unit))) .* y1)) in
    letb x3 := (f_exp xovery (ret_both (2 : int32))) .- ((f_TWO (ret_both (tt : 'unit))) .* x1) in
    letb y3 := (xovery .* (x1 .- x3)) .- y1 in
    solve_lift (prod_b (x3,y3,ret_both (false : 'bool))) : both (t_FpVesta × t_FpVesta × 'bool).
Fail Next Obligation.

Equations g1double_pallas (p : both (t_FpPallas × t_FpPallas × 'bool)) : both (t_FpPallas × t_FpPallas × 'bool) :=
  g1double_pallas p  :=
    letb '(v__x1,y1,inf1) := p in
    solve_lift (ifb andb (y1 <> (f_ZERO (ret_both (tt : 'unit)))) (not inf1)
    then g1double_a_pallas p
    else prod_b (f_ZERO (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)),ret_both (true : 'bool))) : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations g1add_pallas (p : both (t_FpPallas × t_FpPallas × 'bool)) (q : both (t_FpPallas × t_FpPallas × 'bool)) : both (t_FpPallas × t_FpPallas × 'bool) :=
  g1add_pallas p q  :=
    letb '(x1,y1,inf1) := p in
    letb '(x2,y2,inf2) := q in
    solve_lift (ifb inf1
    then q
    else ifb inf2
    then p
    else ifb p =.? q
    then g1double_pallas p
    else ifb not (andb (x1 =.? x2) (y1 =.? ((f_ZERO (ret_both (tt : 'unit))) .- y2)))
    then g1add_a_pallas p q
    else prod_b (f_ZERO (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)),ret_both (true : 'bool))) : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations g1double_vesta (p : both (t_FpVesta × t_FpVesta × 'bool)) : both (t_FpVesta × t_FpVesta × 'bool) :=
  g1double_vesta p  :=
    letb '(v__x1,y1,inf1) := p in
    solve_lift (ifb andb (y1 <> (f_ZERO (ret_both (tt : 'unit)))) (not inf1)
    then g1double_a_vesta p
    else prod_b (f_ZERO (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)),ret_both (true : 'bool))) : both (t_FpVesta × t_FpVesta × 'bool).
Fail Next Obligation.

Equations g1add_vesta (p : both (t_FpVesta × t_FpVesta × 'bool)) (q : both (t_FpVesta × t_FpVesta × 'bool)) : both (t_FpVesta × t_FpVesta × 'bool) :=
  g1add_vesta p q  :=
    letb '(x1,y1,inf1) := p in
    letb '(x2,y2,inf2) := q in
    solve_lift (ifb inf1
    then q
    else ifb inf2
    then p
    else ifb p =.? q
    then g1double_vesta p
    else ifb not (andb (x1 =.? x2) (y1 =.? ((f_ZERO (ret_both (tt : 'unit))) .- y2)))
    then g1add_a_vesta p q
    else prod_b (f_ZERO (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)),ret_both (true : 'bool))) : both (t_FpVesta × t_FpVesta × 'bool).
Fail Next Obligation.

Equations g1neg_pallas (p : both (t_FpPallas × t_FpPallas × 'bool)) : both (t_FpPallas × t_FpPallas × 'bool) :=
  g1neg_pallas p  :=
    letb '(x,y,inf) := p in
    solve_lift (prod_b (x,(f_ZERO (ret_both (tt : 'unit))) .- y,inf)) : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations g1neg_vesta (p : both (t_FpVesta × t_FpVesta × 'bool)) : both (t_FpVesta × t_FpVesta × 'bool) :=
  g1neg_vesta p  :=
    letb '(x,y,inf) := p in
    solve_lift (prod_b (x,(f_ZERO (ret_both (tt : 'unit))) .- y,inf)) : both (t_FpVesta × t_FpVesta × 'bool).
Fail Next Obligation.

Equations g1mul_pallas (m : both t_FpVesta) (p : both (t_FpPallas × t_FpPallas × 'bool)) : both (t_FpPallas × t_FpPallas × 'bool) :=
  g1mul_pallas m p  :=
    letb t := prod_b (f_ZERO (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)),ret_both (true : 'bool)) in
    letb t := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := ret_both (255 : uint_size)))) t (fun t => fun i =>
      letb t := g1double_pallas t in
      ifb impl__FpVesta__bit m ((ret_both (254 : uint_size)) .- i)
      then letb t := g1add_pallas t p in
      t
      else t) in
    solve_lift t : both (t_FpPallas × t_FpPallas × 'bool).
Fail Next Obligation.

Equations g1mul_vesta (m : both t_FpPallas) (p : both (t_FpVesta × t_FpVesta × 'bool)) : both (t_FpVesta × t_FpVesta × 'bool) :=
  g1mul_vesta m p  :=
    letb t := prod_b (f_ZERO (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)),ret_both (true : 'bool)) in
    letb t := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := ret_both (255 : uint_size)))) t (fun t => fun i =>
      letb t := g1double_vesta t in
      ifb impl__FpPallas__bit m ((ret_both (254 : uint_size)) .- i)
      then letb t := g1add_vesta t p in
      t
      else t) in
    solve_lift t : both (t_FpVesta × t_FpVesta × 'bool).
Fail Next Obligation.
