(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib.
From Coq Require Import ZArith.
Import List.ListNotations.
Require Import Coq.Strings.String.
Open Scope Z_scope.
Open Scope bool_scope.
Open Scope hacspec_scope.

Require Import Hacspec_lib.
Export Hacspec_lib.

(*Not implemented yet? todo(item)*)

Definition v_RCON : nseq t_u8 TODO: Int.to_string length :=
  array_from_list [(Int8.repr 141);
    (Int8.repr 1);
    (Int8.repr 2);
    (Int8.repr 4);
    (Int8.repr 8);
    (Int8.repr 16);
    (Int8.repr 32);
    (Int8.repr 64);
    (Int8.repr 128);
    (Int8.repr 27);
    (Int8.repr 54);
    (Int8.repr 108);
    (Int8.repr 216);
    (Int8.repr 171);
    (Int8.repr 77)].

Definition v_SBOX : nseq t_u8 TODO: Int.to_string length :=
  array_from_list [(Int8.repr 99);
    (Int8.repr 124);
    (Int8.repr 119);
    (Int8.repr 123);
    (Int8.repr 242);
    (Int8.repr 107);
    (Int8.repr 111);
    (Int8.repr 197);
    (Int8.repr 48);
    (Int8.repr 1);
    (Int8.repr 103);
    (Int8.repr 43);
    (Int8.repr 254);
    (Int8.repr 215);
    (Int8.repr 171);
    (Int8.repr 118);
    (Int8.repr 202);
    (Int8.repr 130);
    (Int8.repr 201);
    (Int8.repr 125);
    (Int8.repr 250);
    (Int8.repr 89);
    (Int8.repr 71);
    (Int8.repr 240);
    (Int8.repr 173);
    (Int8.repr 212);
    (Int8.repr 162);
    (Int8.repr 175);
    (Int8.repr 156);
    (Int8.repr 164);
    (Int8.repr 114);
    (Int8.repr 192);
    (Int8.repr 183);
    (Int8.repr 253);
    (Int8.repr 147);
    (Int8.repr 38);
    (Int8.repr 54);
    (Int8.repr 63);
    (Int8.repr 247);
    (Int8.repr 204);
    (Int8.repr 52);
    (Int8.repr 165);
    (Int8.repr 229);
    (Int8.repr 241);
    (Int8.repr 113);
    (Int8.repr 216);
    (Int8.repr 49);
    (Int8.repr 21);
    (Int8.repr 4);
    (Int8.repr 199);
    (Int8.repr 35);
    (Int8.repr 195);
    (Int8.repr 24);
    (Int8.repr 150);
    (Int8.repr 5);
    (Int8.repr 154);
    (Int8.repr 7);
    (Int8.repr 18);
    (Int8.repr 128);
    (Int8.repr 226);
    (Int8.repr 235);
    (Int8.repr 39);
    (Int8.repr 178);
    (Int8.repr 117);
    (Int8.repr 9);
    (Int8.repr 131);
    (Int8.repr 44);
    (Int8.repr 26);
    (Int8.repr 27);
    (Int8.repr 110);
    (Int8.repr 90);
    (Int8.repr 160);
    (Int8.repr 82);
    (Int8.repr 59);
    (Int8.repr 214);
    (Int8.repr 179);
    (Int8.repr 41);
    (Int8.repr 227);
    (Int8.repr 47);
    (Int8.repr 132);
    (Int8.repr 83);
    (Int8.repr 209);
    (Int8.repr 0);
    (Int8.repr 237);
    (Int8.repr 32);
    (Int8.repr 252);
    (Int8.repr 177);
    (Int8.repr 91);
    (Int8.repr 106);
    (Int8.repr 203);
    (Int8.repr 190);
    (Int8.repr 57);
    (Int8.repr 74);
    (Int8.repr 76);
    (Int8.repr 88);
    (Int8.repr 207);
    (Int8.repr 208);
    (Int8.repr 239);
    (Int8.repr 170);
    (Int8.repr 251);
    (Int8.repr 67);
    (Int8.repr 77);
    (Int8.repr 51);
    (Int8.repr 133);
    (Int8.repr 69);
    (Int8.repr 249);
    (Int8.repr 2);
    (Int8.repr 127);
    (Int8.repr 80);
    (Int8.repr 60);
    (Int8.repr 159);
    (Int8.repr 168);
    (Int8.repr 81);
    (Int8.repr 163);
    (Int8.repr 64);
    (Int8.repr 143);
    (Int8.repr 146);
    (Int8.repr 157);
    (Int8.repr 56);
    (Int8.repr 245);
    (Int8.repr 188);
    (Int8.repr 182);
    (Int8.repr 218);
    (Int8.repr 33);
    (Int8.repr 16);
    (Int8.repr 255);
    (Int8.repr 243);
    (Int8.repr 210);
    (Int8.repr 205);
    (Int8.repr 12);
    (Int8.repr 19);
    (Int8.repr 236);
    (Int8.repr 95);
    (Int8.repr 151);
    (Int8.repr 68);
    (Int8.repr 23);
    (Int8.repr 196);
    (Int8.repr 167);
    (Int8.repr 126);
    (Int8.repr 61);
    (Int8.repr 100);
    (Int8.repr 93);
    (Int8.repr 25);
    (Int8.repr 115);
    (Int8.repr 96);
    (Int8.repr 129);
    (Int8.repr 79);
    (Int8.repr 220);
    (Int8.repr 34);
    (Int8.repr 42);
    (Int8.repr 144);
    (Int8.repr 136);
    (Int8.repr 70);
    (Int8.repr 238);
    (Int8.repr 184);
    (Int8.repr 20);
    (Int8.repr 222);
    (Int8.repr 94);
    (Int8.repr 11);
    (Int8.repr 219);
    (Int8.repr 224);
    (Int8.repr 50);
    (Int8.repr 58);
    (Int8.repr 10);
    (Int8.repr 73);
    (Int8.repr 6);
    (Int8.repr 36);
    (Int8.repr 92);
    (Int8.repr 194);
    (Int8.repr 211);
    (Int8.repr 172);
    (Int8.repr 98);
    (Int8.repr 145);
    (Int8.repr 149);
    (Int8.repr 228);
    (Int8.repr 121);
    (Int8.repr 231);
    (Int8.repr 200);
    (Int8.repr 55);
    (Int8.repr 109);
    (Int8.repr 141);
    (Int8.repr 213);
    (Int8.repr 78);
    (Int8.repr 169);
    (Int8.repr 108);
    (Int8.repr 86);
    (Int8.repr 244);
    (Int8.repr 234);
    (Int8.repr 101);
    (Int8.repr 122);
    (Int8.repr 174);
    (Int8.repr 8);
    (Int8.repr 186);
    (Int8.repr 120);
    (Int8.repr 37);
    (Int8.repr 46);
    (Int8.repr 28);
    (Int8.repr 166);
    (Int8.repr 180);
    (Int8.repr 198);
    (Int8.repr 232);
    (Int8.repr 221);
    (Int8.repr 116);
    (Int8.repr 31);
    (Int8.repr 75);
    (Int8.repr 189);
    (Int8.repr 139);
    (Int8.repr 138);
    (Int8.repr 112);
    (Int8.repr 62);
    (Int8.repr 181);
    (Int8.repr 102);
    (Int8.repr 72);
    (Int8.repr 3);
    (Int8.repr 246);
    (Int8.repr 14);
    (Int8.repr 97);
    (Int8.repr 53);
    (Int8.repr 87);
    (Int8.repr 185);
    (Int8.repr 134);
    (Int8.repr 193);
    (Int8.repr 29);
    (Int8.repr 158);
    (Int8.repr 225);
    (Int8.repr 248);
    (Int8.repr 152);
    (Int8.repr 17);
    (Int8.repr 105);
    (Int8.repr 217);
    (Int8.repr 142);
    (Int8.repr 148);
    (Int8.repr 155);
    (Int8.repr 30);
    (Int8.repr 135);
    (Int8.repr 233);
    (Int8.repr 206);
    (Int8.repr 85);
    (Int8.repr 40);
    (Int8.repr 223);
    (Int8.repr 140);
    (Int8.repr 161);
    (Int8.repr 137);
    (Int8.repr 13);
    (Int8.repr 191);
    (Int8.repr 230);
    (Int8.repr 66);
    (Int8.repr 104);
    (Int8.repr 65);
    (Int8.repr 153);
    (Int8.repr 45);
    (Int8.repr 15);
    (Int8.repr 176);
    (Int8.repr 84);
    (Int8.repr 187);
    (Int8.repr 22)].

Definition index_u32 (s : t_u128) (i : t_usize) : t_u32 :=
  cast ((s shift_right (i.*(Int32.repr 32))).%((Int128.repr 1) shift_left (Int32.repr 32)) : t_u128) : t_u32.

Definition index_u8 (s : t_u32) (i : t_usize) : t_u8 :=
  cast ((s shift_right (i.*(Int32.repr 8))).%((Int32.repr 1) shift_left (Int32.repr 8)) : t_u32) : t_u8.

Definition matrix_index (s : t_u128) (i : t_usize) (j : t_usize) : t_u8 :=
  index_u8 (index_u32 (s : t_u128) (j : t_usize) : t_u32) (i : t_usize) : t_u8.

Definition rebuild_u128 (s0 : t_u32) (s1 : t_u32) (s2 : t_u32) (s3 : t_u32) : t_u128 :=
  (cast (s0 : t_u32) : t_u128).|(((cast (s1 : t_u32) : t_u128) shift_left (Int32.repr 32)).|(((cast (s2 : t_u32) : t_u128) shift_left (Int32.repr 64)).|((cast (s3 : t_u32) : t_u128) shift_left (Int32.repr 96)))).

Definition rebuild_u32 (s0 : t_u8) (s1 : t_u8) (s2 : t_u8) (s3 : t_u8) : t_u32 :=
  (cast (s0 : t_u8) : t_u32).|(((cast (s1 : t_u8) : t_u32) shift_left (Int32.repr 8)).|(((cast (s2 : t_u8) : t_u32) shift_left (Int32.repr 16)).|((cast (s3 : t_u8) : t_u32) shift_left (Int32.repr 24)))).

Definition rotword (v : t_u32) : t_u32 :=
  rebuild_u32 (index_u8 (v : t_u32) ((Int32.repr 1) : t_usize) : t_u8) (index_u8 (v : t_u32) ((Int32.repr 2) : t_usize) : t_u8) (index_u8 (v : t_u32) ((Int32.repr 3) : t_usize) : t_u8) (index_u8 (v : t_u32) ((Int32.repr 0) : t_usize) : t_u8) : t_u32.

Definition shiftrows (s : t_u128) : t_u128 :=
  rebuild_u128 (rebuild_u32 (matrix_index (s : t_u128) ((Int32.repr 0) : t_usize) ((Int32.repr 0) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 1) : t_usize) ((Int32.repr 1) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 2) : t_usize) ((Int32.repr 2) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 3) : t_usize) ((Int32.repr 3) : t_usize) : t_u8) : t_u32) (rebuild_u32 (matrix_index (s : t_u128) ((Int32.repr 0) : t_usize) ((Int32.repr 1) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 1) : t_usize) ((Int32.repr 2) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 2) : t_usize) ((Int32.repr 3) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 3) : t_usize) ((Int32.repr 0) : t_usize) : t_u8) : t_u32) (rebuild_u32 (matrix_index (s : t_u128) ((Int32.repr 0) : t_usize) ((Int32.repr 2) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 1) : t_usize) ((Int32.repr 3) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 2) : t_usize) ((Int32.repr 0) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 3) : t_usize) ((Int32.repr 1) : t_usize) : t_u8) : t_u32) (rebuild_u32 (matrix_index (s : t_u128) ((Int32.repr 0) : t_usize) ((Int32.repr 3) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 1) : t_usize) ((Int32.repr 0) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 2) : t_usize) ((Int32.repr 1) : t_usize) : t_u8) (matrix_index (s : t_u128) ((Int32.repr 3) : t_usize) ((Int32.repr 2) : t_usize) : t_u8) : t_u32) : t_u128.

Definition subword (v : t_u32) : t_u32 :=
  rebuild_u32 (v_SBOX.[(cast (index_u8 (v : t_u32) ((Int32.repr 0) : t_usize) : t_u8) : t_usize)] : t_u8) (v_SBOX.[(cast (index_u8 (v : t_u32) ((Int32.repr 1) : t_usize) : t_u8) : t_usize)] : t_u8) (v_SBOX.[(cast (index_u8 (v : t_u32) ((Int32.repr 2) : t_usize) : t_u8) : t_usize)] : t_u8) (v_SBOX.[(cast (index_u8 (v : t_u32) ((Int32.repr 3) : t_usize) : t_u8) : t_usize)] : t_u8) : t_u32.

Definition aeskeygenassist (v1 : t_u128) (v2 : t_u8) : t_u128 :=
  let x1 := index_u32 (v1 : t_u128) ((Int32.repr 1) : t_usize) : t_u32 : t_u32 in
  let x3 := index_u32 (v1 : t_u128) ((Int32.repr 3) : t_usize) : t_u32 : t_u32 in
  let y0 := subword (x1 : t_u32) : t_u32 : t_u32 in
  let y1 := (rotword (y0 : t_u32) : t_u32).^(cast (v2 : t_u8) : t_u32) : t_u32 in
  let y2 := subword (x3 : t_u32) : t_u32 : t_u32 in
  let y3 := (rotword (y2 : t_u32) : t_u32).^(cast (v2 : t_u8) : t_u32) : t_u32 in
  rebuild_u128 (y0 : t_u32) (y1 : t_u32) (y2 : t_u32) (y3 : t_u32) : t_u128.

Definition subbytes (s : t_u128) : t_u128 :=
  rebuild_u128 (subword (index_u32 (s : t_u128) ((Int32.repr 0) : t_usize) : t_u32) : t_u32) (subword (index_u32 (s : t_u128) ((Int32.repr 1) : t_usize) : t_u32) : t_u32) (subword (index_u32 (s : t_u128) ((Int32.repr 2) : t_usize) : t_u32) : t_u32) (subword (index_u32 (s : t_u128) ((Int32.repr 3) : t_usize) : t_u32) : t_u32) : t_u128.

Definition aesenclast (state : t_u128) (rkey : t_u128) : t_u128 :=
  let state := shiftrows (state : t_u128) : t_u128 : t_u128 in
  let state := subbytes (state : t_u128) : t_u128 : t_u128 in
  state.^rkey.

Definition vpshufd1 (s : t_u128) (o : t_u8) (i : t_usize) : t_u32 :=
  index_u32 (s shift_right ((Int32.repr 32).*(cast ((o shift_right ((Int32.repr 2).*i)).%(Int8.repr 4) : t_u8) : t_usize)) : t_u128) ((Int32.repr 0) : t_usize) : t_u32.

Definition vpshufd (s : t_u128) (o : t_u8) : t_u128 :=
  let d1 := vpshufd1 (s : t_u128) (o : t_u8) ((Int32.repr 0) : t_usize) : t_u32 : t_u32 in
  let d2 := vpshufd1 (s : t_u128) (o : t_u8) ((Int32.repr 1) : t_usize) : t_u32 : t_u32 in
  let d3 := vpshufd1 (s : t_u128) (o : t_u8) ((Int32.repr 2) : t_usize) : t_u32 : t_u32 in
  let d4 := vpshufd1 (s : t_u128) (o : t_u8) ((Int32.repr 3) : t_usize) : t_u32 : t_u32 in
  rebuild_u128 (d1 : t_u32) (d2 : t_u32) (d3 : t_u32) (d4 : t_u32) : t_u128.

Definition vshufps (s1 : t_u128) (s2 : t_u128) (o : t_u8) : t_u128 :=
  let d1 := vpshufd1 (s1 : t_u128) (o : t_u8) ((Int32.repr 0) : t_usize) : t_u32 : t_u32 in
  let d2 := vpshufd1 (s1 : t_u128) (o : t_u8) ((Int32.repr 1) : t_usize) : t_u32 : t_u32 in
  let d3 := vpshufd1 (s2 : t_u128) (o : t_u8) ((Int32.repr 2) : t_usize) : t_u32 : t_u32 in
  let d4 := vpshufd1 (s2 : t_u128) (o : t_u8) ((Int32.repr 3) : t_usize) : t_u32 : t_u32 in
  rebuild_u128 (d1 : t_u32) (d2 : t_u32) (d3 : t_u32) (d4 : t_u32) : t_u128.

Definition key_combine (rkey : t_u128) (temp1 : t_u128) (temp2 : t_u128) : t_u128 * t_u128 :=
  let temp1 := vpshufd (temp1 : t_u128) ((Int8.repr 255) : t_u8) : t_u128 : t_u128 in
  let temp2 := vshufps (temp2 : t_u128) (rkey : t_u128) ((Int8.repr 16) : t_u8) : t_u128 : t_u128 in
  let rkey := rkey.^temp2 : t_u128 in
  let temp2 := vshufps (temp2 : t_u128) (rkey : t_u128) ((Int8.repr 140) : t_u8) : t_u128 : t_u128 in
  let rkey := rkey.^temp2 : t_u128 in
  let rkey := rkey.^temp1 : t_u128 in
  (rkey,temp2).

Definition key_expand (rcon : t_u8) (rkey : t_u128) (temp2 : t_u128) : t_u128 * t_u128 :=
  let temp1 := aeskeygenassist (rkey : t_u128) (rcon : t_u8) : t_u128 : t_u128 in
  key_combine (rkey : t_u128) (temp1 : t_u128) (temp2 : t_u128) : (t_u128 * t_u128).

Definition xtime (x : t_u8) : t_u8 :=
  let x1 := x shift_left (Int32.repr 1) : t_u8 in
  let x7 := x shift_right (Int32.repr 7) : t_u8 in
  let x71 := x7.&(Int8.repr 1) : t_u8 in
  let x711b := x71.*(Int8.repr 27) : t_u8 in
  x1.^x711b.

Definition mixcolumn (c : t_usize) (state : t_u128) : t_u32 :=
  let s0 := matrix_index (state : t_u128) ((Int32.repr 0) : t_usize) (c : t_usize) : t_u8 : t_u8 in
  let s1 := matrix_index (state : t_u128) ((Int32.repr 1) : t_usize) (c : t_usize) : t_u8 : t_u8 in
  let s2 := matrix_index (state : t_u128) ((Int32.repr 2) : t_usize) (c : t_usize) : t_u8 : t_u8 in
  let s3 := matrix_index (state : t_u128) ((Int32.repr 3) : t_usize) (c : t_usize) : t_u8 : t_u8 in
  let tmp := ((s0.^s1).^s2).^s3 : t_u8 in
  let r0 := (s0.^tmp).^(xtime (s0.^s1 : t_u8) : t_u8) : t_u8 in
  let r1 := (s1.^tmp).^(xtime (s1.^s2 : t_u8) : t_u8) : t_u8 in
  let r2 := (s2.^tmp).^(xtime (s2.^s3 : t_u8) : t_u8) : t_u8 in
  let r3 := (s3.^tmp).^(xtime (s3.^s0 : t_u8) : t_u8) : t_u8 in
  rebuild_u32 (r0 : t_u8) (r1 : t_u8) (r2 : t_u8) (r3 : t_u8) : t_u32.

Definition mixcolumns (state : t_u128) : t_u128 :=
  let c0 := mixcolumn ((Int32.repr 0) : t_usize) (state : t_u128) : t_u32 : t_u32 in
  let c1 := mixcolumn ((Int32.repr 1) : t_usize) (state : t_u128) : t_u32 : t_u32 in
  let c2 := mixcolumn ((Int32.repr 2) : t_usize) (state : t_u128) : t_u32 : t_u32 in
  let c3 := mixcolumn ((Int32.repr 3) : t_usize) (state : t_u128) : t_u32 : t_u32 in
  rebuild_u128 (c0 : t_u32) (c1 : t_u32) (c2 : t_u32) (c3 : t_u32) : t_u128.

Definition aesenc (state : t_u128) (rkey : t_u128) : t_u128 :=
  let state := shiftrows (state : t_u128) : t_u128 : t_u128 in
  let state := subbytes (state : t_u128) : t_u128 : t_u128 in
  let state := mixcolumns (state : t_u128) : t_u128 : t_u128 in
  state.^rkey.

Definition aes_rounds (rkeys : nseq t_u128 TODO: Int.to_string length) (inp : t_u128) : t_u128 :=
  let state := inp.^(rkeys.[(Int32.repr 0)]) : t_u128 in
  let state := fold_range ((Int32.repr 1) : t_usize) ((Int32.repr 10) : t_usize) (fun state => fun _ =>
      true : (t_u128 -> t_usize -> bool)) (state : t_u128) (fun state => fun round =>
      aesenc (state : t_u128) (rkeys.[round] : t_u128) : t_u128 : (t_u128 -> t_usize -> t_u128)) : t_u128 : t_u128 in
  aesenclast (state : t_u128) (rkeys.[(Int32.repr 10)] : t_u128) : t_u128.

Definition keys_expand (key : t_u128) : nseq t_u128 TODO: Int.to_string length :=
  let rkeys := repeat ((Int128.repr 0) : t_u128) ((Int32.repr 12) : t_usize) : (nseq t_u128 TODO: Int.to_string length) : nseq t_u128 TODO: Int.to_string length in
  let key := key : t_u128 in
  let rkeys := update_at_usize (rkeys : (nseq t_u128 TODO: Int.to_string length)) ((Int32.repr 0) : t_usize) (key : t_u128) : (nseq t_u128 TODO: Int.to_string length) : nseq t_u128 TODO: Int.to_string length in
  let temp2 := (Int128.repr 0) : t_u128 in
  let '(key,rkeys,temp2) := fold_range ((Int32.repr 1) : t_usize) ((Int32.repr 11) : t_usize) (fun '(key,rkeys,temp2) => fun _ =>
      true : (t_u128 * nseq t_u128 TODO: Int.to_string length * t_u128 -> t_usize -> bool)) ((key,rkeys,temp2) : (t_u128 * nseq t_u128 TODO: Int.to_string length * t_u128)) (fun '(key,rkeys,temp2) => fun round =>
      let rcon := v_RCON.[round] : t_u8 in
      let '(key_temp,temp2_temp) := key_expand (rcon : t_u8) (key : t_u128) (temp2 : t_u128) : (t_u128 * t_u128) : t_u128 * t_u128 in
      let key := key_temp : t_u128 in
      let temp2 := temp2_temp : t_u128 in
      let rkeys := update_at_usize (rkeys : (nseq t_u128 TODO: Int.to_string length)) (round : t_usize) (key : t_u128) : (nseq t_u128 TODO: Int.to_string length) : nseq t_u128 TODO: Int.to_string length in
      (key,rkeys,temp2) : (t_u128 * nseq t_u128 TODO: Int.to_string length * t_u128 -> t_usize -> t_u128 * nseq t_u128 TODO: Int.to_string length * t_u128)) : (t_u128 * nseq t_u128 TODO: Int.to_string length * t_u128) : t_u128 * nseq t_u128 TODO: Int.to_string length * t_u128 in
  rkeys.

Definition aes (key : t_u128) (inp : t_u128) : t_u128 :=
  let rkeys := keys_expand (key : t_u128) : (nseq t_u128 TODO: Int.to_string length) : nseq t_u128 TODO: Int.to_string length in
  aes_rounds (rkeys : (nseq t_u128 TODO: Int.to_string length)) (inp : t_u128) : t_u128.
