(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

Require Import Hacspec_sha512.
Export Hacspec_sha512.

Notation "'t_EdPoint'" := (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement).

Definition t_Error : choice_type :=
  ('unit ∐ 'unit ∐ 'unit ∐ 'unit ∐ 'unit ∐ 'unit).
Notation "'Error_InvalidPublickey_case'" := (inl (inl (inl (inl (inl tt))))) (at level 100).
Equations Error_InvalidPublickey : both t_Error :=
  Error_InvalidPublickey  :=
    solve_lift (ret_both (inl (inl (inl (inl (inl (tt : 'unit))))) : t_Error)) : both t_Error.
Fail Next Obligation.
Notation "'Error_InvalidSignature_case'" := (inl (inl (inl (inl (inr tt))))) (at level 100).
Equations Error_InvalidSignature : both t_Error :=
  Error_InvalidSignature  :=
    solve_lift (ret_both (inl (inl (inl (inl (inr (tt : 'unit))))) : t_Error)) : both t_Error.
Fail Next Obligation.
Notation "'Error_InvalidS_case'" := (inl (inl (inl (inr tt)))) (at level 100).
Equations Error_InvalidS : both t_Error :=
  Error_InvalidS  :=
    solve_lift (ret_both (inl (inl (inl (inr (tt : 'unit)))) : t_Error)) : both t_Error.
Fail Next Obligation.
Notation "'Error_InvalidR_case'" := (inl (inl (inr tt))) (at level 100).
Equations Error_InvalidR : both t_Error :=
  Error_InvalidR  :=
    solve_lift (ret_both (inl (inl (inr (tt : 'unit))) : t_Error)) : both t_Error.
Fail Next Obligation.
Notation "'Error_SmallOrderPoint_case'" := (inl (inr tt)) (at level 100).
Equations Error_SmallOrderPoint : both t_Error :=
  Error_SmallOrderPoint  :=
    solve_lift (ret_both (inl (inr (tt : 'unit)) : t_Error)) : both t_Error.
Fail Next Obligation.
Notation "'Error_NotEnoughRandomness_case'" := (inr tt) (at level 100).
Equations Error_NotEnoughRandomness : both t_Error :=
  Error_NotEnoughRandomness  :=
    solve_lift (ret_both (inr (tt : 'unit) : t_Error)) : both t_Error.
Fail Next Obligation.

Notation "'t_VerifyResult'" := (t_Result 'unit t_Error).

(*Not implemented yet? todo(item)*)

Equations point_eq (p : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) (q : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) : both 'bool :=
  point_eq p q  :=
    letb '(x1,y1,z1,_) := p in
    letb '(x2,y2,z2,_) := q in
    solve_lift (andb ((x1 .* z2) =.? (x2 .* z1)) ((y1 .* z2) =.? (y2 .* z1))) : both 'bool.
Fail Next Obligation.

Notation "'t_CompressedEdPoint'" := (nseq int8 32).
Definition CompressedEdPoint : both t_CompressedEdPoint -> both t_CompressedEdPoint :=
  id.

Notation "'t_PublicKey'" := t_CompressedEdPoint.

Notation "'t_SerializedScalar'" := (nseq int8 32).
Definition SerializedScalar : both t_SerializedScalar -> both t_SerializedScalar :=
  id.

Notation "'t_SecretKey'" := t_SerializedScalar.

Notation "'t_Signature'" := (nseq int8 64).
Definition Signature : both t_Signature -> both t_Signature :=
  id.

Notation "'t_BigInteger'" := (nat_mod 0x8000000000000000000000000000000080000000000000000000000000000000).
Definition BigInteger : both t_BigInteger -> both t_BigInteger :=
  id.

Notation "'t_BigScalar'" := (nat_mod 0x1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3ed).
Definition BigScalar : both t_BigScalar -> both t_BigScalar :=
  id.

Notation "'t_Ed25519FieldElement'" := (nat_mod 0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffed).
Definition Ed25519FieldElement : both t_Ed25519FieldElement -> both t_Ed25519FieldElement :=
  id.

Notation "'t_Scalar'" := (nat_mod 0x1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3ed).
Definition Scalar : both t_Scalar -> both t_Scalar :=
  id.

Equations point_normalize (q : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement) :=
  point_normalize q  :=
    letb '(qx,qy,qz,_) := q in
    letb px := qx .* (impl__Ed25519FieldElement__inv qz) in
    letb py := qy .* (impl__Ed25519FieldElement__inv qz) in
    letb pz := f_ONE (ret_both (tt : 'unit)) in
    letb pt := px .* py in
    solve_lift (prod_b (px,py,pz,pt)) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement).
Fail Next Obligation.

Equations point_identity (_ : both 'unit) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement) :=
  point_identity _  :=
    solve_lift (prod_b (f_ZERO (ret_both (tt : 'unit)),f_ONE (ret_both (tt : 'unit)),f_ONE (ret_both (tt : 'unit)),f_ZERO (ret_both (tt : 'unit)))) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement).
Fail Next Obligation.

Equations point_neg (p : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement) :=
  point_neg p  :=
    letb '(x,y,z,t) := p in
    solve_lift (prod_b ((f_ZERO (ret_both (tt : 'unit))) .- x,y,z,(f_ZERO (ret_both (tt : 'unit))) .- t)) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement).
Fail Next Obligation.

Equations v_BASE : both t_CompressedEdPoint :=
  v_BASE  :=
    CompressedEdPoint (array_from_list [U8 (solve_lift (ret_both (88 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)));
      U8 (solve_lift (ret_both (102 : int8)))]) : both t_CompressedEdPoint.
Fail Next Obligation.

Equations v_CONSTANT_D : both t_SerializedScalar :=
  v_CONSTANT_D  :=
    SerializedScalar (array_from_list [U8 (solve_lift (ret_both (163 : int8)));
      U8 (solve_lift (ret_both (120 : int8)));
      U8 (solve_lift (ret_both (89 : int8)));
      U8 (solve_lift (ret_both (19 : int8)));
      U8 (solve_lift (ret_both (202 : int8)));
      U8 (solve_lift (ret_both (77 : int8)));
      U8 (solve_lift (ret_both (235 : int8)));
      U8 (solve_lift (ret_both (117 : int8)));
      U8 (solve_lift (ret_both (171 : int8)));
      U8 (solve_lift (ret_both (216 : int8)));
      U8 (solve_lift (ret_both (65 : int8)));
      U8 (solve_lift (ret_both (65 : int8)));
      U8 (solve_lift (ret_both (77 : int8)));
      U8 (solve_lift (ret_both (10 : int8)));
      U8 (solve_lift (ret_both (112 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (152 : int8)));
      U8 (solve_lift (ret_both (232 : int8)));
      U8 (solve_lift (ret_both (121 : int8)));
      U8 (solve_lift (ret_both (119 : int8)));
      U8 (solve_lift (ret_both (121 : int8)));
      U8 (solve_lift (ret_both (64 : int8)));
      U8 (solve_lift (ret_both (199 : int8)));
      U8 (solve_lift (ret_both (140 : int8)));
      U8 (solve_lift (ret_both (115 : int8)));
      U8 (solve_lift (ret_both (254 : int8)));
      U8 (solve_lift (ret_both (111 : int8)));
      U8 (solve_lift (ret_both (43 : int8)));
      U8 (solve_lift (ret_both (238 : int8)));
      U8 (solve_lift (ret_both (108 : int8)));
      U8 (solve_lift (ret_both (3 : int8)));
      U8 (solve_lift (ret_both (82 : int8)))]) : both t_SerializedScalar.
Fail Next Obligation.

Equations v_CONSTANT_L : both t_SerializedScalar :=
  v_CONSTANT_L  :=
    SerializedScalar (array_from_list [U8 (solve_lift (ret_both (237 : int8)));
      U8 (solve_lift (ret_both (211 : int8)));
      U8 (solve_lift (ret_both (245 : int8)));
      U8 (solve_lift (ret_both (92 : int8)));
      U8 (solve_lift (ret_both (26 : int8)));
      U8 (solve_lift (ret_both (99 : int8)));
      U8 (solve_lift (ret_both (18 : int8)));
      U8 (solve_lift (ret_both (88 : int8)));
      U8 (solve_lift (ret_both (214 : int8)));
      U8 (solve_lift (ret_both (156 : int8)));
      U8 (solve_lift (ret_both (247 : int8)));
      U8 (solve_lift (ret_both (162 : int8)));
      U8 (solve_lift (ret_both (222 : int8)));
      U8 (solve_lift (ret_both (249 : int8)));
      U8 (solve_lift (ret_both (222 : int8)));
      U8 (solve_lift (ret_both (20 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (0 : int8)));
      U8 (solve_lift (ret_both (16 : int8)))]) : both t_SerializedScalar.
Fail Next Obligation.

Equations v_CONSTANT_P : both t_SerializedScalar :=
  v_CONSTANT_P  :=
    SerializedScalar (array_from_list [U8 (solve_lift (ret_both (237 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (127 : int8)))]) : both t_SerializedScalar.
Fail Next Obligation.

Equations v_CONSTANT_P1_4_ : both t_SerializedScalar :=
  v_CONSTANT_P1_4_  :=
    SerializedScalar (array_from_list [U8 (solve_lift (ret_both (251 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (31 : int8)))]) : both t_SerializedScalar.
Fail Next Obligation.

Equations v_CONSTANT_P3_8_ : both t_SerializedScalar :=
  v_CONSTANT_P3_8_  :=
    SerializedScalar (array_from_list [U8 (solve_lift (ret_both (254 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (255 : int8)));
      U8 (solve_lift (ret_both (15 : int8)))]) : both t_SerializedScalar.
Fail Next Obligation.

Equations check_canonical_point (x : both t_CompressedEdPoint) : both 'bool :=
  check_canonical_point x  :=
    letb x := update_at x (ret_both (31 : int32)) ((x.a[(ret_both (31 : int32))]) .& (U8 (ret_both (127 : int8)))) in
    letb x := impl__BigInteger__from_byte_seq_le x in
    solve_lift (x <.? (impl__BigInteger__from_byte_seq_le v_CONSTANT_P)) : both 'bool.
Fail Next Obligation.

Equations check_canonical_scalar (s : both t_SerializedScalar) : both 'bool :=
  check_canonical_scalar s  :=
    solve_lift (ifb (impl__U8__declassify ((s.a[(ret_both (31 : uint_size))]) .& (U8 (ret_both (224 : int8))))) <> (ret_both (0 : int8))
    then ret_both (false : 'bool)
    else (impl__BigInteger__from_byte_seq_le s) <.? (impl__BigInteger__from_byte_seq_le v_CONSTANT_L)) : both 'bool.
Fail Next Obligation.

Equations is_negative (x : both t_Ed25519FieldElement) : both t_U8 :=
  is_negative x  :=
    solve_lift (ifb impl__Ed25519FieldElement__bit x (ret_both (0 : uint_size))
    then U8 (ret_both (1 : int8))
    else U8 (ret_both (0 : int8))) : both t_U8.
Fail Next Obligation.

Equations compress (p : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) : both t_CompressedEdPoint :=
  compress p  :=
    letb '(x,y,z,_) := p in
    letb z_inv := impl__Ed25519FieldElement__inv z in
    letb x := x .* z_inv in
    letb y := y .* z_inv in
    letb (s : t_Seq t_U8) := impl__Ed25519FieldElement__to_byte_seq_le y in
    letb s := update_at s (ret_both (31 : int32)) ((s.a[(ret_both (31 : int32))]) .^ ((is_negative x) shift_left (ret_both (7 : uint_size)))) in
    solve_lift (impl__CompressedEdPoint__from_slice s (ret_both (0 : uint_size)) (ret_both (32 : uint_size))) : both t_CompressedEdPoint.
Fail Next Obligation.

Equations encode (p : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) : both (t_Seq t_U8) :=
  encode p  :=
    letb '(x,y,z,_) := p in
    letb z_inv := impl__Ed25519FieldElement__inv z in
    letb x := x .* z_inv in
    letb y := y .* z_inv in
    letb (s : t_Seq t_U8) := impl__Ed25519FieldElement__to_byte_seq_le y in
    letb s := update_at s (ret_both (31 : int32)) ((s.a[(ret_both (31 : int32))]) .^ ((is_negative x) shift_left (ret_both (7 : uint_size)))) in
    solve_lift s : both (t_Seq t_U8).
Fail Next Obligation.

Equations point_add (p : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) (q : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement) :=
  point_add p q  :=
    letb d_c := impl__Ed25519FieldElement__from_byte_seq_le v_CONSTANT_D in
    letb two := f_TWO (ret_both (tt : 'unit)) in
    letb '(x1,y1,z1,t1) := p in
    letb '(x2,y2,z2,t2) := q in
    letb a := (y1 .- x1) .* (y2 .- x2) in
    letb b := (y1 .+ x1) .* (y2 .+ x2) in
    letb c := ((t1 .* two) .* d_c) .* t2 in
    letb d := (z1 .* two) .* z2 in
    letb e := b .- a in
    letb f := d .- c in
    letb g := d .+ c in
    letb h := b .+ a in
    letb x3 := e .* f in
    letb y3 := g .* h in
    letb t3 := e .* h in
    letb z3 := f .* g in
    solve_lift (prod_b (x3,y3,z3,t3)) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement).
Fail Next Obligation.

Equations point_mul (s : both t_Scalar) (p : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement) :=
  point_mul s p  :=
    letb p := p in
    letb q := point_identity (ret_both (tt : 'unit)) in
    letb '(p,q) := f_fold (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := ret_both (256 : uint_size)))) (prod_b (p,q)) (fun '(p,q) => fun i =>
      letb q := ifb impl__Scalar__bit s i
      then letb q := point_add q p in
      q
      else q in
      letb p := point_add p p in
      prod_b (p,q)) in
    solve_lift q : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement).
Fail Next Obligation.

Equations point_mul_by_cofactor (p : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement) :=
  point_mul_by_cofactor p  :=
    letb p2 := point_add p p in
    letb p4 := point_add p2 p2 in
    solve_lift (point_add p4 p4) : both (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement).
Fail Next Obligation.

Equations secret_expand (sk : both t_SerializedScalar) : both (t_SerializedScalar × t_SerializedScalar) :=
  secret_expand sk  :=
    letb h := sha512 (impl_41__from_slice sk (ret_both (0 : uint_size)) (ret_both (32 : uint_size))) in
    letb h_d := impl__SerializedScalar__from_slice h (ret_both (32 : uint_size)) (ret_both (32 : uint_size)) in
    letb s := impl__SerializedScalar__from_slice h (ret_both (0 : uint_size)) (ret_both (32 : uint_size)) in
    letb s := update_at s (ret_both (0 : int32)) ((s.a[(ret_both (0 : int32))]) .& (U8 (ret_both (248 : int8)))) in
    letb s := update_at s (ret_both (31 : int32)) ((s.a[(ret_both (31 : int32))]) .& (U8 (ret_both (127 : int8)))) in
    letb s := update_at s (ret_both (31 : int32)) ((s.a[(ret_both (31 : int32))]) .| (U8 (ret_both (64 : int8)))) in
    solve_lift (prod_b (s,h_d)) : both (t_SerializedScalar × t_SerializedScalar).
Fail Next Obligation.

Equations sqrt (a : both t_Ed25519FieldElement) : both (t_Option t_Ed25519FieldElement) :=
  sqrt a  :=
    letb p3_8_ := impl__Ed25519FieldElement__from_byte_seq_le v_CONSTANT_P3_8_ in
    letb p1_4_ := impl__Ed25519FieldElement__from_byte_seq_le v_CONSTANT_P1_4_ in
    letb x_c := f_pow_self a p3_8_ in
    letb (result : t_Option t_Ed25519FieldElement) := Option_None in
    letb result := ifb (x_c .* x_c) =.? a
    then letb result := Option_Some x_c in
    result
    else result in
    letb result := ifb (x_c .* x_c) =.? ((f_ZERO (ret_both (tt : 'unit))) .- a)
    then letb x := (f_pow_self (f_TWO (ret_both (tt : 'unit))) p1_4_) .* x_c in
    letb result := Option_Some x in
    result
    else result in
    solve_lift result : both (t_Option t_Ed25519FieldElement).
Fail Next Obligation.

Equations decompress (q : both t_CompressedEdPoint) : both (t_Option (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) :=
  decompress q  :=
    solve_lift (run (letb d := impl__Ed25519FieldElement__from_byte_seq_le v_CONSTANT_D in
    letb x_s := ((q.a[(ret_both (31 : uint_size))]) .& (U8 (ret_both (128 : int8)))) shift_right (ret_both (7 : uint_size)) in
    letb y_s := q in
    letb y_s := update_at y_s (ret_both (31 : int32)) ((y_s.a[(ret_both (31 : int32))]) .& (U8 (ret_both (127 : int8)))) in
    letm[choice_typeMonad.option_bind_code] _ := ifb not (check_canonical_point y_s)
    then letm[choice_typeMonad.option_bind_code] _ := Option_None in
    Option_Some (ret_both (tt : 'unit))
    else Option_Some (ret_both (tt : 'unit)) in
    letb y := impl__Ed25519FieldElement__from_byte_seq_le y_s in
    letb z := f_ONE (ret_both (tt : 'unit)) in
    letb yy := y .* y in
    letb u := yy .- z in
    letb v := (d .* yy) .+ z in
    letb xx := u .* (impl__Ed25519FieldElement__inv v) in
    letm[choice_typeMonad.option_bind_code] x := sqrt xx in
    letb x_r := is_negative x in
    letm[choice_typeMonad.option_bind_code] _ := ifb andb (x =.? (f_ZERO (ret_both (tt : 'unit)))) ((impl__U8__declassify x_s) =.? (ret_both (1 : int8)))
    then letm[choice_typeMonad.option_bind_code] _ := Option_None in
    Option_Some (ret_both (tt : 'unit))
    else Option_Some (ret_both (tt : 'unit)) in
    Option_Some (letb x := ifb (impl__U8__declassify x_r) <> (impl__U8__declassify x_s)
    then letb x := (f_ZERO (ret_both (tt : 'unit))) .- x in
    x
    else x in
    Option_Some (prod_b (x,y,z,x .* y))))) : both (t_Option (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)).
Fail Next Obligation.

Equations decode (q_s : both (t_Seq t_U8)) : both (t_Option (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) :=
  decode q_s  :=
    letb q := impl__CompressedEdPoint__from_slice q_s (ret_both (0 : uint_size)) (ret_both (32 : uint_size)) in
    solve_lift (decompress q) : both (t_Option (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)).
Fail Next Obligation.

Equations decompress_non_canonical (p : both t_CompressedEdPoint) : both (t_Option (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)) :=
  decompress_non_canonical p  :=
    solve_lift (run (letb d := impl__Ed25519FieldElement__from_byte_seq_le v_CONSTANT_D in
    letb x_s := ((p.a[(ret_both (31 : uint_size))]) .& (U8 (ret_both (128 : int8)))) shift_right (ret_both (7 : uint_size)) in
    letb y_s := p in
    letb y_s := update_at y_s (ret_both (31 : int32)) ((y_s.a[(ret_both (31 : int32))]) .& (U8 (ret_both (127 : int8)))) in
    letb y := impl__Ed25519FieldElement__from_byte_seq_le y_s in
    letb z := f_ONE (ret_both (tt : 'unit)) in
    letb yy := y .* y in
    letb u := yy .- z in
    letb v := (d .* yy) .+ z in
    letb xx := u .* (impl__Ed25519FieldElement__inv v) in
    letm[choice_typeMonad.option_bind_code] x := sqrt xx in
    Option_Some (letb x_r := is_negative x in
    letb x := ifb (impl__U8__declassify x_r) <> (impl__U8__declassify x_s)
    then letb x := (f_ZERO (ret_both (tt : 'unit))) .- x in
    x
    else x in
    Option_Some (prod_b (x,y,z,x .* y))))) : both (t_Option (t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement × t_Ed25519FieldElement)).
Fail Next Obligation.

Equations secret_to_public (sk : both t_SerializedScalar) : both t_CompressedEdPoint :=
  secret_to_public sk  :=
    letb '(s,_) := secret_expand sk in
    letb base := impl__unwrap (decompress v_BASE) in
    letb ss := impl__Scalar__from_byte_seq_le s in
    letb a := point_mul ss base in
    solve_lift (compress a) : both t_CompressedEdPoint.
Fail Next Obligation.
