(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
Import choice.Choice.Exports.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.
From Hacspec Require Import ConCertLib.

From Hacspec_ovn Require Import Hacspec_ovn (t_ovn_traits).
Export Hacspec_ovn (t_ovn_traits).

From Hacspec_ovn Require Import hacspec_lib.
Export hacspec_lib.

From Hacspec_ovn Require Import hacspec_bip_340.
Export hacspec_bip_340.

Definition t_Group_curve : choice_type :=
   t_Point.Definition Build_t_Group_curve : t_Group_curve :=
  Group_curve_f_g_val.
Definition Group_curve_f_g_val (x : t_Group_curve) : t_Point :=
  x.
#[export] Instance settable_t_Group_curve : Settable _ :=
  settable! (@Build_t_Group_curve) <Group_curve_f_g_val>.

Definition t_Z_curve : choice_type :=
   t_Scalar.Definition Build_t_Z_curve : t_Z_curve :=
  Z_curve_f_z_val.
Definition Z_curve_f_z_val (x : t_Z_curve) : t_Scalar :=
  x.
#[export] Instance settable_t_Z_curve : Settable _ :=
  settable! (@Build_t_Z_curve) <Z_curve_f_z_val>.

Instance t_Deserial_57956922 : t_Deserial ((t_Z_curve)) :=
  {
    t_Deserial_impl_f_deserial := fun (source : v_R) =>
      run (let (tmp0,out) := Get_f_get (source) in
      let _ := TODO: please implement the method `lhs_LhsLocalVar` := tmp0 in
      let hoist2 := out in
      let hoist3 := Try_f_branch (hoist2) in
      let temp : t_Vec ((t_u8)) ((t_Global)) := match hoist3 with
      | ControlFlow_Break (residual) =>
        let hoist1 := ControlFlow_Break ((source,FromResidual_f_from_residual (residual))) in
        ControlFlow_Continue (never_to_any (hoist1))
      | ControlFlow_Continue (val) =>
        ControlFlow_Continue (val)
      end in
      ControlFlow_Continue (let hax_temp_output := Result_Ok (Build_t_Z_curve (impl__Scalar__from_public_byte_seq_be (impl_52__from_vec (temp)))) in
      (source,hax_temp_output)));
  }.

Instance t_Serial_79745743 : t_Serial ((t_Z_curve)) :=
  {
    t_Serial_impl_1_f_serial := fun (self : t_Z_curve) (out : v_W) =>
      let v : t_Vec ((t_u8)) ((t_Global)) := impl__new (tt) in
      let _ := {IntoIterator_f_into_iter (impl_41__native_slice (impl__Scalar__to_public_byte_seq_be (Z_curve_f_z_val self)))} inP? [x] [is_none]default of (
        TODO: please implement the method `lhs_LhsLocalVar` := impl_1__push (v) (Clone_f_clone (x))) in
      let (tmp0,out1) := Serial_f_serial (v) (out) in
      let _ := TODO: please implement the method `lhs_LhsLocalVar` := tmp0 in
      let hax_temp_output := out1 in
      (out,hax_temp_output);
  }.

Instance t_Deserial_116245855 : t_Deserial ((t_Group_curve)) :=
  {
    t_Deserial_impl_7_f_deserial := fun (source : v_R) =>
      run (let (tmp0,out) := Get_f_get (source) in
      let _ := TODO: please implement the method `lhs_LhsLocalVar` := tmp0 in
      let hoist5 := out in
      let hoist6 := Try_f_branch (hoist5) in
      let b : 'bool := match hoist6 with
      | ControlFlow_Break (residual) =>
        let hoist4 := ControlFlow_Break ((source,FromResidual_f_from_residual (residual))) in
        ControlFlow_Continue (never_to_any (hoist4))
      | ControlFlow_Continue (val) =>
        ControlFlow_Continue (val)
      end in
      let hax_temp_output := if
        b
      then
        let (tmp0,out) := Get_f_get (source) in
        let _ := TODO: please implement the method `lhs_LhsLocalVar` := tmp0 in
        let hoist8 := out in
        let hoist9 := Try_f_branch (hoist8) in
        let vx : t_Vec ((t_u8)) ((t_Global)) := match hoist9 with
        | ControlFlow_Break (residual) =>
          let hoist7 := ControlFlow_Break ((source,FromResidual_f_from_residual (residual))) in
          ControlFlow_Continue (never_to_any (hoist7))
        | ControlFlow_Continue (val) =>
          ControlFlow_Continue (val)
        end in
        let (tmp0,out) := Get_f_get (source) in
        let _ := TODO: please implement the method `lhs_LhsLocalVar` := tmp0 in
        let hoist11 := out in
        let hoist12 := Try_f_branch (hoist11) in
        let vy : t_Vec ((t_u8)) ((t_Global)) := match hoist12 with
        | ControlFlow_Break (residual) =>
          let hoist10 := ControlFlow_Break ((source,FromResidual_f_from_residual (residual))) in
          ControlFlow_Continue (never_to_any (hoist10))
        | ControlFlow_Continue (val) =>
          ControlFlow_Continue (val)
        end in
        ControlFlow_Continue (Result_Ok (Build_t_Group_curve (Point_Affine ((impl__FieldElement__from_public_byte_seq_be (impl_52__from_vec (vx)),impl__FieldElement__from_public_byte_seq_be (impl_52__from_vec (vy)))))))
      else
        ControlFlow_Continue (Result_Ok (Build_t_Group_curve (Point_AtInfinity))) in
      ControlFlow_Continue ((source,hax_temp_output)));
  }.

Instance t_Serial_210512824 : t_Serial ((t_Group_curve)) :=
  {
    t_Serial_impl_8_f_serial := fun (self : t_Group_curve) (out : v_W) =>
      run (let _ := match Group_curve_f_g_val self with
      | Point_Affine (p) =>
        let (tmp0,out1) := Serial_f_serial (true) (out) in
        let _ := TODO: please implement the method `lhs_LhsLocalVar` := tmp0 in
        let hoist14 := out1 in
        let hoist15 := Try_f_branch (hoist14) in
        let _ := match hoist15 with
        | ControlFlow_Break (residual) =>
          let hoist13 := ControlFlow_Break ((out,FromResidual_f_from_residual (residual))) in
          ControlFlow_Continue (never_to_any (hoist13))
        | ControlFlow_Continue (val) =>
          ControlFlow_Continue (val)
        end in
        let vx : t_Vec ((t_u8)) ((t_Global)) := impl__new (tt) in
        let _ := {IntoIterator_f_into_iter (impl_41__native_slice (impl__FieldElement__to_public_byte_seq_be (x (p))))} inP? [x] [is_none]default of (
          TODO: please implement the method `lhs_LhsLocalVar` := impl_1__push (vx) (Clone_f_clone (x))) in
        let (tmp0,out1) := Serial_f_serial (vx) (out) in
        let _ := TODO: please implement the method `lhs_LhsLocalVar` := tmp0 in
        let hoist17 := out1 in
        let hoist18 := Try_f_branch (hoist17) in
        let _ := match hoist18 with
        | ControlFlow_Break (residual) =>
          let hoist16 := ControlFlow_Break ((out,FromResidual_f_from_residual (residual))) in
          ControlFlow_Continue (never_to_any (hoist16))
        | ControlFlow_Continue (val) =>
          ControlFlow_Continue (val)
        end in
        let vy : t_Vec ((t_u8)) ((t_Global)) := impl__new (tt) in
        let _ := {IntoIterator_f_into_iter (impl_41__native_slice (impl__FieldElement__to_public_byte_seq_be (y (p))))} inP? [y] [is_none]default of (
          TODO: please implement the method `lhs_LhsLocalVar` := impl_1__push (vy) (Clone_f_clone (y))) in
        let (tmp0,out1) := Serial_f_serial (vy) (out) in
        let _ := TODO: please implement the method `lhs_LhsLocalVar` := tmp0 in
        let hoist20 := out1 in
        let hoist21 := Try_f_branch (hoist20) in
        let _ := match hoist21 with
        | ControlFlow_Break (residual) =>
          let hoist19 := ControlFlow_Break ((out,FromResidual_f_from_residual (residual))) in
          ControlFlow_Continue (never_to_any (hoist19))
        | ControlFlow_Continue (val) =>
          ControlFlow_Continue (val)
        end in
        ControlFlow_Continue (tt)
      | Point_AtInfinity =>
        let (tmp0,out1) := Serial_f_serial (false) (out) in
        let _ := TODO: please implement the method `lhs_LhsLocalVar` := tmp0 in
        let hoist23 := out1 in
        let hoist24 := Try_f_branch (hoist23) in
        let _ := match hoist24 with
        | ControlFlow_Break (residual) =>
          let hoist22 := ControlFlow_Break ((out,FromResidual_f_from_residual (residual))) in
          ControlFlow_Continue (never_to_any (hoist22))
        | ControlFlow_Continue (val) =>
          ControlFlow_Continue (val)
        end in
        ControlFlow_Continue (tt)
      end in
      ControlFlow_Continue (let hax_temp_output := Result_Ok (tt) in
      (out,hax_temp_output)));
  }.

Instance t_Mul_893045317 : t_Mul ((t_Z_curve)) ((t_Z_curve)) :=
  {
    t_Mul_impl_2_f_Output := t_Z_curve;
    t_Mul_impl_2_f_mul := fun (self : t_Z_curve) (y : t_Z_curve) =>
      Build_t_Z_curve (Mul_f_mul (Z_curve_f_z_val self) (Z_curve_f_z_val y));
  }.

Instance t_Product_902246531 : t_Product ((t_Z_curve)) ((t_Z_curve)) :=
  {
    t_Product_impl_3_f_product := fun (iter : v_I) =>
      Iterator_f_fold (iter) (Build_t_Z_curve (impl__Scalar__from_literal (1))) (fun a b =>
        Mul_f_mul (a) (b));
  }.

Instance t_Add_552520376 : t_Add ((t_Z_curve)) ((t_Z_curve)) :=
  {
    t_Add_impl_4_f_Output := t_Z_curve;
    t_Add_impl_4_f_add := fun (self : t_Z_curve) (y : t_Z_curve) =>
      Build_t_Z_curve (Add_f_add (Z_curve_f_z_val self) (Z_curve_f_z_val y));
  }.

Instance t_Mul_565430551 : t_Mul ((t_Group_curve)) ((t_Group_curve)) :=
  {
    t_Mul_impl_9_f_Output := t_Group_curve;
    t_Mul_impl_9_f_mul := fun (self : t_Group_curve) (y : t_Group_curve) =>
      Build_t_Group_curve (point_add (Group_curve_f_g_val self) (Group_curve_f_g_val y));
  }.

Instance t_Field_230158822 : t_Field ((t_Z_curve)) :=
  {
    t_Field_impl_6_f_q := fun (_ : unit) =>
      Build_t_Z_curve (impl__Scalar__from_hex ("0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141"%string));
    t_Field_impl_6_f_random_field_elem := fun (random : t_u32) =>
      Build_t_Z_curve (impl__Scalar__from_literal (cast (random)));
    t_Field_impl_6_f_field_zero := fun (_ : unit) =>
      Build_t_Z_curve (impl__Scalar__from_literal (0));
    t_Field_impl_6_f_field_one := fun (_ : unit) =>
      Build_t_Z_curve (impl__Scalar__from_literal (1));
    t_Field_impl_6_f_inv := fun (x : t_Z_curve) =>
      run (let _ := assert (false) in
      let hoist29 := ControlFlow_Break (x) in
      ControlFlow_Continue (never_to_any (hoist29)));
  }.

Instance t_Neg_848153603 : t_Neg ((t_Z_curve)) :=
  {
    t_Neg_impl_5_f_Output := t_Z_curve;
    t_Neg_impl_5_f_neg := fun (self : t_Z_curve) =>
      Build_t_Z_curve (Sub_f_sub (Z_curve_f_z_val Field_f_field_zero (tt)) (Z_curve_f_z_val self));
  }.

Instance t_Product_307260739 : t_Product ((t_Group_curve)) ((t_Group_curve)) :=
  {
    t_Product_impl_10_f_product := fun (iter : v_I) =>
      Iterator_f_fold (iter) (Group_f_g_pow (Field_f_field_zero (tt))) (fun a b =>
        Mul_f_mul (a) (b));
  }.

Instance t_Group_947705802 : t_Group ((t_Group_curve)) :=
  {
    t_Group_impl_11_f_Z := t_Z_curve;
    t_Group_impl_11_f_g := fun (_ : unit) =>
      let gx := Build_t_PBytes32 ([121; 190; 102; 126; 249; 220; 187; 172; 85; 160; 98; 149; 206; 135; 11; 7; 2; 155; 252; 219; 45; 206; 40; 217; 89; 242; 129; 91; 22; 248; 23; 152]) in
      let gy := Build_t_PBytes32 ([72; 58; 218; 119; 38; 163; 196; 101; 93; 164; 251; 252; 14; 17; 8; 168; 253; 23; 180; 72; 166; 133; 84; 25; 156; 71; 208; 143; 251; 16; 212; 184]) in
      Build_t_Group_curve (Point_Affine ((impl__FieldElement__from_public_byte_seq_be (gx),impl__FieldElement__from_public_byte_seq_be (gy))));
    t_Group_impl_11_f_pow := fun (g : t_Group_curve) (x : t_Z_curve) =>
      Build_t_Group_curve (point_mul (Z_curve_f_z_val x) (Group_curve_f_g_val g));
    t_Group_impl_11_f_g_pow := fun (x : t_Z_curve) =>
      Build_t_Group_curve (point_mul_base (Z_curve_f_z_val x));
    t_Group_impl_11_f_group_one := fun (_ : unit) =>
      Group_f_g_pow (Field_f_field_zero (tt));
    t_Group_impl_11_f_group_inv := fun (x : t_Group_curve) =>
      Build_t_Group_curve (match Group_curve_f_g_val x with
      | Point_Affine ((a,b)) =>
        Point_Affine ((a,Sub_f_sub (impl__FieldElement__from_literal (0)) (b)))
      | Point_AtInfinity =>
        Point_AtInfinity
      end);
    t_Group_impl_11_f_hash := fun (x : t_Vec ((t_Group_curve)) ((t_Global))) =>
      Field_f_field_one (tt);
  }.
