(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
Import choice.Choice.Exports.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.
From Hacspec Require Import ConCertLib.

Class t_Field `{v_Self : choice_type} : Type :=
  {
    Field_f_q : unit -> v_Self;
    Field_f_random_field_elem : t_u32 -> v_Self;
    Field_f_field_zero : unit -> v_Self;
    Field_f_field_one : unit -> v_Self;
    Field_f_inv : v_Self -> v_Self;
    H11581440318597584651 : t_Copy (v_Self);
    H12632649257025169145 : t_PartialEq (v_Self) (v_Self);
    H8099741844003281729 : t_Eq (v_Self);
    H9442900250278684536 : t_Clone (v_Self);
    H17605656595743636193 : t_Serialize (v_Self);
    H12091683018502772129 : t_Mul (v_Self) (v_Self);
    _.(Mul_f_Output) = v_Self;
    H8449417958832886617 : t_Product (v_Self) (v_Self);
    H9509749083603562901 : t_Add (v_Self) (v_Self);
    _.(Add_f_Output) = v_Self;
    H7732034498048571850 : t_Neg (v_Self);
    _.(Neg_f_Output) = v_Self;
  }..

Class t_Group `{v_Self : choice_type} : Type :=
  {
    Group_f_Z : choice_type;
    Hi0 : t_Field (Group_f_Z);
    _ : _.(Neg_f_Output) = Group_f_Z;
    Hi1 : t_Neg (Group_f_Z);
    _ : _.(Add_f_Output) = Group_f_Z;
    Hi2 : t_Add (Group_f_Z) (Group_f_Z);
    Hi3 : t_Product (Group_f_Z) (Group_f_Z);
    _ : _.(Mul_f_Output) = Group_f_Z;
    Hi4 : t_Mul (Group_f_Z) (Group_f_Z);
    Hi5 : t_Serialize (Group_f_Z);
    Hi6 : t_Deserial (Group_f_Z);
    Hi7 : t_Serial (Group_f_Z);
    Hi8 : t_Clone (Group_f_Z);
    Hi9 : t_Eq (Group_f_Z);
    Hi10 : t_PartialEq (Group_f_Z) (Group_f_Z);
    Hi11 : t_Copy (Group_f_Z);
    Hi12 : t_Sized (Group_f_Z);
    Group_f_g : unit -> v_Self;
    Group_f_g_pow : Group_f_Z -> v_Self;
    Group_f_pow : v_Self -> Group_f_Z -> v_Self;
    Group_f_group_one : unit -> v_Self;
    Group_f_group_inv : v_Self -> v_Self;
    Group_f_hash : t_Vec ((v_Self)) ((t_Global)) -> Group_f_Z;
    H11581440318597584651 : t_Copy (v_Self);
    H12632649257025169145 : t_PartialEq (v_Self) (v_Self);
    H8099741844003281729 : t_Eq (v_Self);
    H9442900250278684536 : t_Clone (v_Self);
    H17605656595743636193 : t_Serialize (v_Self);
    H12091683018502772129 : t_Mul (v_Self) (v_Self);
    _.(Mul_f_Output) = v_Self;
    H8449417958832886617 : t_Product (v_Self) (v_Self);
  }..
