(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
Import choice.Choice.Exports.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.
From Hacspec Require Import ConCertLib.

From Hacspec_ovn Require Import Hacspec_ovn (t_ovn_traits).
Export Hacspec_ovn (t_ovn_traits).

Definition t_g_z_89_ : choice_type :=
   t_u8.Definition Build_t_g_z_89_ : t_g_z_89_ :=
  g_z_89__f_g_val.
Definition g_z_89__f_g_val (x : t_g_z_89_) : t_u8 :=
  x.
#[export] Instance settable_t_g_z_89_ : Settable _ :=
  settable! (@Build_t_g_z_89_) <g_z_89__f_g_val>.

Definition t_z_89_ : choice_type :=
   t_u8.Definition Build_t_z_89_ : t_z_89_ :=
  z_89__f_z_val.
Definition z_89__f_z_val (x : t_z_89_) : t_u8 :=
  x.
#[export] Instance settable_t_z_89_ : Settable _ :=
  settable! (@Build_t_z_89_) <z_89__f_z_val>.

Instance t_Product_516576874 : t_Product ((t_z_89_)) ((t_z_89_)) :=
  {
    t_Product_impl_1_f_product := fun (iter : v_I) =>
      Iterator_f_fold (iter) (Build_t_C_z_89_ (1)) (fun a b =>
        Mul_f_mul (a) (b));
  }.

Instance t_Product_550947082 : t_Product ((t_g_z_89_)) ((t_g_z_89_)) :=
  {
    t_Product_impl_6_f_product := fun (iter : v_I) =>
      Iterator_f_fold (iter) (Build_t_C_g_z_89_ (1)) (fun a b =>
        Mul_f_mul (a) (b));
  }.

Instance t_Mul_1006909152 : t_Mul ((t_z_89_)) ((t_z_89_)) :=
  {
    t_Mul_impl_f_Output := t_z_89_;
    t_Mul_impl_f_mul := fun (self : t_z_89_) (y : t_z_89_) =>
      let q___ := sub (z_89__f_z_val Field_f_q (tt)) (1) in
      let x___ : t_u16 := cast (t_Rem_f_rem (z_89__f_z_val self) (q___)) in
      let y___ : t_u16 := cast (t_Rem_f_rem (z_89__f_z_val y) (q___)) in
      Build_t_C_z_89_ (cast (t_Rem_f_rem (t_Mul_f_mul (x___) (y___)) (cast (q___))));
  }.

Instance t_Add_753400148 : t_Add ((t_z_89_)) ((t_z_89_)) :=
  {
    t_Add_impl_2_f_Output := t_z_89_;
    t_Add_impl_2_f_add := fun (self : t_z_89_) (y : t_z_89_) =>
      let q___ := sub (z_89__f_z_val Field_f_q (tt)) (1) in
      let x___ := t_Rem_f_rem (z_89__f_z_val self) (q___) in
      let y___ := t_Rem_f_rem (z_89__f_z_val y) (q___) in
      Build_t_C_z_89_ (t_Rem_f_rem (t_Add_f_add (x___) (y___)) (q___));
  }.

Instance t_Neg_486327576 : t_Neg ((t_z_89_)) :=
  {
    t_Neg_impl_3_f_Output := t_z_89_;
    t_Neg_impl_3_f_neg := fun (self : t_z_89_) =>
      let q___ := sub (z_89__f_z_val Field_f_q (tt)) (1) in
      let x___ := t_Rem_f_rem (z_89__f_z_val self) (q___) in
      Build_t_C_z_89_ (sub (q___) (x___));
  }.

Instance t_Field_519153209 : t_Field ((t_z_89_)) :=
  {
    t_Field_impl_4_f_q := fun (_ : unit) =>
      Build_t_C_z_89_ (89);
    t_Field_impl_4_f_random_field_elem := fun (random : t_u32) =>
      Build_t_C_z_89_ (t_Rem_f_rem (cast (random)) (sub (z_89__f_z_val Field_f_q (tt)) (1)));
    t_Field_impl_4_f_field_zero := fun (_ : unit) =>
      Build_t_C_z_89_ (0);
    t_Field_impl_4_f_field_one := fun (_ : unit) =>
      Build_t_C_z_89_ (1);
    t_Field_impl_4_f_inv := fun (x : t_z_89_) =>
      run (let _ := assert (false) in
      let hoist30 := ControlFlow_Break (x) in
      ControlFlow_Continue (never_to_any (hoist30)));
  }.

Instance t_Mul_509828028 : t_Mul ((t_g_z_89_)) ((t_g_z_89_)) :=
  {
    t_Mul_impl_5_f_Output := t_g_z_89_;
    t_Mul_impl_5_f_mul := fun (self : t_g_z_89_) (y : t_g_z_89_) =>
      let q___ := z_89__f_z_val Field_f_q (tt) in
      let x___ := cast (t_Rem_f_rem (g_z_89__f_g_val self) (q___)) in
      let y___ := cast (t_Rem_f_rem (g_z_89__f_g_val y) (q___)) in
      Build_t_C_g_z_89_ (cast (t_Rem_f_rem (t_Mul_f_mul (x___) (y___)) (cast (q___))));
  }.

Instance t_Group_794386426 : t_Group ((t_g_z_89_)) :=
  {
    t_Group_impl_7_f_Z := t_z_89_;
    t_Group_impl_7_f_g := fun (_ : unit) =>
      Build_t_C_g_z_89_ (3);
    t_Group_impl_7_f_hash := fun (x : t_Vec ((t_g_z_89_)) ((t_Global))) =>
      let res := Field_f_field_one (tt) in
      let _ := {IntoIterator_f_into_iter (x)} inP? [y] [is_none]default of (
        TODO: please implement the method `lhs_LhsLocalVar` := Mul_f_mul (Build_t_C_z_89_ (g_z_89__f_g_val y)) (res)) in
      res;
    t_Group_impl_7_f_g_pow := fun (x : t_z_89_) =>
      Group_f_pow (Group_f_g (tt)) (x);
    t_Group_impl_7_f_pow := fun (g : t_g_z_89_) (x : t_z_89_) =>
      let result := Group_f_group_one (tt) in
      let _ := {IntoIterator_f_into_iter (Build_t_Range (0, t_Rem_f_rem (z_89__f_z_val x) (sub (z_89__f_z_val Field_f_q (tt)) (1))))} inP? [_] [is_none]default of (
        TODO: please implement the method `lhs_LhsLocalVar` := Mul_f_mul (result) (g)) in
      result;
    t_Group_impl_7_f_group_one := fun (_ : unit) =>
      Build_t_C_g_z_89_ (1);
    t_Group_impl_7_f_group_inv := fun (x : t_g_z_89_) =>
      run (let _ := {IntoIterator_f_into_iter (Build_t_Range (0, 89))} inP? [j] [is_none]default of (
        let g_value := Build_t_C_g_z_89_ (j) in
        if
          PartialEq_f_eq (Mul_f_mul (x) (g_value)) (Group_f_group_one (tt))
        then
          let hoist31 := ControlFlow_Break (g_value) in
          ControlFlow_Continue (never_to_any (hoist31))
        else
          tt) in
      let _ := assert (false) in
      let hoist32 := ControlFlow_Break (x) in
      ControlFlow_Continue (never_to_any (hoist32)));
  }.
