(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
Import choice.Choice.Exports.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.
From Hacspec Require Import ConCertLib.



(** settable! creates an instance of Settable from a constructor and list of
fields. *)
Local Ltac eta_choice_prod x :=
  (reflexivity ||
     destruct x ;
   repeat
     match goal with
     | H : choice.Choice.sort (chElement (_ × _)) |- _ => destruct H
     end
   ; reflexivity).
Notation "'settable!' mk < f1 ; .. ; fn >" :=
  (Build_Settable
     (fun x => .. (mk (f1 x)) .. (fn x))
     (fun x => _)) (at level 0, mk at level 10, f1, fn at level 9, only parsing).

From Hacspec_ovn Require Import Hacspec_ovn_Ovn_traits.
Export Hacspec_ovn_Ovn_traits.

Definition t_TallyParameter : choice_type :=
  'unit.
Definition Build_t_TallyParameter : t_TallyParameter := tt.

Definition t_CastVoteParam `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} : choice_type :=
  int32 ×  v_Z ×  v_Z ×  v_Z ×  v_Z ×  'bool.
Definition Build_t_CastVoteParam `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} CastVoteParam_f_cvp_i CastVoteParam_f_cvp_xi CastVoteParam_f_cvp_zkp_random_w CastVoteParam_f_cvp_zkp_random_r CastVoteParam_f_cvp_zkp_random_d CastVoteParam_f_cvp_vote : t_CastVoteParam :=
  (CastVoteParam_f_cvp_i, CastVoteParam_f_cvp_xi,CastVoteParam_f_cvp_zkp_random_w,CastVoteParam_f_cvp_zkp_random_r, CastVoteParam_f_cvp_zkp_random_d, CastVoteParam_f_cvp_vote).
Definition CastVoteParam_f_cvp_i `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : t_CastVoteParam) :32 :=
  fst(fst(fst(fst(fst(x))))).
Definition CastVoteParam_f_cvp_xi `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : t_CastVoteParam) : v_Z :=
  snd(fst(fst(fst(fst(x))))).
Definition CastVoteParam_f_cvp_zkp_random_w `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : t_CastVoteParam) : v_Z :=
  snd(fst(fst(fst(x)))).
Definition CastVoteParam_f_cvp_zkp_random_r `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : t_CastVoteParam) : v_Z :=
  snd(fst(fst(x))).
Definition CastVoteParam_f_cvp_zkp_random_d `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : t_CastVoteParam) : v_Z :=
  snd(fst(x)).
Definition CastVoteParam_f_cvp_vote `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : t_CastVoteParam) : 'bool :=
  snd(x).
#[export] Instance settable_t_CastVoteParam `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} : Settable _ :=
  settable! (@Build_t_CastVoteParam `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)}) <CastVoteParam_f_cvp_i; CastVoteParam_f_cvp_xi; CastVoteParam_f_cvp_zkp_random_w; CastVoteParam_f_cvp_zkp_random_r; CastVoteParam_f_cvp_zkp_random_d; CastVoteParam_f_cvp_vote>.

Definition t_RegisterParam `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} : choice_type :=
   t_u32 ×  v_Z ×  v_Z.Definition Build_t_RegisterParam `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} : t_RegisterParam :=
  RegisterParam_f_rp_iRegisterParam_f_rp_xiRegisterParam_f_rp_zkp_random.
Definition RegisterParam_f_rp_i `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : t_RegisterParam) : t_u32 :=
  fst(fst(x)).
Definition RegisterParam_f_rp_xi `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : t_RegisterParam) : v_Z :=
  snd(fst(x)).
Definition RegisterParam_f_rp_zkp_random `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : t_RegisterParam) : v_Z :=
  snd(x).
#[export] Instance settable_t_RegisterParam `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} : Settable _ :=
  settable! (@Build_t_RegisterParam `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)}) <RegisterParam_f_rp_i; RegisterParam_f_rp_xi; RegisterParam_f_rp_zkp_random>.

Definition sub `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : v_Z) (y : v_Z) : v_Z :=
  Add_f_add (x) (Neg_f_neg (y)).

Lemma addC `{v_Z : choice_type} `{Hi0 : t_Sized (v_Z)} `{Hi1 : t_Field (v_Z)} (x : v_Z) (y : v_Z) :
  true = true ->
  implies (PartialEq_f_ne (x) (Field_f_field_zero (tt))) (fun _ =>
    PartialEq_f_eq (Add_f_add (x) (y)) (Add_f_add (y) (x))) = true.
Proof. Admitted.

Definition t_OrZKPCommit `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} : choice_type :=
   v_G ×  v_G ×  v_G ×  v_G ×  v_G ×  v_G ×  Group_f_Z ×  Group_f_Z ×  Group_f_Z ×  Group_f_Z ×  Group_f_Z.Definition Build_t_OrZKPCommit `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} : t_OrZKPCommit :=
  OrZKPCommit_f_or_zkp_xOrZKPCommit_f_or_zkp_yOrZKPCommit_f_or_zkp_a1OrZKPCommit_f_or_zkp_b1OrZKPCommit_f_or_zkp_a2OrZKPCommit_f_or_zkp_b2OrZKPCommit_f_or_zkp_cOrZKPCommit_f_or_zkp_d1OrZKPCommit_f_or_zkp_d2OrZKPCommit_f_or_zkp_r1OrZKPCommit_f_or_zkp_r2.
Definition OrZKPCommit_f_or_zkp_x `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : v_G :=
  fst(fst(fst(fst(fst(fst(fst(fst(fst(fst(x)))))))))).
Definition OrZKPCommit_f_or_zkp_y `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : v_G :=
  snd(fst(fst(fst(fst(fst(fst(fst(fst(fst(x)))))))))).
Definition OrZKPCommit_f_or_zkp_a1 `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : v_G :=
  snd(fst(fst(fst(fst(fst(fst(fst(fst(x))))))))).
Definition OrZKPCommit_f_or_zkp_b1 `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : v_G :=
  snd(fst(fst(fst(fst(fst(fst(fst(x)))))))).
Definition OrZKPCommit_f_or_zkp_a2 `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : v_G :=
  snd(fst(fst(fst(fst(fst(fst(x))))))).
Definition OrZKPCommit_f_or_zkp_b2 `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : v_G :=
  snd(fst(fst(fst(fst(fst(x)))))).
Definition OrZKPCommit_f_or_zkp_c `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : Group_f_Z :=
  snd(fst(fst(fst(fst(x))))).
Definition OrZKPCommit_f_or_zkp_d1 `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : Group_f_Z :=
  snd(fst(fst(fst(x)))).
Definition OrZKPCommit_f_or_zkp_d2 `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : Group_f_Z :=
  snd(fst(fst(x))).
Definition OrZKPCommit_f_or_zkp_r1 `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : Group_f_Z :=
  snd(fst(x)).
Definition OrZKPCommit_f_or_zkp_r2 `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OrZKPCommit) : Group_f_Z :=
  snd(x).
#[export] Instance settable_t_OrZKPCommit `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} : Settable _ :=
  settable! (@Build_t_OrZKPCommit `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)}) <OrZKPCommit_f_or_zkp_x; OrZKPCommit_f_or_zkp_y; OrZKPCommit_f_or_zkp_a1; OrZKPCommit_f_or_zkp_b1; OrZKPCommit_f_or_zkp_a2; OrZKPCommit_f_or_zkp_b2; OrZKPCommit_f_or_zkp_c; OrZKPCommit_f_or_zkp_d1; OrZKPCommit_f_or_zkp_d2; OrZKPCommit_f_or_zkp_r1; OrZKPCommit_f_or_zkp_r2>.

Definition t_SchnorrZKPCommit `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} : choice_type :=
   v_G ×  Group_f_Z ×  Group_f_Z.Definition Build_t_SchnorrZKPCommit `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} : t_SchnorrZKPCommit :=
  SchnorrZKPCommit_f_schnorr_zkp_uSchnorrZKPCommit_f_schnorr_zkp_cSchnorrZKPCommit_f_schnorr_zkp_z.
Definition SchnorrZKPCommit_f_schnorr_zkp_u `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_SchnorrZKPCommit) : v_G :=
  fst(fst(x)).
Definition SchnorrZKPCommit_f_schnorr_zkp_c `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_SchnorrZKPCommit) : Group_f_Z :=
  snd(fst(x)).
Definition SchnorrZKPCommit_f_schnorr_zkp_z `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_SchnorrZKPCommit) : Group_f_Z :=
  snd(x).
#[export] Instance settable_t_SchnorrZKPCommit `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} : Settable _ :=
  settable! (@Build_t_SchnorrZKPCommit `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)}) <SchnorrZKPCommit_f_schnorr_zkp_u; SchnorrZKPCommit_f_schnorr_zkp_c; SchnorrZKPCommit_f_schnorr_zkp_z>.

Definition t_OvnContractState `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} : choice_type :=
   t_Array (v_G) (n) ×  t_Array (t_SchnorrZKPCommit ((v_G))) (n) ×  t_Array (Group_f_Z) (n) ×  t_Array (v_G) (n) ×  t_Array (t_OrZKPCommit ((v_G))) (n) ×  t_u32 ×  t_Array ('bool) (n).Definition Build_t_OvnContractState `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} : t_OvnContractState :=
  OvnContractState_f_g_pow_xisOvnContractState_f_zkp_xisOvnContractState_f_commit_visOvnContractState_f_g_pow_xi_yi_visOvnContractState_f_zkp_visOvnContractState_f_tallyOvnContractState_f_round1.
Definition OvnContractState_f_g_pow_xis `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OvnContractState) : t_Array (v_G) (n) :=
  fst(fst(fst(fst(fst(fst(x)))))).
Definition OvnContractState_f_zkp_xis `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OvnContractState) : t_Array (t_SchnorrZKPCommit ((v_G))) (n) :=
  snd(fst(fst(fst(fst(fst(x)))))).
Definition OvnContractState_f_commit_vis `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OvnContractState) : t_Array (Group_f_Z) (n) :=
  snd(fst(fst(fst(fst(x))))).
Definition OvnContractState_f_g_pow_xi_yi_vis `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OvnContractState) : t_Array (v_G) (n) :=
  snd(fst(fst(fst(x)))).
Definition OvnContractState_f_zkp_vis `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OvnContractState) : t_Array (t_OrZKPCommit ((v_G))) (n) :=
  snd(fst(fst(x))).
Definition OvnContractState_f_tally `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OvnContractState) : t_u32 :=
  snd(fst(x)).
Definition OvnContractState_f_round1 `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : t_OvnContractState) : t_Array ('bool) (n) :=
  snd(x).
#[export] Instance settable_t_OvnContractState `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} : Settable _ :=
  settable! (@Build_t_OvnContractState `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)}) <OvnContractState_f_g_pow_xis; OvnContractState_f_zkp_xis; OvnContractState_f_commit_vis; OvnContractState_f_g_pow_xi_yi_vis; OvnContractState_f_zkp_vis; OvnContractState_f_tally; OvnContractState_f_round1>.

Definition check_commitment `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (g_pow_xi_yi_vi : v_G) (commitment : Group_f_Z) : 'bool :=
  PartialEq_f_eq (Group_f_hash (impl__into_vec (unsize (box_new ([g_pow_xi_yi_vi]))))) (commitment).

Definition commit_to `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (g_pow_xi_yi_vi : v_G) : Group_f_Z :=
  Group_f_hash (impl__into_vec (unsize (box_new ([g_pow_xi_yi_vi])))).

Definition compute_group_element_for_vote `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (xi : Group_f_Z) (vote : 'bool) (g_pow_yi : v_G) : v_G :=
  Mul_f_mul (Group_f_pow (g_pow_yi) (xi)) (Group_f_g_pow (if
    vote
  then
    Field_f_field_one (tt)
  else
    Field_f_field_zero (tt))).

Definition t_Div_f_div `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (x : v_G) (y : v_G) : v_G :=
  Mul_f_mul (x) (Group_f_group_inv (y)).

Definition compute_g_pow_yi `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (i : t_usize) (xis : t_Array (v_G) (n)) : v_G :=
  let prod1 := Iterator_f_product (Iterator_f_map (impl__iter (Index_f_index (xis) (Build_t_Range (0, i)))) (fun x =>
    Clone_f_clone (x))) in
  let prod2 := Iterator_f_product (Iterator_f_map (impl__iter (Index_f_index (xis) (Build_t_Range (t_Add_f_add (i) (1), n)))) (fun x =>
    Clone_f_clone (x))) in
  t_Div_f_div (prod1) (prod2).

Definition init_ovn_contract `{v_G : choice_type} `{n : t_usize} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (_ : unit) : t_Result ((t_OvnContractState ((v_G)) (n))) ((t_Reject)) :=
  Result_Ok (Build_t_OvnContractState (repeat (Group_f_group_one (tt)) (n), repeat (Build_t_SchnorrZKPCommit (Group_f_group_one (tt), Field_f_field_zero (tt), Field_f_field_zero (tt))) (n), repeat (Field_f_field_zero (tt)) (n), repeat (Group_f_group_one (tt)) (n), repeat (Build_t_OrZKPCommit (Group_f_group_one (tt), Group_f_group_one (tt), Group_f_group_one (tt), Group_f_group_one (tt), Group_f_group_one (tt), Group_f_group_one (tt), Field_f_field_zero (tt), Field_f_field_zero (tt), Field_f_field_zero (tt), Field_f_field_zero (tt), Field_f_field_zero (tt))) (n), 0, repeat (false) (n))).

Definition schnorr_zkp `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (random : Group_f_Z) (h : v_G) (x : Group_f_Z) : t_SchnorrZKPCommit ((v_G)) :=
  run (let r := random in
  let u := Group_f_g_pow (r) in
  let c := Group_f_hash (impl__into_vec (unsize (box_new ([Group_f_g (tt); h; u])))) in
  let z := Add_f_add (r) (Mul_f_mul (c) (x)) in
  let hoist25 := ControlFlow_Break (Build_t_SchnorrZKPCommit (u, c, z)) in
  ControlFlow_Continue (never_to_any (hoist25))).

Definition register_vote `{v_G : choice_type} `{n : t_usize} `{v_A : choice_type} `{impl_205173520_ : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Sized (v_A)} `{Hi2 : t_Sized (impl_205173520_)} `{Hi3 : t_Group (v_G)} `{Hi4 : t_HasActions (v_A)} `{Hi5 : t_HasReceiveContext (impl_205173520_) (unit)} (ctx : impl_205173520_) (state : t_OvnContractState ((v_G)) (n)) : t_Result (((v_A*t_OvnContractState ((v_G)) (n)))) ((t_ParseError)) :=
  run (let (_,out) := Get_f_get (HasCommonData_f_parameter_cursor (ctx)) in
  let params : t_RegisterParam ((Group_f_Z)) := out in
  Result_Ok (let g_pow_xi := Group_f_g_pow (RegisterParam_f_rp_xi params) in
  let zkp_xi := schnorr_zkp (RegisterParam_f_rp_zkp_random params) (g_pow_xi) (RegisterParam_f_rp_xi params) in
  let register_vote_state_ret := Clone_f_clone (state) in
  let _ := TODO: please implement the method `lhs_LhsLocalVar` := Build_register_vote_state_ret (update_at_usize (OvnContractState_f_g_pow_xis register_vote_state_ret) (cast (RegisterParam_f_rp_i params)) (g_pow_xi)) in
  let _ := TODO: please implement the method `lhs_LhsLocalVar` := Build_register_vote_state_ret (update_at_usize (OvnContractState_f_zkp_xis register_vote_state_ret) (cast (RegisterParam_f_rp_i params)) (zkp_xi)) in
  let _ := TODO: please implement the method `lhs_LhsLocalVar` := Build_register_vote_state_ret (update_at_usize (OvnContractState_f_round1 register_vote_state_ret) (cast (RegisterParam_f_rp_i params)) (true)) in
  Result_Ok ((HasActions_f_accept (tt),register_vote_state_ret)))).

Definition schnorr_zkp_validate `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (h : v_G) (pi : t_SchnorrZKPCommit ((v_G))) : 'bool :=
  andb (PartialEq_f_eq (SchnorrZKPCommit_f_schnorr_zkp_c pi) (Group_f_hash (impl__into_vec (unsize (box_new ([Group_f_g (tt); h; SchnorrZKPCommit_f_schnorr_zkp_u pi])))))) (PartialEq_f_eq (Group_f_g_pow (SchnorrZKPCommit_f_schnorr_zkp_z pi)) (Mul_f_mul (SchnorrZKPCommit_f_schnorr_zkp_u pi) (Group_f_pow (h) (SchnorrZKPCommit_f_schnorr_zkp_c pi)))).

Definition commit_to_vote `{v_G : choice_type} `{n : t_usize} `{v_A : choice_type} `{impl_205173520_ : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Sized (v_A)} `{Hi2 : t_Sized (impl_205173520_)} `{Hi3 : t_Group (v_G)} `{Hi4 : t_HasActions (v_A)} `{Hi5 : t_HasReceiveContext (impl_205173520_) (unit)} (ctx : impl_205173520_) (state : t_OvnContractState ((v_G)) (n)) : t_Result (((v_A*t_OvnContractState ((v_G)) (n)))) ((t_ParseError)) :=
  run (let (_,out) := Get_f_get (HasCommonData_f_parameter_cursor (ctx)) in
  let params : t_CastVoteParam ((Group_f_Z)) := out in
  Result_Ok (let _ := {IntoIterator_f_into_iter (Build_t_Range (0, n))} inP? [i] [is_none]default of (
    if
      orb (negb (schnorr_zkp_validate (index (OvnContractState_f_g_pow_xis state) (i)) (index (OvnContractState_f_zkp_xis state) (i)))) (negb (index (OvnContractState_f_round1 state) (i)))
    then
      let hoist26 := ControlFlow_Break (Result_Err (Build_t_ParseError)) in
      ControlFlow_Continue (never_to_any (hoist26))
    else
      tt) in
  let g_pow_yi := compute_g_pow_yi (cast (CastVoteParam_f_cvp_i params)) (OvnContractState_f_g_pow_xis state) in
  let g_pow_xi_yi_vi := compute_group_element_for_vote (CastVoteParam_f_cvp_xi params) (CastVoteParam_f_cvp_vote params) (g_pow_yi) in
  let commit_vi := commit_to (g_pow_xi_yi_vi) in
  let commit_to_vote_state_ret := Clone_f_clone (state) in
  let _ := TODO: please implement the method `lhs_LhsLocalVar` := Build_commit_to_vote_state_ret (update_at_usize (OvnContractState_f_commit_vis commit_to_vote_state_ret) (cast (CastVoteParam_f_cvp_i params)) (commit_vi)) in
  Result_Ok ((HasActions_f_accept (tt),commit_to_vote_state_ret)))).

Definition zkp_one_out_of_two `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (random_w : Group_f_Z) (random_r : Group_f_Z) (random_d : Group_f_Z) (h : v_G) (xi : Group_f_Z) (vi : 'bool) : t_OrZKPCommit ((v_G)) :=
  let w := random_w in
  if
    vi
  then
    let r1 := random_r in
    let d1 := random_d in
    let x := Group_f_g_pow (xi) in
    let y := Mul_f_mul (Group_f_pow (h) (xi)) (Group_f_g (tt)) in
    let a1 := Mul_f_mul (Group_f_g_pow (r1)) (Group_f_pow (x) (d1)) in
    let b1 := Mul_f_mul (Group_f_pow (h) (r1)) (Group_f_pow (y) (d1)) in
    let a2 := Group_f_g_pow (w) in
    let b2 := Group_f_pow (h) (w) in
    let c := Group_f_hash (impl__into_vec (unsize (box_new ([x; y; a1; b1; a2; b2])))) in
    let d2 := sub (c) (d1) in
    let r2 := sub (w) (Mul_f_mul (xi) (d2)) in
    Build_t_OrZKPCommit (x, y, a1, b1, a2, b2, c, d1, d2, r1, r2)
  else
    let r2 := random_r in
    let d2 := random_d in
    let x := Group_f_g_pow (xi) in
    let y := Group_f_pow (h) (xi) in
    let a1 := Group_f_g_pow (w) in
    let b1 := Group_f_pow (h) (w) in
    let a2 := Mul_f_mul (Group_f_g_pow (r2)) (Group_f_pow (x) (d2)) in
    let b2 := Mul_f_mul (Group_f_pow (h) (r2)) (Group_f_pow (t_Div_f_div (y) (Group_f_g (tt))) (d2)) in
    let c := Group_f_hash (impl__into_vec (unsize (box_new ([x; y; a1; b1; a2; b2])))) in
    let d1 := sub (c) (d2) in
    let r1 := sub (w) (Mul_f_mul (xi) (d1)) in
    Build_t_OrZKPCommit (x, y, a1, b1, a2, b2, c, d1, d2, r1, r2).

Definition cast_vote `{v_G : choice_type} `{n : t_usize} `{v_A : choice_type} `{impl_205173520_ : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Sized (v_A)} `{Hi2 : t_Sized (impl_205173520_)} `{Hi3 : t_Group (v_G)} `{Hi4 : t_HasActions (v_A)} `{Hi5 : t_HasReceiveContext (impl_205173520_) (unit)} (ctx : impl_205173520_) (state : t_OvnContractState ((v_G)) (n)) : t_Result (((v_A*t_OvnContractState ((v_G)) (n)))) ((t_ParseError)) :=
  run (let (_,out) := Get_f_get (HasCommonData_f_parameter_cursor (ctx)) in
  let params : t_CastVoteParam ((Group_f_Z)) := out in
  Result_Ok (let g_pow_yi := compute_g_pow_yi (cast (CastVoteParam_f_cvp_i params)) (OvnContractState_f_g_pow_xis state) in
  let g_pow_xi_yi_vi := compute_group_element_for_vote (CastVoteParam_f_cvp_xi params) (CastVoteParam_f_cvp_vote params) (g_pow_yi) in
  let zkp_vi := zkp_one_out_of_two (CastVoteParam_f_cvp_zkp_random_w params) (CastVoteParam_f_cvp_zkp_random_r params) (CastVoteParam_f_cvp_zkp_random_d params) (g_pow_yi) (CastVoteParam_f_cvp_xi params) (CastVoteParam_f_cvp_vote params) in
  let cast_vote_state_ret := Clone_f_clone (state) in
  let _ := TODO: please implement the method `lhs_LhsLocalVar` := Build_cast_vote_state_ret (update_at_usize (OvnContractState_f_g_pow_xi_yi_vis cast_vote_state_ret) (cast (CastVoteParam_f_cvp_i params)) (g_pow_xi_yi_vi)) in
  let _ := TODO: please implement the method `lhs_LhsLocalVar` := Build_cast_vote_state_ret (update_at_usize (OvnContractState_f_zkp_vis cast_vote_state_ret) (cast (CastVoteParam_f_cvp_i params)) (zkp_vi)) in
  Result_Ok ((HasActions_f_accept (tt),cast_vote_state_ret)))).

Definition zkp_one_out_of_two_validate `{v_G : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Group (v_G)} (h : v_G) (zkp : t_OrZKPCommit ((v_G))) : 'bool :=
  let c := Group_f_hash (impl__into_vec (unsize (box_new ([OrZKPCommit_f_or_zkp_x zkp; OrZKPCommit_f_or_zkp_y zkp; OrZKPCommit_f_or_zkp_a1 zkp; OrZKPCommit_f_or_zkp_b1 zkp; OrZKPCommit_f_or_zkp_a2 zkp; OrZKPCommit_f_or_zkp_b2 zkp])))) in
  andb (andb (andb (andb (PartialEq_f_eq (c) (Add_f_add (OrZKPCommit_f_or_zkp_d1 zkp) (OrZKPCommit_f_or_zkp_d2 zkp))) (PartialEq_f_eq (OrZKPCommit_f_or_zkp_a1 zkp) (Mul_f_mul (Group_f_g_pow (OrZKPCommit_f_or_zkp_r1 zkp)) (Group_f_pow (OrZKPCommit_f_or_zkp_x zkp) (OrZKPCommit_f_or_zkp_d1 zkp))))) (PartialEq_f_eq (OrZKPCommit_f_or_zkp_b1 zkp) (Mul_f_mul (Group_f_pow (h) (OrZKPCommit_f_or_zkp_r1 zkp)) (Group_f_pow (OrZKPCommit_f_or_zkp_y zkp) (OrZKPCommit_f_or_zkp_d1 zkp))))) (PartialEq_f_eq (OrZKPCommit_f_or_zkp_a2 zkp) (Mul_f_mul (Group_f_g_pow (OrZKPCommit_f_or_zkp_r2 zkp)) (Group_f_pow (OrZKPCommit_f_or_zkp_x zkp) (OrZKPCommit_f_or_zkp_d2 zkp))))) (PartialEq_f_eq (OrZKPCommit_f_or_zkp_b2 zkp) (Mul_f_mul (Group_f_pow (h) (OrZKPCommit_f_or_zkp_r2 zkp)) (Group_f_pow (t_Div_f_div (OrZKPCommit_f_or_zkp_y zkp) (Group_f_g (tt))) (OrZKPCommit_f_or_zkp_d2 zkp)))).

Definition tally_votes `{v_G : choice_type} `{n : t_usize} `{v_A : choice_type} `{impl_205173520_ : choice_type} `{Hi0 : t_Sized (v_G)} `{Hi1 : t_Sized (v_A)} `{Hi2 : t_Sized (impl_205173520_)} `{Hi3 : t_Group (v_G)} `{Hi4 : t_HasActions (v_A)} `{Hi5 : t_HasReceiveContext (impl_205173520_) (unit)} (_ : impl_205173520_) (state : t_OvnContractState ((v_G)) (n)) : t_Result (((v_A*t_OvnContractState ((v_G)) (n)))) ((t_ParseError)) :=
  let _ := {IntoIterator_f_into_iter (Build_t_Range (0, n))} inP? [i] [is_none]default of (
    let g_pow_yi := compute_g_pow_yi (i) (OvnContractState_f_g_pow_xis state) in
    let _ := ControlFlow_Continue (if
      negb (zkp_one_out_of_two_validate (g_pow_yi) (index (OvnContractState_f_zkp_vis state) (i)))
    then
      let hoist27 := ControlFlow_Break (Result_Err (Build_t_ParseError)) in
      ControlFlow_Continue (never_to_any (hoist27))
    else
      tt) in
    if
      negb (check_commitment (index (OvnContractState_f_g_pow_xi_yi_vis state) (i)) (index (OvnContractState_f_commit_vis state) (i)))
    then
      let hoist28 := ControlFlow_Break (Result_Err (Build_t_ParseError)) in
      ControlFlow_Continue (never_to_any (hoist28))
    else
      tt) in
  let vote_result := Group_f_group_one (tt) in
  let _ := {IntoIterator_f_into_iter (OvnContractState_f_g_pow_xi_yi_vis state)} inP? [g_pow_vote] [is_none]default of (
    TODO: please implement the method `lhs_LhsLocalVar` := Mul_f_mul (vote_result) (g_pow_vote)) in
  let tally := 0 in
  let curr := Field_f_field_zero (tt) in
  let _ := {IntoIterator_f_into_iter (Build_t_Range (0, cast (n)))} inP? [i] [is_none]default of (
    let _ := if
      PartialEq_f_eq (Group_f_g_pow (curr)) (vote_result)
    then
      let _ := TODO: please implement the method `lhs_LhsLocalVar` := i in
      tt
    else
      tt in
    let _ := TODO: please implement the method `lhs_LhsLocalVar` := Add_f_add (curr) (Field_f_field_one (tt)) in
    tt) in
  let tally_votes_state_ret := Clone_f_clone (state) in
  let _ := TODO: please implement the method `lhs_LhsLocalVar` := Build_tally_votes_state_ret (tally) in
  Result_Ok ((HasActions_f_accept (tt),tally_votes_state_ret)).
